### ISSUE TITLE
TestLLTM failure

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/MONAI#1172]
**Describe the bug**
`python -m unittest -k TestLLTM` fails on my machine. From https://github.com/Project-MONAI/MONAI/pull/786, I thought it might be fixed with `python setup.py develop`, but error remains:

```
root@rb-monai-0:~/MONAI# python -m unittest -k TestLLTM
EE
======================================================================
ERROR: test_value_0 (tests.test_lltm.TestLLTM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/parameterized/parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/root/MONAI/tests/test_lltm.py", line 33, in test_value
    new_h, new_c = LLTM(**input_param)(x, (h, c))
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/MONAI/monai/networks/layers/simplelayers.py", line 230, in forward
    return LLTMFunction.apply(input, self.weights, self.bias, *state)
  File "/root/MONAI/monai/networks/layers/simplelayers.py", line 186, in forward
    outputs = _C.lltm_forward(input, weights, bias, old_h, old_cell)
  File "/root/MONAI/monai/utils/module.py", line 211, in __getattr__
    raise self._exception
  File "/root/MONAI/monai/utils/module.py", line 171, in optional_import
    pkg = __import__(module)  # top level module
monai.utils.module.OptionalImportError: import monai._C (No module named 'monai._C').

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

======================================================================
ERROR: test_value_cuda_0 (tests.test_lltm.TestLLTM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/parameterized/parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/root/MONAI/tests/test_lltm.py", line 47, in test_value_cuda
    new_h, new_c = lltm(x, (h, c))
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/MONAI/monai/networks/layers/simplelayers.py", line 230, in forward
    return LLTMFunction.apply(input, self.weights, self.bias, *state)
  File "/root/MONAI/monai/networks/layers/simplelayers.py", line 186, in forward
    outputs = _C.lltm_forward(input, weights, bias, old_h, old_cell)
  File "/root/MONAI/monai/utils/module.py", line 211, in __getattr__
    raise self._exception
  File "/opt/conda/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/opt/conda/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/opt/conda/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/opt/conda/lib/python3.8/site-packages/parameterized/parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/root/MONAI/tests/test_lltm.py", line 33, in test_value
    new_h, new_c = LLTM(**input_param)(x, (h, c))
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/MONAI/monai/networks/layers/simplelayers.py", line 230, in forward
    return LLTMFunction.apply(input, self.weights, self.bias, *state)
  File "/root/MONAI/monai/networks/layers/simplelayers.py", line 186, in forward
    outputs = _C.lltm_forward(input, weights, bias, old_h, old_cell)
  File "/root/MONAI/monai/utils/module.py", line 211, in __getattr__
    raise self._exception
  File "/root/MONAI/monai/utils/module.py", line 171, in optional_import
    pkg = __import__(module)  # top level module
monai.utils.module.OptionalImportError: import monai._C (No module named 'monai._C').

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies
```

**To Reproduce**
1. Go to MONAI root
2. python -m unittest -k TestLLTM

**Expected behavior**
Unit test should run (or state that it's skipping if a component hasn't been compiled/installed).

**Environment (please complete the following information; e.g. using `sh runtests.sh -v`):**
 - OS: Linux (4.15.0-115-generic)
 - Python version: 3.8.3 (default, May 19 2020, 18:47:26)  [GCC 7.3.0]
 - MONAI version [e.g. git commit hash]: 0.3.0+38.g3f08f0b.dirty

**Comment by wyli** [comment]
Hi @rijobro, by default the setup command doesn't do the compiling, please try this one:
```bash
BUILD_MONAI=1 python setup.py develop
```

**Comment by rijobro** [comment]
Thanks, after running that, the test now passes. 

However, the test should be skipped if the code isn't compiled. I'll PR now.
