### ISSUE TITLE
CI errors test_data_stats

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#1310]
failed randomly difficult to reproduce:
```
FAIL: test_file_0 (tests.test_data_statsd.TestDataStatsd)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/parameterized/parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/opt/monai/tests/test_data_statsd.py", line 150, in test_file
    self.assertEqual(content, expected_print)
AssertionError: '' != 'test data statistics:\nShape: (2, 2)\nVal[60 chars].0\n'
+ test data statistics:
+ Shape: (2, 2)
+ Value range: (0, 2)
+ Value: [[0 1]
+  [1 2]]
+ Additional info: 1.0
```

```
FAIL: test_file_0 (tests.test_data_stats.TestDataStats)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/parameterized/parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
DiceLoss iter: 0, acc: 0.5625
DiceLoss iter: 10, acc: 0.9375
DiceLoss iter: 20, acc: 1.0
  File "/opt/monai/tests/test_data_stats.py", line 136, in test_file
    self.assertEqual(content, expected_print)
AssertionError: '' != 'test data statistics:\nShape: (2, 2)\nVal[60 chars].0\n'
+ test data statistics:
+ Shape: (2, 2)
+ Value range: (0, 2)
+ Value: [[0 1]
+  [1 2]]
+ Additional info: 1.0
```

**Environment (please complete the following information; e.g. using `sh runtests.sh -v`):**
https://github.com/Project-MONAI/MONAI/runs/1477554074?check_suite_focus=true#step:3:5150

cc @IsaacYangSLA @YuanTingHsieh @behxyz @yanchengnv

**Comment by wyli** [comment]
looks like this error is becoming frequent, i'm attaching the log here
[ci_log.txt](https://github.com/Project-MONAI/MONAI/files/5628378/ci_log.txt)
