### ISSUE TITLE
RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by GOZGOXGOYGO** [Project-MONAI/MONAI#1328]
Hi there,

When I run the code for a time, it will come up with the RuntimeError and make the thread become all occupied. I don't know what is happening. Could you please help me solve it?

Best,
Frank

**Comment by Nic-Ma** [comment]
Hi @GOZGOXGOYGO ,

Could you please help share your error log or backtrace?

Thanks.

**Comment by GOZGOXGOYGO** [comment]
The error log is like this.
```
Traceback (most recent call last):
  File "2D_UNet_baseline.py", line 232, in <module>
    main()
  File "2D_UNet_baseline.py", line 133, in main
    for batch_data in train_loader:
  File "/home/gdp/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/gdp/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 963, in _next_data
    self._shutdown_workers()
  File "/home/gdp/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1061, in _shutdown_workers
    self._worker_result_queue.put((None, None))
  File "/home/gdp/anaconda3/envs/pytorch/lib/python3.7/multiprocessing/queues.py", line 87, in put
    self._start_thread()
  File "/home/gdp/anaconda3/envs/pytorch/lib/python3.7/multiprocessing/queues.py", line 170, in _start_thread
    self._thread.start()
  File "/home/gdp/anaconda3/envs/pytorch/lib/python3.7/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```
After that, when I open a python console and import numpy/pytorch etc. It will output this kind of log information.
```
>>> import numpy
OpenBLAS blas_thread_init: pthread_create failed for thread 38 of 40: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514152 current, 514152 max
OpenBLAS blas_thread_init: pthread_create failed for thread 39 of 40: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514152 current, 514152 max
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gdp/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/__init__.py", line 189, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import
```

**Comment by Nic-Ma** [comment]
Can you run other regular PyTorch program not related to MONAI?
And what's the MONAI program you are using?

Thanks.

**Comment by GOZGOXGOYGO** [comment]
Yes, I can run other pytorch program. And the MONAI program I am using is just like the tutorial code 2D unet training dict. Thank you.

**Comment by Nic-Ma** [comment]
Are you using MONAI docker or installed all the `requirements.txt` locally?
Could you please help call below code to provide the env details?
```py
from monai.config import print_config
print_config()
```
Seems like something related to PyTorch env settings, @wyli @ericspod have you guys seen this error before?

Thanks.

**Comment by GOZGOXGOYGO** [comment]
Here it is.
```
MONAI version: 0.3.0
Python version: 3.7.9 (default, Aug 31 2020, 12:42:55)  [GCC 7.3.0]
OS version: Linux (4.15.0-126-generic)
Numpy version: 1.19.4
Pytorch version: 1.6.0+cu101
MONAI flags: HAS_EXT = False, USE_COMPILED = False

Optional dependencies:
Pytorch Ignite version: NOT INSTALLED or UNKNOWN VERSION.
Nibabel version: 3.1.1
scikit-image version: 0.17.2
Pillow version: 8.0.0
Tensorboard version: 2.4.0
gdown version: NOT INSTALLED or UNKNOWN VERSION.
TorchVision version: 0.7.0+cu101
ITK version: 5.1.2
tqdm version: 4.50.2

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies
```

**Comment by GOZGOXGOYGO** [comment]
I create a new environment to run the code now, it seems alright. Maybe there exist some env conflict. 

Thank you.

**Comment by Nic-Ma** [comment]
sounds good!
