### ISSUE TITLE
The prediction has different direction with the original val dataset

### ISSUE THREAD

**Issue by GOZGOXGOYGO** [Project-MONAI/MONAI#1333]
Hi,

I am using NiftiSaver to save the  prediction of val dataset. However, the predict result has different direction with the original val dataset. Could you please help me find what is wrong? My code is here. It is almost the same with the code in tutorial.

```
    monai.config.print_config() 
    logging.basicConfig(stream=sys.stdout, level=logging.INFO) 
    
    datadir = '../data/'
    images_val = sorted(glob(os.path.join(datadir, './*.nii.gz')))
    segs_val = sorted(glob(os.path.join(datadir, './*.nii.gz')))  
    print('validation num is ', len(images_val))
    val_files = [{"img": img, "seg": seg} for img, seg in zip(images_val, segs_val)]

    # define transforms for image and segmentation
    val_transforms = Compose(
        [
            LoadImaged(keys=["img", "seg"]),
            AddChanneld(keys=["img", "seg"]),
            ScaleIntensityd(keys="img"),
            ToTensord(keys=["img", "seg"]),
        ]
    )

    '''
    Validation
    '''    
    # create a validation data loader
    val_ds = monai.data.Dataset(data=val_files, transform=val_transforms)
    val_loader = DataLoader(val_ds, batch_size=1, num_workers=4, collate_fn=list_data_collate)
    dice_metric = DiceMetric(include_background=True, reduction="mean")
    post_trans = Compose([Activations(sigmoid=True), AsDiscrete(threshold_values=True)])
    
    # create UNet, DiceLoss and Adam optimizer
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = monai.networks.nets.UNet(
        dimensions=2,
        in_channels=1,
        out_channels=1,
        channels=(16, 32, 64, 128, 256),
        strides=(2, 2, 2, 2),
        num_res_units=2,
    ).to(device)
    model.load_state_dict(torch.load("./results/best_metric_model.pth"))
    
    
    model.eval()
    print('evaluating...')
    with torch.no_grad():
        metric_sum = 0.0
        metric_count = 0
        saver = NiftiSaver(output_dir="./val_predict")
        for val_data in val_loader:
            val_images, val_labels = val_data["img"].to(device), val_data["seg"].to(device)
            # define sliding window size and batch size for windows inference
            roi_size = (96, 96)
            sw_batch_size = 4
            val_outputs = sliding_window_inference(val_images, roi_size, sw_batch_size, model)
            val_outputs = post_trans(val_outputs)
            value = dice_metric(y_pred=val_outputs, y=val_labels)
            metric_count += len(value)
            metric_sum += value.item() * len(value)
            saver.save_batch(val_outputs)
        metric = metric_sum / metric_count
        print("evaluation metric:", metric)
```

Best,
Frank

**Comment by Nic-Ma** [comment]
Hi @GOZGOXGOYGO ,

I think you can refer to this example:
https://github.com/Project-MONAI/tutorials/blob/master/3d_segmentation/torch/unet_evaluation_dict.py
Note that `NiftiSaver` takes affine information from metadata(which is missing in your code):
```py
saver.save_batch(val_outputs, val_data["img_meta_dict"])
```

Thanks.

**Comment by GOZGOXGOYGO** [comment]
I modify this part in my code, the prediction has the same naming index as the image has now. However, the direction still not match.

**Comment by Nic-Ma** [comment]
Hi @wyli , I want to double confirm whether the Nibabel reader/writer will change the image orientation during loading or writing? In this case, I think there are no spatial transforms at all.

Thanks.

**Comment by wyli** [comment]
orientation is defined by affine, could you share val_data["img_meta_dict"]["affine"] and val_data["img_meta_dict"]["original_affine"]

**Comment by GOZGOXGOYGO** [comment]
val_data["img_meta_dict"]["affine"]
```
tensor([[[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]], dtype=torch.float64)
```

val_data["img_meta_dict"]["original_affine"]
```
tensor([[[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]], dtype=torch.float64)
```

Thank you.

**Comment by wyli** [comment]
thanks, those affine mean both in reading and writing the volume orientation doesn't change.

maybe it's just the conventions of XY and HW makes the image 'flipped', you could try the PNG saver.

**Comment by GOZGOXGOYGO** [comment]
I try the PNGSaver, but it seems not work as well. It is strange.

```
Traceback (most recent call last):
  File "/home/gdp/anaconda3/envs/monai/lib/python3.7/site-packages/PIL/PngImagePlugin.py", line 1220, in _save
    rawmode, mode = _OUTMODES[mode]
KeyError: 'F'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "2D_UNet_baseline_evaluate_png.py", line 114, in <module>
    main()
  File "2D_UNet_baseline_evaluate_png.py", line 102, in main
    saver.save_batch(val_outputs)
  File "/home/gdp/anaconda3/envs/monai/lib/python3.7/site-packages/monai/data/png_saver.py", line 118, in save_batch
    self.save(data, {k: meta_data[k][i] for k in meta_data} if meta_data else None)
  File "/home/gdp/anaconda3/envs/monai/lib/python3.7/site-packages/monai/data/png_saver.py", line 107, in save
    scale=self.scale,
  File "/home/gdp/anaconda3/envs/monai/lib/python3.7/site-packages/monai/data/png_writer.py", line 79, in write_png
    img.save(file_name, "PNG")
  File "/home/gdp/anaconda3/envs/monai/lib/python3.7/site-packages/PIL/Image.py", line 2151, in save
    save_handler(self, fp, filename)
  File "/home/gdp/anaconda3/envs/monai/lib/python3.7/site-packages/PIL/PngImagePlugin.py", line 1222, in _save
    raise OSError(f"cannot write mode {mode} as PNG") from e
OSError: cannot write mode F as PNG
```

**Comment by wyli** [comment]
this is a data type issue, please convert the model output to integers

**Comment by sulaimanvesal** [comment]
Hi @wyli,

I have got one question:

Is there anyway to reverse back the "Applied operations"  and save the model predictions in the original size/spacing/before-cropping? 

I can see the that meta_data_dict store all the pre-processing operations in "Applied Operations" tag, and I can access and reconstruct back my predictions in original size based on these stored parameters. However, I was wondering if there is already a built-in function that does this?

Thank you.

  ```
valid_transform = Compose([
        LoadImaged(keys=['image_t2', 'image_adc','image_dwi', 'label']), 
        AddChanneld(keys=['image_t2', 'image_adc','image_dwi', 'label']),
        Spacingd(keys=['image_t2', 'image_adc','image_dwi', "label"], pixdim=[0.5, 0.5, 3.0], mode=("bilinear",
                                                                                                    "bilinear",
                                                                                                    "bilinear", "nearest")),

        CenterSpatialCropd(keys=['image_t2', 'image_adc','image_dwi', 'label'], roi_size = [256, 256, 20], 
        ConcatItemsd(keys=['image_t2', 'image_adc','image_dwi'], name="image"),
        #NormalizeIntensityd(keys=['image'], nonzero=True, channel_wise=True),
        Lambdad(keys="image", func=lambda x: x / x.max()),
        ToTensord(keys=['image', 'label'])
    ])
```

```
Applied operations
[ [ { class: 'SpatialResample',
      extra_info: { 'align_corners': False,
                    'dtype': 'float64',
                    'mode': 'bilinear',
                    'padding_mode': 'border',
                    'src_affine': tensor([[-3.4226e-01,  0.0000e+00,  0.0000e+00,  1.7958e+02],
        [ 0.0000e+00, -3.1792e-01, -1.1112e+00,  1.5292e+02],
        [ 0.0000e+00, -1.2677e-01,  2.7866e+00, -6.5497e+01],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00]],
       dtype=torch.float64)},
      id: 2745328190176,
      orig_size: (1024, 1024, 27)},
    { class: 'CenterSpatialCrop',
      extra_info: {'cropped': [222, 223, 222, 223, 3, 4]},
      id: 2745328190272,
      orig_size: (701, 701, 27)},
    { class: 'SpatialPad',
      extra_info: {'padded': [(0, 0), (0, 0), (0, 0), (0, 0)]},
      id: 2745328190464,
      orig_size: (256, 256, 20)}]]
```

**Comment by wyli** [comment]
sure, if you are using v0.9.1 monai, you can run the inverse directly, something like this:
```py
...
dataset = Dataset(filenames, transform=valid_transform)
loader = monai.data.DataLoader(dataset, batch_size=3, shuffle=False)
for x in loader:
    for data in monai.data.decollate_batch(x):
        inverted = valid_transform.inverse(data)
...
```

**Comment by sulaimanvesal** [comment]
Thank you @wyli. I did so but it throws the following error:


``` Python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\anaconda3\envs\Pytorch_env\lib\site-packages\monai\transforms\transform.py in apply_transform(transform, data, map_items, unpack_items, log_stats)
     88         if isinstance(data, (list, tuple)) and map_items:
---> 89             return [_apply_transform(transform, item, unpack_items) for item in data]
     90         return _apply_transform(transform, data, unpack_items)

~\anaconda3\envs\Pytorch_env\lib\site-packages\monai\transforms\transform.py in <listcomp>(.0)
     88         if isinstance(data, (list, tuple)) and map_items:
---> 89             return [_apply_transform(transform, item, unpack_items) for item in data]
     90         return _apply_transform(transform, data, unpack_items)

~\anaconda3\envs\Pytorch_env\lib\site-packages\monai\transforms\transform.py in _apply_transform(transform, parameters, unpack_parameters)
     53 
---> 54     return transform(parameters)
     55 

~\anaconda3\envs\Pytorch_env\lib\site-packages\monai\transforms\utility\dictionary.py in inverse(self, data)
    515     def inverse(self, data: Mapping[Hashable, NdarrayOrTensor]) -> Dict[Hashable, NdarrayOrTensor]:
--> 516         d = dict(data)
    517         for key in self.key_iterator(d):

ValueError: dictionary update sequence element #0 has length 256; 2 is required

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
<ipython-input-106-eb9d00758d0d> in <module>
     55                 for val_pred_tensor in val_outputs_list
     56             ]
---> 57             inverted = val_transform.inverse(val_outputs_list)
     58             print(inverted.shape)
     59 

~\anaconda3\envs\Pytorch_env\lib\site-packages\monai\transforms\compose.py in inverse(self, data)
    181         # loop backwards over transforms
    182         for t in reversed(invertible_transforms):
--> 183             data = apply_transform(t.inverse, data, self.map_items, self.unpack_items, self.log_stats)
    184         return data
    185 

~\anaconda3\envs\Pytorch_env\lib\site-packages\monai\transforms\transform.py in apply_transform(transform, data, map_items, unpack_items, log_stats)
    112             else:
    113                 _log_stats(data=data)
--> 114         raise RuntimeError(f"applying transform {transform}") from e
    115 
    116 

RuntimeError: applying transform <bound method ToTensord.inverse of <monai.transforms.utility.dictionary.ToTensord object at 0x0000027FAE56DC10>>
```

My inference code based on your suggestion.

``` Python

valid_transform = Compose([
      LoadImaged(keys=['image_t2', 'image_adc','image_dwi', 'label']), 
      AddChanneld(keys=['image_t2', 'image_adc','image_dwi', 'label']),
      Spacingd(keys=['image_t2', 'image_adc','image_dwi', "label"], pixdim=[0.5, 0.5, 3.0], mode=("bilinear",
                                                                                                  "bilinear",
                                                                                                  "bilinear", "nearest")),

      CenterSpatialCropd(keys=['image_t2', 'image_adc','image_dwi', 'label'], roi_size = [256, 256, 20], 
      ConcatItemsd(keys=['image_t2', 'image_adc','image_dwi'], name="image"),
      Lambdad(keys="image", func=lambda x: x / x.max()),
      ToTensord(keys=['image', 'label'])
  ])

val_ds = data.Dataset(data=data_dicts_valid, transform=valid_transform)
val_loader = data.DataLoader( val_ds,
      batch_size=1,
      shuffle=False,
      num_workers=0, ##collate_fn=list_data_collate,
      pin_memory=False
  )

with torch.no_grad():
    for idx, batch_data in enumerate(val_loader):
        data, target = batch_data["image"].to(device), batch_data["label"].to(device)
        logits = model_inferer_test(data)
        val_labels_list = decollate_batch(target)
        val_outputs_list = decollate_batch(logits)
        val_output_convert = [
            post_pred(post_sigmoid(val_pred_tensor))
            for val_pred_tensor in val_outputs_list
        ]
        
        # reverse operation, transform the prediction to match the ground-truth label
        # with original size, spacing, before-center-crop.
        inverted = val_transform.inverse(val_outputs_list)
```

**Comment by wyli** [comment]
Yes, pls make sure the input of val_transform.inverse is a ditionary of metatensors. The result of decollate_batch is a list of dictionary of metatensors.

**Comment by sulaimanvesal** [comment]
Is there any working example for this val_transform.inverse? I made sure the input is  a ditionary of metatensors but same error. 

May I know, how do you access "Applied operations" element in metatensor? Even though it's a dict but I can't access the transformation elements directly. If I can only get the image size (orig_size) after resampling, then I can write the other part myself and no need for val_transform.inverse.

**Comment by wyli** [comment]
yes -- https://github.com/Project-MONAI/tutorials/blob/main/modules/inverse_transforms_and_test_time_augmentations.ipynb

**Comment by KumoLiu** [comment]
> Is there any working example for this val_transform.inverse? I made sure the input is a ditionary of metatensors but same error.
> 
> May I know, how do you access "Applied operations" element in metatensor? Even though it's a dict but I can't access the transformation elements directly. If I can only get the image size (orig_size) after resampling, then I can write the other part myself and no need for val_transform.inverse.

Hi @sulaimanvesal,
Your last tranform `Totensord` will transform your data from `MetaTensor` to tensor, you can just remove this transform and try again. Hope it will help you!
