### ISSUE TITLE
Sizes of tensors must match except in dimension 4. Got 18 and 17

### ISSUE THREAD

**Issue by itruonghai** [Project-MONAI/MONAI#1754]
**I try to train Monai with Unet (the architecture is the same as the tutorial at 
https://github.com/Project-MONAI/tutorials/blob/master/3d_segmentation/spleen_segmentation_3d.ipynb**
Please help me to fix this bug
```
Traceback (most recent call last):
  File "/home/pqdung/segmentation_3d.py", line 247, in <module>
    outputs = model(inputs)
  File "/home/pqdung/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pqdung/.local/lib/python3.6/site-packages/monai/networks/nets/unet.py", line 189, in forward
    x = self.model(x)
  File "/home/pqdung/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pqdung/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/pqdung/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pqdung/.local/lib/python3.6/site-packages/monai/networks/layers/simplelayers.py", line 125, in forward
    y = self.submodule(x)
  File "/home/pqdung/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pqdung/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/pqdung/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pqdung/.local/lib/python3.6/site-packages/monai/networks/layers/simplelayers.py", line 125, in forward
    y = self.submodule(x)
  File "/home/pqdung/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pqdung/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/pqdung/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pqdung/.local/lib/python3.6/site-packages/monai/networks/layers/simplelayers.py", line 128, in forward
    return torch.cat([x, y], dim=self.dim)
RuntimeError: Sizes of tensors must match except in dimension 4. Got 18 and 17 (The offending index is 0)

 

Process finished with exit code 1
```
The U-net architecture is defined as
```
# standard PyTorch program style: create UNet, DiceLoss and Adam optimizer
device = torch.device("cuda:0")
model = UNet(
    dimensions=3,
    in_channels=1,
    out_channels=2,
    channels=(16, 32, 64, 128, 256),
    strides=(2, 2, 2, 2),
    num_res_units=2,
    norm=Norm.BATCH,
).to(device)
loss_function = DiceLoss(to_onehot_y=True, softmax=True)
optimizer = torch.optim.Adam(model.parameters(), 1e-4)
```
I try to segment 1 class (tumor only)

**Comment by rijobro** [comment]
What transforms are you using? And what is your batch size for training, validation and testing?

**Comment by itruonghai** [comment]
> What transforms are you using (training, validation and testing)? And what is your batch size (also training, validation and testing)?

I just use loadimage, addchanel and then toTensord
```
train_transforms = Compose(
    [
        LoadImaged(keys=["image", "label"]),
        AddChanneld(keys=["image", "label"]),
        ToTensord(keys=["image", "label"]),
    ]
)
val_transforms = Compose(
    [
        LoadImaged(keys=["image", "label"]),
        AddChanneld(keys=["image", "label"]),
        ToTensord(keys=["image", "label"]),
    ]
)
```

My train batch size is 2 now (by default), I have use a batch size equal to 1 but it didn't work too. It raises an error on outputs = model(inputs). Is there any mismatch?

**Comment by rijobro** [comment]
And what size are your input images?

**Comment by itruonghai** [comment]
> And what size are your input images?

My input image is from NIFTI images (512x512), when it feeds into the data loader, the image has the input shape as 1,1,512,512,132 with 512x512 is the image shape and 132 is the number of images in the first NIFTI

**Comment by mtsale** [comment]
If all your images (train, validation, testing) are definitely the same size in all dimensions, then the problem might be in the '132'.  Make that last dimension divisible by pool size^depth. For example 2^4 = 16. So either pad or crop your images to a multiple of 16. Another way to do it is with patches. The spleen example crops the patches to 96. This is the best approach because the big images take up quite a bit of memory.

**Comment by itruonghai** [comment]
> If all your images (train, validation, testing) are definitely the same size in all dimensions, then the problem might be in the '132'. Make that last dimension divisible by pool size^depth. For example 2^4 = 16. So either pad or crop your images to a multiple of 16. Another way to do it is with patches. The spleen example crops the patches to 96. This is the best approach because the big images take up quite a bit of memory.

Is there any transform to make the image size maintains the same (like 512 x 512). I change the RandCropByPosNegLabeld to
```
RandCropByPosNegLabeld(
            keys=["image", "label"],
            label_key="label",
            spatial_size=(512, 512, 96),
            pos=1,
            neg=1,
            num_samples=4,
            image_key="image",
            image_threshold=0,
        ),
``` 
Or can we change from Crop the Image to Pad the images? Hope you will help me.

**Comment by mtsale** [comment]
You can keep your input images as 512x512 and use the Monai transforms to do patch wise cropping (don't worry your network will reassemble them later if you are copying the spleen example code). Try a simple RandSpatialCropD ~ look at the brats segmentation tutorial. 

Get that working first then try and change small things to see if they make an improvement to your segmentations.
