### ISSUE TITLE
PR #1778 causes error

### ISSUE THREAD

**Issue by behxyz** [Project-MONAI/MONAI#1798]
**Describe the bug**
PR #1778 has broken a Clara Train MMAR that uses RandomZoomD.

```
Original Traceback (most recent call last):
  File "/workspace/MONAI/monai/data/utils.py", line 257, in list_data_collate
    return default_collate(data)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 73, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 73, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 83, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 83, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 73, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 73, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 73, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 73, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 81, in default_collate
    raise RuntimeError('each element in list of batch should be of equal size')
RuntimeError: each element in list of batch should be of equal size

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/workspace/MONAI/monai/data/utils.py", line 266, in list_data_collate
    raise RuntimeError(re_str)
RuntimeError: each element in list of batch should be of equal size
```

**Comment by behxyz** [comment]
@wyli @rijobro, it seems that this PR requires more testing.

**Comment by wyli** [comment]
thanks, could you share the version info: `python -c 'import monai; monai.config.print_debug_info()'` of this error stack, and the input parameters of `RandZoomD`?

**Comment by wyli** [comment]
would be great to follow the bug report template to provide debug info as much as possible, so that we could address this efficiently. "PR #1778 causes error" jumps to the conclusions too quickly

**Comment by behxyz** [comment]
```
================================
Printing MONAI config...
================================
MONAI version: 0.3.0+305.gf8fe3b1.dirty
Numpy version: 1.20.1
Pytorch version: 1.8.0a0+1606899
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: f8fe3b1e72228215f0295121bf8ea3fbdf8be319

Optional dependencies:
Pytorch Ignite version: 0.4.4
Nibabel version: 3.2.1
scikit-image version: 0.18.1
Pillow version: 8.1.0
Tensorboard version: 2.4.1
gdown version: 3.12.2
TorchVision version: 0.9.0a0
ITK version: 5.1.2
tqdm version: 4.57.0
lmdb version: 1.1.1
psutil version: 5.8.0

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies


================================
Printing system config...
================================
System: Linux
Linux version: Ubuntu 20.04.1 LTS
Platform: Linux-5.8.0-43-generic-x86_64-with-glibc2.10
Processor: x86_64
Machine: x86_64
Python version: 3.8.5
Process name: python
Command: ['python', '-c', 'import monai; monai.config.print_debug_info()']
Open files: []
Num physical CPUs: 8
Num logical CPUs: 16
Num usable CPUs: 16
CPU usage (%): [10.4, 9.1, 97.4, 10.5, 10.3, 11.5, 7.9, 9.1, 10.3, 10.1, 9.0, 7.8, 10.3, 9.1, 9.1, 9.1]
CPU freq. (MHz): 1201
Load avg. in last 1, 5, 15 mins (%): [0.0, 2.9, 12.0]
Disk usage (%): 87.0
Avg. sensor temp. (Celsius): UNKNOWN for given OS
Total physical memory (GB): 31.1
Available memory (GB): 27.8
Used memory (GB): 2.8

================================
Printing GPU config...
================================
Num GPUs: 2
Has CUDA: True
CUDA version: 11.1
cuDNN enabled: True
cuDNN version: 8005
Current device: 0
Library compiled for CUDA architectures: ['sm_52', 'sm_60', 'sm_61', 'sm_70', 'sm_75', 'sm_80', 'sm_86', 'compute_86']
GPU 0 Name: TITAN RTX
GPU 0 Is integrated: False
GPU 0 Is multi GPU board: False
GPU 0 Multi processor count: 72
GPU 0 Total memory (GB): 23.7
GPU 0 Cached memory (GB): 0.0
GPU 0 Allocated memory (GB): 0.0
GPU 0 CUDA capability (maj.min): 7.5
GPU 1 Name: TITAN RTX
GPU 1 Is integrated: False
GPU 1 Is multi GPU board: False
GPU 1 Multi processor count: 72
GPU 1 Total memory (GB): 23.7
GPU 1 Cached memory (GB): 0.0
GPU 1 Allocated memory (GB): 0.0
GPU 1 CUDA capability (maj.min): 7.5
```

**Comment by behxyz** [comment]
Here are the input args: 
```
        "name": "RandZoomD",
        "args": {
          "keys": "image",
          "prob": 0.5,
          "min_zoom": 0.9,
          "max_zoom": 1.1
        }
```

**Comment by wyli** [comment]
currently I couldn't locate the issue, just quick comments atm:
1. MONAI version: 0.3.0+305.gf8fe3b1.dirty, "dirty" means there're some changes based on `f8fe3b1` which is this version https://github.com/Project-MONAI/MONAI/tree/f8fe3b1e72228215f0295121bf8ea3fbdf8be319 could you retry with `git checkout f8fe3b1e72228215f0295121bf8ea3fbdf8be319`
1. the error msg check is too strict that capture useful info for this case, I think this could be improved? @rijobro 
https://github.com/Project-MONAI/MONAI/blob/f8fe3b1e72228215f0295121bf8ea3fbdf8be319/monai/data/utils.py#L260

**Comment by behxyz** [comment]
If it helps, I updated to the latest commit and remove all the local changes and untracked files. The same happens!
```
================================
Printing MONAI config...
================================
MONAI version: 0.3.0+305.g053d0c8
Numpy version: 1.20.1
Pytorch version: 1.8.0a0+1606899
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: 053d0c8aab5bf038b65300bf2632fc0be7a10991

Optional dependencies:
Pytorch Ignite version: 0.4.4
Nibabel version: 3.2.1
scikit-image version: 0.18.1
Pillow version: 8.1.0
Tensorboard version: 2.4.1
gdown version: 3.12.2
TorchVision version: 0.9.0a0
ITK version: 5.1.2
tqdm version: 4.57.0
lmdb version: 1.1.1
psutil version: 5.8.0
```

**Comment by behxyz** [comment]
When I checkout the commit just before PR#1778, all goes back to normal and work as before (`46154ec78fb41680561fe275068c52dcd073faa5`).

**Comment by rijobro** [comment]
Thanks for bringing this to my attention, I'll sort it first thing tomorrow!
