### ISSUE TITLE
Problem with pip install monai and monai-weekly

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/MONAI#1902]
**Describe the bug**
There seem to be some confusing things going on with `pip install monai` and `pip install monai-weekly`.

**To Reproduce**
Steps to reproduce the behavior (monai installed first):
1. Fresh python venv
2. pip install monai monai-weekly
3. python -c "import monai"

Error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rbrown/.conda/lib/python3.8/site-packages/monai/__init__.py", line 46, in <module>
    load_submodules(sys.modules[__name__], True, exclude_pattern=excludes)
  File "/home/rbrown/.conda/lib/python3.8/site-packages/monai/utils/module.py", line 75, in load_submodules
    mod = import_module(name)
  File "/home/rbrown/.conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/rbrown/.conda/lib/python3.8/site-packages/monai/data/nifti_reader.py", line 17, in <module>
    from monai.transforms import LoadNifti, Randomizable, apply_transform
ImportError: cannot import name 'LoadNifti' from 'monai.transforms' (/home/rbrown/.conda/lib/python3.8/site-packages/monai/transforms/__init__.py)
```

Steps to reproduce the behavior (monai-weekly installed first):
1. Fresh python venv
2. pip install monai-weekly monai
3. python -c "import monai"

Error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rbrown/.conda/lib/python3.8/site-packages/monai/__init__.py", line 43, in <module>
    load_submodules(sys.modules[__name__], False, exclude_pattern=excludes)
  File "/home/rbrown/.conda/lib/python3.8/site-packages/monai/utils/module.py", line 75, in load_submodules
    mod = import_module(name)
  File "/home/rbrown/.conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/rbrown/.conda/lib/python3.8/site-packages/monai/apps/pathology/__init__.py", line 12, in <module>
    from .datasets import PatchWSIDataset, SmartCacheDataset
  File "/home/rbrown/.conda/lib/python3.8/site-packages/monai/apps/pathology/datasets.py", line 18, in <module>
    from monai.data.image_reader import WSIReader
ImportError: cannot import name 'WSIReader' from 'monai.data.image_reader' (/home/rbrown/.conda/lib/python3.8/site-packages/monai/data/image_reader.py)
```

It seems the two are treated as two separate packages but installed on top of each other, causing conflicts.

I think if we solve this we can also simplify the `python -c "import monai" || pip install monai-weekly` back to how it was previously (`%pip install monai-weekly`), which will improve readability.

Would it be possible to remove `monai-weekly` and enable something like this: `pip install monai==weekly`? In that fashion we would only have one repository so the problem would have to resolve itself.

**Comment by wyli** [comment]
I think we are trying to follow the `tensorflow` and `tf-nightly` approach here. we also discussed using something like `v0.5.dev2102` to denote the weekly build, to install it the command will be `pip install --pre monai`

**Comment by rijobro** [comment]
Not sure if tensorflow have the same problem as us, but it sounds like switching to `--pre` would solve our problem. Is there any reason not to switch?

**Comment by wyli** [comment]
it seems it's slightly easier to track the milestone releases' traffic.
