### ISSUE TITLE
CRFTestCaseCuda test case issue

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#2023]
**Describe the bug**
one of the test cases of `tests.test_crf_cuda.CRFTestCaseCuda` fails randomly (with a small chance)

**To Reproduce**
this error 
e.g. CI log: https://github.com/Project-MONAI/MONAI/runs/2361733732?check_suite_focus=true#step:6:7821
```
======================================================================
FAIL: test_2_1_batche_s_3_dimension_s_2_classe_s_1_channel_s_ (tests.test_crf_cuda.CRFTestCaseCuda)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/parameterized/parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/__w/MONAI/MONAI/tests/test_crf_cuda.py", line 447, in test
    np.testing.assert_allclose(output, expected, atol=1e-3, rtol=1e-3)
  File "/usr/local/lib/python3.6/dist-packages/numpy/testing/_private/utils.py", line 1528, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/usr/local/lib/python3.6/dist-packages/numpy/testing/_private/utils.py", line 840, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.001, atol=0.001

Mismatched elements: 63 / 250 (25.2%)
Max absolute difference: 0.021
Max relative difference: 0.114
```

**Expected behavior**
no failure for this test case

cc @charliebudd

**Comment by charliebudd** [comment]
Thanks for pointing this out, I've tried it quite a number of times and cant repeat the error in the environment specified. I can raise the diff threshold so that its not in any bodies way and open a seperate issue to investigate this fully in the future?

**Comment by wyli** [comment]
this is still an issue from two different runs:
```
======================================================================
FAIL: test_2_1_batche_s_3_dimension_s_2_classe_s_1_channel_s_ (tests.test_crf_cuda.CRFTestCaseCuda)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/parameterized/parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/__w/MONAI/MONAI/tests/test_crf_cuda.py", line 447, in test
    np.testing.assert_allclose(output, expected, atol=5e-2, rtol=5e-2)
  File "/opt/conda/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 1527, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/opt/conda/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 840, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.05, atol=0.05

Mismatched elements: 6 / 250 (2.4%)
Max absolute difference: 0.13990143
Max relative difference: 0.7867256
 x: array([[[[[1.000000e+00, 1.000000e+00, 1.000000e+00, 9.998817e-01,
           7.638893e-01],
          [1.000000e+00, 1.000000e+00, 1.000000e+00, 9.998482e-01,...
 y: array([[[[[1.00000e+00, 1.00000e+00, 1.00000e+00, 9.99884e-01,
           7.69625e-01],
          [1.00000e+00, 1.00000e+00, 1.00000e+00, 9.99851e-01,...

----------------------------------------------------------------------
```

```
======================================================================
FAIL: test_2_1_batche_s_3_dimension_s_2_classe_s_1_channel_s_ (tests.test_crf_cuda.CRFTestCaseCuda)
----------------------------------------------------------------------
test_read_whole_image_0__opt_monai_tests_testing_data_temp_CMU_1_tiff (tests.test_cuimage_reader.TestCuCIMReader) (11.2s)
test_read_patches_cucim_0 (tests.test_masked_inference_wsi_dataset.TestMaskedInferenceWSIDataset) (11.5s)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/parameterized/parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/opt/monai/tests/test_crf_cuda.py", line 447, in test
    np.testing.assert_allclose(output, expected, atol=5e-2, rtol=5e-2)
  File "/opt/conda/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 1527, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/opt/conda/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 840, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.05, atol=0.05

Mismatched elements: 6 / 250 (2.4%)
Max absolute difference: 0.139
Max relative difference: 1.116
 x: array([[[[[1.      , 1.      , 1.      , 0.999882, 0.764651],
          [1.      , 1.      , 1.      , 0.999849, 0.708416],
          [1.      , 1.      , 0.999988, 0.997086, 0.608003],...
 y: array([[[[[1.      , 1.      , 1.      , 0.999884, 0.769625],
          [1.      , 1.      , 1.      , 0.999851, 0.714004],
          [1.      , 1.      , 0.999988, 0.99715 , 0.614165],...

----------------------------------------------------------------------
```

**Comment by charliebudd** [comment]
Thanks wenqi. We can raise the error tolerance higher but this could still flare up occasionally. While unconventional, what might be more effective is to raise the tolerance in the number of mismatched elements. This bug is my priority so should be getting it sorted soon.
