### ISSUE TITLE
print_config, print_debug_info etc not working.

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/MONAI#2143]
**Describe the bug**
On both my local MacOS and remote linux, calling `print_config()` and `print_debug_info()` returns mostly blank:

```
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: 234d9c3b9f6d1aa09358db9d4c894a0a5f5656a1
Printing system config...
Printing GPU config...
```

Further, trying to use tab autocomplete results in the following error: 

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/jedi/cache.py", line 109, in wrapper
    return dct[key]
KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/IPython/terminal/ptutils.py", line 115, in get_completions
    yield from self._get_completions(body, offset, cursor_position, self.ipy_completer)
  File "/opt/conda/lib/python3.8/site-packages/IPython/terminal/ptutils.py", line 131, in _get_completions
    for c in completions:
  File "/opt/conda/lib/python3.8/site-packages/IPython/core/completer.py", line 444, in _deduplicate_completions
    completions = list(completions)
  File "/opt/conda/lib/python3.8/site-packages/IPython/core/completer.py", line 1837, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/opt/conda/lib/python3.8/site-packages/IPython/core/completer.py", line 1894, in _completions
    signature = _make_signature(jm)
  File "/opt/conda/lib/python3.8/site-packages/IPython/core/completer.py", line 1001, in _make_signature
    signatures = completion.get_signatures()
  File "/opt/conda/lib/python3.8/site-packages/jedi/api/classes.py", line 572, in get_signatures
    for s in self._get_signatures()
  File "/opt/conda/lib/python3.8/site-packages/jedi/api/classes.py", line 561, in _get_signatures
    return [sig for name in names for sig in name.infer().get_signatures()]
  File "/opt/conda/lib/python3.8/site-packages/jedi/api/classes.py", line 561, in <listcomp>
    return [sig for name in names for sig in name.infer().get_signatures()]
  File "/opt/conda/lib/python3.8/site-packages/jedi/cache.py", line 111, in wrapper
    result = method(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/jedi/inference/compiled/mixed.py", line 129, in infer
    return _create(self._inference_state, compiled_value, module_context)
  File "/opt/conda/lib/python3.8/site-packages/jedi/inference/cache.py", line 43, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/jedi/inference/compiled/mixed.py", line 257, in _create
    result = _find_syntax_node_name(inference_state, python_object)
  File "/opt/conda/lib/python3.8/site-packages/jedi/inference/compiled/mixed.py", line 237, in _find_syntax_node_name
    code_lines = get_cached_code_lines(inference_state.grammar, path)
  File "/opt/conda/lib/python3.8/site-packages/jedi/parser_utils.py", line 280, in get_cached_code_lines
    return parser_cache[grammar._hashed][path].lines
KeyError: '/home/rbrown/Documents/Code/MONAI/monai/config/deviceconfig.py'
```

I see that `deviceconfig.py` was recently changed: https://github.com/Project-MONAI/MONAI/commit/36d855c690f03a44554f7017417cf7fdb12b8477. @wyli do you think it could be due to this?

**Comment by wyli** [comment]
that was to remove the loop variable errors detected by LGTM: https://lgtm.com/projects/g/Project-MONAI/MONAI/rev/pr-4e7d3632955aa6c4418d1c84db746dbdb2974865 the test looks ok: https://github.com/Project-MONAI/MONAI/runs/2432476132#step:6:1172 I couldn't reproduce this issue...

**Comment by rijobro** [comment]
Strangely both local and remote are working for me today ¯\_(ツ)_/¯
