### ISSUE TITLE
Saving NiFTI images with resampling raises memory error

### ISSUE THREAD

**Issue by shawnfan19** [Project-MONAI/MONAI#2316]
Hello!

I have created the following pipeline and run it on some NiFTI images here (https://drive.google.com/drive/folders/1r2_0RTHFN8XfSLnSgMGYZuQXuhEpP4NC?usp=sharing). I would like to save the processed images as NiFTI because I am processing >10,000 images before training a neural network. Instead of having to process all images every epoch, I would like to save them as temporary files until training is complete. 

```python
preprocess_transform = Compose([
    LoadImaged(keys=["img"]),
    AsChannelFirstd(keys=["img"], channel_dim=-1),
    Spacingd(keys=["img"], pixdim=(2, 2, 2), diagonal=True, mode="bilinear"),
    ScaleIntensityd(keys=["img"], minv=0, maxv=1),
    SaveImaged(
                    keys=["img"],
                    output_dir="./visualization",
                    output_ext=".nii",
                    resample=True,
     ),
    ToTensord(keys=["img"])
])
```

Without resampling, the saved images appear distorted and shorn, but with resampling, the following error is received. It appears that the affine transform requires >200,000 GB of memory?

Modifying image pixdim from [1.01821 1.01821 2.025   0.     ] to [  1.01821005   1.01821005   2.0250001  898.17486327]
input data information of the runtime error transform:
img statistics:
Type: <class 'numpy.ndarray'>
Shape: (1, 172, 172, 82)
Value range: (0.0, 1.0)
img_meta_dict statistics:
Type: <class 'dict'>
Value: {'sizeof_hdr': array(1543569408, dtype=int32), 'extents': array(4194304, dtype=int32), 'session_error': array(0, dtype=int16), 'dim_info': array(0, dtype=uint8), 'dim': array([ 1024, 20481, 20481, 20736,   256,     0,     0,     0],
      dtype=int16), 'intent_p1': array(0., dtype=float32), 'intent_p2': array(0., dtype=float32), 'intent_p3': array(0., dtype=float32), 'intent_code': array(0, dtype=int16), 'datatype': array(4096, dtype=int16), 'bitpix': array(8192, dtype=int16), 'slice_start': array(0, dtype=int16), 'pixdim': array([ 4.6006030e-41, -7.9165687e-07, -7.9165687e-07, -6.3281336e-23,
        4.0563766e-09,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
      dtype=float32), 'vox_offset': array(0., dtype=float32), 'scl_slope': array(6.9055e-41, dtype=float32), 'scl_inter': array(6.9055e-41, dtype=float32), 'slice_end': array(0, dtype=int16), 'slice_code': array(0, dtype=uint8), 'xyzt_units': array(2, dtype=uint8), 'cal_max': array(0., dtype=float32), 'cal_min': array(0., dtype=float32), 'slice_duration': array(0., dtype=float32), 'toffset': array(0., dtype=float32), 'glmax': array(0, dtype=int32), 'glmin': array(0, dtype=int32), 'qform_code': array(256, dtype=int16), 'sform_code': array(0, dtype=int16), 'quatern_b': array(0., dtype=float32), 'quatern_c': array(0., dtype=float32), 'quatern_d': array(0., dtype=float32), 'qoffset_x': array(-3.216494e+31, dtype=float32), 'qoffset_y': array(1.5721015e+19, dtype=float32), 'qoffset_z': array(5.8155804e-15, dtype=float32), 'srow_x': array([0., 0., 0., 0.], dtype=float32), 'srow_y': array([0., 0., 0., 0.], dtype=float32), 'srow_z': array([0., 0., 0., 0.], dtype=float32), 'affine': array([[  2.        ,   0.        ,   0.        , 507.58554077],
       [  0.        ,   2.        ,   0.        , 689.41204834],
       [  0.        ,   0.        ,   2.        , 271.63400269],
       [  0.        ,   0.        ,   0.        ,   1.        ]]), 'original_affine': array([[  1.01821005,   0.        ,   0.        , 507.58554077],
       [  0.        ,   1.01821005,   0.        , 689.41204834],
       [  0.        ,   0.        ,   2.0250001 , 271.63400269],
       [  0.        ,   0.        ,   0.        ,   1.        ]]), 'as_closest_canonical': False, 'spatial_shape': array([20481, 20481, 20736], dtype=int16), 'original_channel_dim': -1, 'filename_or_obj': '/scratch/sfan/AV45/I174732/ADNI_023_S_0376_PT_PET_Brain_AV45_recon_br_raw_20100527082453889_6_S85655_I174732.nii'}
img_transforms statistics:
Type: <class 'list'>
Value: [{'class': 'Spacingd', 'id': 23314182078984, 'orig_size': (336, 336, 81), 'extra_info': {'meta_data_key': 'img_meta_dict', 'old_affine': array([[  1.01821005,   0.        ,   0.        , 507.58554077],
       [  0.        ,   1.01821005,   0.        , 689.41204834],
       [  0.        ,   0.        ,   2.0250001 , 271.63400269],
       [  0.        ,   0.        ,   0.        ,   1.        ]]), 'mode': 'bilinear', 'padding_mode': 'border', 'align_corners': False}}]
Traceback (most recent call last):
  File "/home/sfan/anaconda3/envs/torch_monai/lib/python3.6/site-packages/monai/transforms/transform.py", line 48, in apply_transform
    return transform(data)
  File "/home/sfan/anaconda3/envs/torch_monai/lib/python3.6/site-packages/monai/transforms/io/dictionary.py", line 231, in __call__
    self._saver(img=d[key], meta_data=meta_data)
  File "/home/sfan/anaconda3/envs/torch_monai/lib/python3.6/site-packages/monai/transforms/io/array.py", line 282, in __call__
    self.saver.save(img, meta_data)
  File "/home/sfan/anaconda3/envs/torch_monai/lib/python3.6/site-packages/monai/data/nifti_saver.py", line 157, in save
    output_dtype=self.output_dtype,
  File "/home/sfan/anaconda3/envs/torch_monai/lib/python3.6/site-packages/monai/data/nifti_writer.py", line 150, in write_nifti
    spatial_size=output_spatial_shape_[: len(data.shape)],
  File "/home/sfan/anaconda3/envs/torch_monai/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sfan/anaconda3/envs/torch_monai/lib/python3.6/site-packages/monai/networks/layers/spatial_transforms.py", line 539, in forward
    grid = nn.functional.affine_grid(theta=theta[:, :sr], size=list(dst_size), align_corners=self.align_corners)
  File "/home/sfan/anaconda3/envs/torch_monai/lib/python3.6/site-packages/torch/nn/functional.py", line 3933, in affine_grid
    return torch.affine_grid_generator(theta, size, align_corners)
RuntimeError: [enforce fail at CPUAllocator.cpp:67] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 278341060534272 bytes. Error code 12 (Cannot allocate memory)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sfan/anaconda3/envs/torch_monai/lib/python3.6/site-packages/monai/transforms/transform.py", line 48, in apply_transform
    return transform(data)
  File "/home/sfan/anaconda3/envs/torch_monai/lib/python3.6/site-packages/monai/transforms/compose.py", line 144, in __call__
    input_ = apply_transform(_transform, input_)
  File "/home/sfan/anaconda3/envs/torch_monai/lib/python3.6/site-packages/monai/transforms/transform.py", line 71, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.io.dictionary.SaveImaged object at 0x1534418a82e8>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "preprocess.py", line 83, in <module>
    for i, batch in enumerate(check_loader):
  File "/home/sfan/anaconda3/envs/torch_monai/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/sfan/anaconda3/envs/torch_monai/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/sfan/anaconda3/envs/torch_monai/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/sfan/anaconda3/envs/torch_monai/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/sfan/anaconda3/envs/torch_monai/lib/python3.6/site-packages/monai/data/dataset.py", line 93, in __getitem__
    return self._transform(index)
  File "/home/sfan/anaconda3/envs/torch_monai/lib/python3.6/site-packages/monai/data/dataset.py", line 79, in _transform
    return apply_transform(self.transform, data_i) if self.transform is not None else data_i
  File "/home/sfan/anaconda3/envs/torch_monai/lib/python3.6/site-packages/monai/transforms/transform.py", line 71, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.compose.Compose object at 0x1534418a8400>

**Comment by Nic-Ma** [comment]
Hi @shawnfan19 ,

Thanks for your interest here.
May I know why you want `resample=True` when saving your images?
If enabling resample, it will revert the operations in your `Spacingd` transform.
And BTW, to achieve your requirement to avoid repeatedly run for every epoch, I think the better solution is to use the `PersistentDataset`: https://github.com/Project-MONAI/MONAI/blob/dev/monai/data/dataset.py#L97
Or `CacheDataset`: https://github.com/Project-MONAI/MONAI/blob/dev/monai/data/dataset.py#L476
Please have a try.

Thanks.

**Comment by shawnfan19** [comment]
Hello @Nic-Ma,

Thank you for the prompt response. I wanted to save images both with ```resample=True``` and ```resample=False``` for a before-and-after comparison and to ensure that the images are processed correctly. ```resample=True``` gives the memory error above, and ```resample=False``` gives an images that is distorted. 


```PersistentDatset``` sounds exactly what I was looking for, but I would still like to address the above issue to for the sake of visualization and comparison. 

Thank you for looking into this. 

Shawn

**Comment by Nic-Ma** [comment]
Hi @shawnfan19 ,

Could you please help provide a simple program to reproduce the issue? Then let me investigate it.
Maybe you can generate a random data array with the same size as your images.

Thanks.

**Comment by shawnfan19** [comment]
Hello @Nic-Ma,

For sure. Please find the code snippet below. The NiFTI file can be found here (https://drive.google.com/drive/folders/1r2_0RTHFN8XfSLnSgMGYZuQXuhEpP4NC?usp=sharing). 

```python 

dict_transforms = Compose(
    [
        LoadImaged(keys=["img"]),
        AsChannelFirstd(keys=["img"], channel_dim=-1),
        Spacingd(keys=["img"], pixdim=(2, 2, 2), mode="bilinear"),
        ScaleIntensityd(keys=["img"], minv=0.0, maxv=1.0),
        SaveImaged(keys=["img"], output_dir="./visualization", output_ext=".nii", resample=False)
        ToTensord(keys=["img"]),
    ]
)

data_lst = [
   {"img": "./ADNI_023_S_0376_PT_PET_Brain_AV45_recon_br_raw_20100527082453889_6_S85655_I174732.nii"}
]

check_ds = Dataset(data=data_lst, transform=dict_transforms)
check_loader = DataLoader(check_ds, batch_size=1)

for i, batch in enumerate(check_loader):

    imsave(f"visualization/axial_{i}.png", batch["img"][0, 0, :, :, 50])
    imsave(f"visualization/coronal_{i}.png", batch["img"][0, 0, :, 50, :])
    imsave(f"visualization/saggital_{i}.png", batch["img"][0, 0, 50, :, :])

```

Node that the distortion can only be seen in the saved NiFTI file. The .png files actually appear normal. I suspect that the pipeline transforms the images correctly, but something may have gone wrong when saving to NiFTI. 

Thank you.

**Comment by Nic-Ma** [comment]
Hi @shawnfan19 ,

Thanks for your bug report.
I think the root cause of the distortion may because when saving nifti file, we always save with the `original_affine` no matter `reample` is True or False.
I submitted a PR https://github.com/Project-MONAI/MONAI/pull/2322 to update it.

Thanks.

**Comment by shawnfan19** [comment]
Hello @Nic-Ma,

Thank you for the update! Sorry I have limited experiences with GitHub, but to access the PR, would I need to re-install MONAI by building it forms source?

Shawn

**Comment by Nic-Ma** [comment]
Hi @shawnfan19 ,

I think maybe you can try to:
1. pip uninstall monai
2. git clone https://github.com/Nic-Ma/MONAI.git --branch 2316-fix-resample-affine
3. cd MONAI
4. python setup.py develop

If the PR can't fix your issue, please let me know and debug more.

Thanks.

**Comment by wyli** [comment]
#2322 fixes a utility issue but not the original out of memory issue.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Yes, there are 2 issues reported in the ticket: 1. distortion when `resample=False`, 2. out of memory when `resample=True`.

Thanks.

**Comment by wyli** [comment]
Had another look, the error is because of the old format for the image header:
https://github.com/Project-MONAI/MONAI/blob/27e64e0c0469c2fce910545328a2db8914958388/monai/transforms/io/array.py#L161-L162

before the above correction, the spatial shape was 
```py
meta_data['spatial_shape']
>>> array([336, 336,  81], dtype=int16)
```
after `switch_endianness`:
```py
meta_data['spatial_shape']
array([20481, 20481, 20736], dtype=int16)
``` 
the spatial shape was changed to a large value and causes OOM

**Comment by Nic-Ma** [comment]
Cool, thanks for your debugging!
Let try to test and enhance `switch_endianness` later.

Thanks.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

After some investigation, I think the root cause is that we should call Nibabel API to swap the endian order:
https://github.com/nipy/nibabel/blob/master/nibabel/tests/test_image_load_save.py#L68
I will add more unit tests to cover it.

Thanks.

**Comment by wyli** [comment]
> Hi @wyli ,
> 
> After some investigation, I think the root cause is that we should call Nibabel API to swap the endian order:
> https://github.com/nipy/nibabel/blob/master/nibabel/tests/test_image_load_save.py#L68
> I will add more unit tests to cover it.
> 
> Thanks.

thanks, it's still good to have https://github.com/Project-MONAI/MONAI/pull/2325 for all the supported readers, the headers  should be checked/converted
