### ISSUE TITLE
PicklingError on CropForegroundd transform with lambda as select_fn

### ISSUE THREAD

**Issue by ambroslins** [Project-MONAI/MONAI#2443]
**Describe the bug**
Using the `CropForegroundd` transform with a lambda `select_fn` and `DataLoader` with `num_workers > 0` will fail with the following output:
```
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".\crop_issue.py", line 23, in <module>
    main()
  File ".\crop_issue.py", line 20, in main
  File "C:\Users\Ambros\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    print(next(iter(train_loader)))
      File "C:\Users\Ambros\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 355, in __iter__
exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Ambros\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 126, in _main
    return self._get_iterator()
self = reduction.pickle.load(from_parent)  File "C:\Users\Ambros\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 301, in _get_iterator

EOFError: Ran out of input
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\Ambros\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 914, in __init__
    w.start()
  File "C:\Users\Ambros\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Ambros\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Ambros\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\Ambros\AppData\Local\Programs\Python\Python38\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Ambros\AppData\Local\Programs\Python\Python38\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function CropForegroundd.<lambda> at 0x000001FDA37CF310>: attribute lookup CropForegroundd.<lambda> on monai.transforms.croppad.dictionary failed
```

**To Reproduce**
1. save script:
```python
from monai.transforms import CropForegroundd
from monai.data import create_test_image_2d, CacheDataset, DataLoader

def positive(n):
    return n > 0

def main():
    img, seg = create_test_image_2d(128, 128, num_seg_classes=1, channel_dim=0)
    data = [{"img": img, "seg": seg} for _ in range(2)]

    transform = CropForegroundd(
        keys="img",
        source_key="seg",
        # select_fn=lambda n: n > 0 # this would crash
        # select_fn=positive # this would not crash
    )
    train_ds = CacheDataset(data, transform, progress=False)
    train_loader = DataLoader(train_ds, num_workers=1) # num_workers = 0 does not crash

    print(next(iter(train_loader)))

if __name__ == "__main__":
    main()
```
2. Install `monai==0.5.3` 
3. run script

**Expected behavior**
`CropForegroundd` should work with lambda functions, as the default for the `select_fn` argument is a lambda function.

**Environment**

Ensuring you use the relevant python executable, please paste the output of:

```
> python -c 'import monai; monai.config.print_debug_info()'
================================
Printing MONAI config...
================================
MONAI version: 0.5.3
Numpy version: 1.20.2
Pytorch version: 1.8.1+cu111
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: d78c669c67e38ddfbe572f6a0438e9df0b8c65d7

Optional dependencies:
Pytorch Ignite version: NOT INSTALLED or UNKNOWN VERSION.
Nibabel version: 3.2.1
scikit-image version: NOT INSTALLED or UNKNOWN VERSION.
Pillow version: 8.2.0
Tensorboard version: 2.5.0
gdown version: NOT INSTALLED or UNKNOWN VERSION.
TorchVision version: 0.9.1+cu111
ITK version: NOT INSTALLED or UNKNOWN VERSION.
tqdm version: 4.60.0
lmdb version: NOT INSTALLED or UNKNOWN VERSION.
psutil version: NOT INSTALLED or UNKNOWN VERSION.

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies


================================
Printing system config...
================================
`psutil` required for `print_system_info`

================================
Printing GPU config...
================================
Num GPUs: 1
Has CUDA: True
CUDA version: 11.1
cuDNN enabled: True
cuDNN version: 8005
Current device: 0
Library compiled for CUDA architectures: ['sm_37', 'sm_50', 'sm_60', 'sm_61', 'sm_70', 'sm_75', 'sm_80', 'sm_86', 'compute_37']
GPU 0 Name: NVIDIA GeForce RTX 2070 SUPER
GPU 0 Is integrated: False
GPU 0 Is multi GPU board: False
GPU 0 Multi processor count: 40
GPU 0 Total memory (GB): 8.0
GPU 0 CUDA capability (maj.min): 7.5
```

**Comment by wyli** [comment]
Thanks for the detailed report. I think it's been addressed in https://github.com/Project-MONAI/MONAI/issues/2122, the fix will be available in the next milestone release.
