### ISSUE TITLE
cron test error -- test_ensure_typed

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#2556]
**Describe the bug**
issues using torch 1.5.1 https://github.com/Project-MONAI/MONAI/runs/3014995045?check_suite_focus=true#step:5:11770

```
======================================================================
ERROR: test_single_input (tests.test_ensure_typed.TestEnsureTyped)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/MONAI/MONAI/tests/test_ensure_typed.py", line 34, in test_single_input
test_script_3 (tests.test_densenet.TestDENSENET) (13.6s)
test_cpu_precise_backwards_7_3_dimension_1_channel_high_spatial_sigma_high_color_sigma (tests.test_bilateral_precise.BilateralFilterTestCaseCpuPrecise) (14.3s)
test_script_5 (tests.test_resnet.TestResNet) (14.9s)
test_script_2 (tests.test_densenet.TestDENSENET) (15.0s)
test_script_4 (tests.test_senet.TestSENET) (16.3s)
test_script_3 (tests.test_senet.TestSENET) (17.3s)
    torch.testing.assert_allclose(result, test_data)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/__init__.py", line 30, in assert_allclose
    close = torch.isclose(actual, expected, rtol, atol, equal_nan)
RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `logical_not()` operator instead.

----------------------------------------------------------------------
```

**Comment by wyli** [comment]
could you please look into this? @Nic-Ma

**Comment by Nic-Ma** [comment]
Sure, checking and will submit a quick PR to fix ASAP.

Thanks.
