### ISSUE TITLE
LoadImage can not read .mgz files

### ISSUE THREAD

**Issue by Spenhouet** [Project-MONAI/MONAI#2743]
**Is your feature request related to a problem? Please describe.**
If one wants to work with Freesurfer data it is necessary to read `.mgz` files.
Nibabel can do so. 

**Describe the solution you'd like**
One step is to add the `.mgz` extension to the suffixes defined for the `NibabelReader`.

```python
suffixes: Sequence[str] = ["nii", "nii.gz"] # <- add mgz here
```

I tested this by monkey patching `NibabelReader.verify_suffix`:

```python
from monai.data.utils import is_supported_format
from monai.data.image_reader import NibabelReader


def verify_suffix(self, filename: Union[Sequence[str], str]) -> bool:
    """
    Verify whether the specified file or files format is supported by Nibabel reader.

    Args:
        filename: file name or a list of file names to read.
            if a list of files, verify all the suffixes.

    """
    suffixes: Sequence[str] = ["nii", "nii.gz", "mgz"]
    return is_supported_format(filename, suffixes)


NibabelReader.verify_suffix = verify_suffix
```

But there seem to be more adjustments needed. With this change I get the following exception:

```console
~\AppData\Local\Programs\Python\Python37\lib\site-packages\monai\data\image_reader.py in read(self, data, **kwargs)
    363             img = nib.load(name, **kwargs_)
--> 364             img = correct_nifti_header_if_necessary(img)
    365             img_.append(img)

~\AppData\Local\Programs\Python\Python37\lib\site-packages\monai\data\utils.py in correct_nifti_header_if_necessary(img_nii)
    489     """
--> 490     dim = img_nii.header["dim"][0]
    491     if dim >= 5:

~\AppData\Local\Programs\Python\Python37\lib\site-packages\nibabel\freesurfer\mghformat.py in __getitem__(self, item)
    495             return self._header_data[item]
--> 496         return super(MGHHeader, self).__getitem__(item)
    497 

~\AppData\Local\Programs\Python\Python37\lib\site-packages\nibabel\wrapstruct.py in __getitem__(self, item)
    313         """
--> 314         return self._structarr[item]
    315 

ValueError: no field of name dim
```

**Describe alternatives you've considered**
One can convert the `.mgz` files to `.nii.gz` beforehand like this:

```python
img = nib.load(f"{filename}.mgz")
nib.save(img , f"{filename}.nii.gz")
```

**Comment by Nic-Ma** [comment]
Hi @Spenhouet ,

May I know the error if reading the `.mgz` directly with `LoadImage`? I think ITK should support it?

Thanks.

**Comment by Spenhouet** [comment]
Hi @Nic-Ma,

thanks for the hint. I did not know that ITK is the catch all for loading image files.
I did not have ITK installed and therefore got:

```console
RuntimeError: can not find suitable reader for this file: path\to\my\file\orig.mgz.                 Please install dependency libraries: (nii, nii.gz) -> Nibabel, (png, jpg, bmp) -> PIL,                 (npz, npy) -> Numpy, others -> ITK. Refer to the installation instruction:                 https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies.
```

Nonetheless, I installed ITK now and still can not load the image.

```console
~\AppData\Local\Programs\Python\Python37\lib\site-packages\monai\data\image_reader.py in read(self, data, **kwargs)
    195 
--> 196             img_.append(itk.imread(name, **kwargs_))
    197         return img_ if len(filenames) > 1 else img_[0]

~\AppData\Local\Programs\Python\Python37\lib\site-packages\itk\support\extras.py in imread(filename, pixel_type, fallback_only, imageio)
    956     else:
--> 957         reader = template_reader_type.New(**kwargs)
    958     reader.Update()

~\AppData\Local\Programs\Python\Python37\lib\site-packages\itk\support\template_class.py in New(self, *args, **kwargs)
    660             return self._NewImageReader(
--> 661                 itk.ImageFileReader, False, "FileName", *args, **kwargs
    662             )

~\AppData\Local\Programs\Python\Python37\lib\site-packages\itk\support\template_class.py in _NewImageReader(TemplateReaderType, increase_dimension, primaryInputMethod, *args, **kwargs)
    160             raise RuntimeError(
--> 161                 f"Could not create IO object for reading file {inputFileName}" + msg
    162             )

RuntimeError: Could not create IO object for reading file path\to\my\file\orig.mgz
```

**Comment by Nic-Ma** [comment]
Hi @Spenhouet ,

Could you please help share your test program for further analysis?
@thewtex Do you have any idea about this ITK error?

Thanks in advance.

**Comment by Spenhouet** [comment]
Sure, this is the minimal reproduction:

```python
from monai.transforms import LoadImage

LoadImage()(r'C:\Users\path\to\my\file\orig.mgz')
```

I can't share my input file.

But I would propose to simply enable the `NibabelReader` to handle `.mgz` files.

The following patch works:

```python
from typing import List, Sequence, Union

import nibabel as nib
from monai.data.image_reader import NibabelReader, has_nib
from monai.data.utils import (correct_nifti_header_if_necessary, is_supported_format)
from monai.transforms import LoadImage
from monai.utils import ensure_tuple
from nibabel.nifti1 import Nifti1Image


def verify_suffix(self, filename: Union[Sequence[str], str]) -> bool:
    """
    Verify whether the specified file or files format is supported by Nibabel reader.

    Args:
        filename: file name or a list of file names to read.
            if a list of files, verify all the suffixes.

    """
    suffixes: Sequence[str] = ["nii", "nii.gz", "mgz"]  # <- Added 'mgz' here
    return has_nib and is_supported_format(filename, suffixes)


def read(self, data: Union[Sequence[str], str], **kwargs):
    """
        Read image data from specified file or files.
        Note that the returned object is Nibabel image object or list of Nibabel image objects.

        Args:
            data: file name or a list of file names to read.
            kwargs: additional args for `nibabel.load` API, will override `self.kwargs` for existing keys.
                More details about available args:
                https://github.com/nipy/nibabel/blob/master/nibabel/loadsave.py

        """
    img_: List[Nifti1Image] = []

    filenames: Sequence[str] = ensure_tuple(data)
    kwargs_ = self.kwargs.copy()
    kwargs_.update(kwargs)
    for name in filenames:
        img = nib.load(name, **kwargs_)
        if not isinstance(img, Nifti1Image):   # <- added this line
            img = Nifti1Image.from_image(img)  # <- added this line
        img = correct_nifti_header_if_necessary(img)
        img_.append(img)
    return img_ if len(filenames) > 1 else img_[0]


NibabelReader.verify_suffix = verify_suffix
NibabelReader.read = read

LoadImage()(r'C:\Users\path\to\my\file\orig.mgz')
```

It is only a small change which allows Nibabel to convert the `MGHImage` object to a `Nifti1Image` object.

This is basically the fix:

```python
if not isinstance(img, Nifti1Image):
    img = Nifti1Image.from_image(img)
```

Why is Nifti1Image over Nifti2Image used?

**Comment by Nic-Ma** [comment]
Hi @Spenhouet ,

I tried to run the ITK reader, maybe it because the image file is unavailable?
Could you please help confirm with below command:
```
>>> import itk
>>> 
>>> itk.imread(r'path/to/orig.mgz')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/itk/support/extras.py", line 957, in imread
    reader = template_reader_type.New(**kwargs)
  File "/opt/conda/lib/python3.8/site-packages/itk/support/template_class.py", line 660, in New
    return self._NewImageReader(
  File "/opt/conda/lib/python3.8/site-packages/itk/support/template_class.py", line 160, in _NewImageReader
    raise RuntimeError(
RuntimeError: Could not create IO object for reading file path/to/orig.mgz
The file doesn't exist. 
Filename = path/to/orig.mgz
```

**Comment by wyli** [comment]
I feel if the user specifies a reader in `LoadImage`, there's no need to do the filename extension checks. I'll submit a PR to show the idea

**Comment by Spenhouet** [comment]
Hi @Nic-Ma,

```
import itk

itk.imread(r'C:\Users\path\to\my\file\orig.mgz')
```

This gives me the same error as with `LoadImage`:

```console
RuntimeError: Could not create IO object for reading file C:\Users\path\to\my\file\orig.mgz
```

With the fix for the NibabelReader above I can load the same file so it is definitely not that.

@wyli @Nic-Ma What you do think about the proposed adjustment to the NibabelReader?

**Comment by Nic-Ma** [comment]
I think @wyli wanted to submit a PR to unlock the extension check if explicitly providing reader, then you can just set `NibabelReader` for your case.
But I am still don't understand why ITK can't read it, CC @thewtex .

Thanks.

**Comment by Spenhouet** [comment]
I tested the fix with `LoadImaged(FILE_KEYS, "NibabelReader")` and can confirm that it solved my issue.

**Comment by Spenhouet** [comment]
Thanks @wyli for the implementation. :)
