### ISSUE TITLE
Mixing MONAI and TorchIO transforms in OneOf with batched data leads to RuntimeError

### ISSUE THREAD

**Issue by lyndonboone** [Project-MONAI/MONAI#2811]
**Describe the bug**
Mixing MONAI and TorchIO transforms in the same `OneOf` instance with batched data leads to `RuntimeError: each element in list of batch should be of equal size`, even though both transforms within `OneOf` seem to produce tensors of the same size. Using MONAI transforms only or TorchIO transforms only within a given `OneOf` instance works with batched data. Would like to be able to combine both within a given `OneOf` instance.

**To Reproduce**
The following example, adapted from the 3D spleen segmentation tutorial, should reproduce the error:

```python
import glob
import os
import tempfile

from monai.apps import download_and_extract
from monai.config import print_config
from monai.data import DataLoader, Dataset
import monai.transforms as tf
from monai.utils import first, set_determinism
import torchio as tio

print_config()

directory = os.environ.get("MONAI_DATA_DIRECTORY")
root_dir = tempfile.mkdtemp() if directory is None else directory
print(root_dir)

resource = "https://msd-for-monai.s3-us-west-2.amazonaws.com/Task09_Spleen.tar"
md5 = "410d4a301da4e5b2f6f86ec3ddba524e"

compressed_file = os.path.join(root_dir, "Task09_Spleen.tar")
data_dir = os.path.join(root_dir, "Task09_Spleen")
if not os.path.exists(data_dir):
    download_and_extract(resource, compressed_file, root_dir, md5)

train_images = sorted(
    glob.glob(os.path.join(data_dir, "imagesTr", "*.nii.gz")))
train_labels = sorted(
    glob.glob(os.path.join(data_dir, "labelsTr", "*.nii.gz")))
data_dicts = [
    {"image": image_name, "label": label_name}
    for image_name, label_name in zip(train_images, train_labels)
]
train_files, val_files = data_dicts[:-9], data_dicts[-9:]

set_determinism(seed=0)

oneof_transforms = [
    tf.RandAdjustContrastd(
        keys=['image'],
        prob=1.0
    ),
    tf.Compose([
        tf.ToTensord(keys=['image', 'label']),
        tio.transforms.RandomBlur(
            p=1.0,
            include=['image']
        ),
        tf.ToNumpyd(keys=['image', 'label'])
    ])
]

train_transforms = tf.Compose([
    tf.LoadImaged(keys=["image", "label"]),
    tf.EnsureChannelFirstd(keys=["image", "label"]),
    tf.Spacingd(keys=["image", "label"], pixdim=(
        1.5, 1.5, 2.0), mode=("bilinear", "nearest")),
    tf.Orientationd(keys=["image", "label"], axcodes="RAS"),
    tf.ScaleIntensityRanged(
        keys=["image"], a_min=-57, a_max=164,
        b_min=0.0, b_max=1.0, clip=True,
    ),
    tf.CropForegroundd(keys=["image", "label"], source_key="image"),
    tf.OneOf(transforms=oneof_transforms),
    tf.RandCropByPosNegLabeld(
        keys=["image", "label"],
        label_key="label",
        spatial_size=(96, 96, 96),
        pos=1,
        neg=1,
        num_samples=4,
        image_key="image",
        image_threshold=0,
    ),
    tf.EnsureTyped(keys=["image", "label"]),
])

ds = Dataset(data=train_files, transform=train_transforms)
loader = DataLoader(ds, batch_size=2, shuffle=True)

for batch_data in loader:
    continue
```

**Expected behavior**
I would expect the dataloader to be able to collate the samples within a batch if the two samples have the same size (e.g., `[4, 1, 96, 96, 96]` for the example above) even if they're transformed by transforms from different libraries (i.e., MONAI and TorchIO). With that said, I'm not too familiar with the low-level details of the dataloader and collate functions, so I could be missing an important detail.

**Screenshots**
![image](https://user-images.githubusercontent.com/22750822/130114917-7136d06b-ba36-43e1-8bec-7c3f036b1fa5.png)

**Environment**

```
================================
Printing MONAI config...
================================
MONAI version: 0.7.dev2133
Numpy version: 1.19.2
Pytorch version: 1.8.1+cu102
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: 20ffa3f987fad60a8428ec635fb0b4f6ccca9747

Optional dependencies:
Pytorch Ignite version: NOT INSTALLED or UNKNOWN VERSION.
Nibabel version: 3.2.1
scikit-image version: NOT INSTALLED or UNKNOWN VERSION.
Pillow version: 7.2.0
Tensorboard version: NOT INSTALLED or UNKNOWN VERSION.
gdown version: NOT INSTALLED or UNKNOWN VERSION.
TorchVision version: 0.9.1+cu102
tqdm version: 4.60.0
lmdb version: NOT INSTALLED or UNKNOWN VERSION.
psutil version: NOT INSTALLED or UNKNOWN VERSION.
pandas version: 1.2.4
einops version: NOT INSTALLED or UNKNOWN VERSION.

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies


================================
Printing system config...
================================
`psutil` required for `print_system_info`

================================
Printing GPU config...
================================
Num GPUs: 0
Has CUDA: False
cuDNN enabled: True
cuDNN version: 7605
```

**Additional context**
N/A

**Comment by Nic-Ma** [comment]
Hi @lyndonboone ,

I want to double confirm that if you remove the `OneOf` part, the program can run normally?
For integrating TorchIO, you can also refer to: https://github.com/Project-MONAI/tutorials/blob/master/modules/integrate_3rd_party_transforms.ipynb

Thanks.

**Comment by lyndonboone** [comment]
Hi @Nic-Ma ,

Yes, the program runs normally without the `OneOf` part (i.e. with the MONAI and TorchIO transforms in series). As I mentioned above, it also runs normally if `OneOf` includes strictly MONAI transforms or strictly TorchIO transforms. The problem seems to arise when two samples transformed by different libraries (i.e. one sample transformed by MONAI and the other transformed by TorchIO) are batched together, as can happen when using `OneOf` with a batch size > 1.

**Comment by Nic-Ma** [comment]
Hi @lyndonboone ,

I think your 2 transforms in the `OneOf` are intensity transforms which don't change the spatial shape. And the `RandCropByPosNegLabeld` transform will generate data with shape [96, 96, 96], seems it always applied.
I will try to reproduce your code later.

Thanks.

**Comment by lyndonboone** [comment]
Hi @Nic-Ma ,

Thanks for your help. That would be great!

I was surprised by the error message mentioning size since as you mentioned, both are intensity transforms that shouldn't alter the shape of the tensor and the patching operation at the end renders the samples to `[4, 1, 96, 96, 96]` in the end anyway. I'm having trouble understanding what this could have to do with tensor shape. Perhaps the error message isn't describing the true problem?

**Comment by rijobro** [comment]
@lyndonboone if you did something like:
```python
t = tio.transforms.RandomBlur(
    p=1.0,
    include=['image']
)
out = t(np.ones(1, 96, 97, 98)
print(out.shape)
```
What do you get?

**Comment by Nic-Ma** [comment]
Hi @rijobro ,

I just run your test program, the output is:
```
torch.Size([1, 96, 97, 98])
```

Thanks.

**Comment by Nic-Ma** [comment]
Hi @lyndonboone ,

I can reproduce your issue locally, but unfortunately, I didn't get the root cause immediately..
Could you please help use the `GaussianSmoothd` or other transforms of MONAI instead?
https://github.com/Project-MONAI/MONAI/blob/dev/monai/transforms/intensity/dictionary.py
CC @rijobro @wyli @fepegar Do you guys know some reason of this TorchIO issue?

Thanks in advance.

**Comment by fepegar** [comment]
> CC @rijobro @wyli @fepegar Do you guys know some reason of this TorchIO issue?

I'll try to reproduce and investigate. Could this be related to the fact that TorchIO doesn't support (yet?) batched inputs?

**Comment by rijobro** [comment]
I've done some messing around and think the problem is due to differences in the `image_transforms`. If `RandAdjustConstrastd` is used, an extra element will be in the list compared to the torchio transform. Adding `tf.DeleteItemsd(keys=["image_transforms", "label_transforms"]),` at the end of the transforms worked for me. 

But certainly something that we need to think about for avoiding this in the future. Thanks for raising this!

**Comment by fepegar** [comment]
In case it helps, I'm getting a different error when trying to reproduce:

```python-traceback
[7, 7, 7, 7, 7, 7, 7]
[3, 3, 3, 3, 3, 3, 3]
[3, 3, 3, 3, 3, 3, 3]
[3, 3, 3, 3, 3, 3, 3]
[3, 3, 3, 3, 3, 3, 3]
[3, 3, 3, 3, 3, 3, 3]
[3, 3, 3, 3, 3, 3, 3]
[3, 3, 3, 3, 3, 3, 3]
[3, 3, 3, 3, 3, 3, 3]
[7, 7, 7, 7, 7, 7, 7]
[3, 3, 3, 3, 3, 3, 3]
[3, 3, 3, 3, 3, 3, 3]
[3, 3, 3, 3, 3, 3, 3]
[3, 3, 3, 3, 3, 3, 3]
[3, 3, 3, 3, 3, 3, 3]
[3, 3, 3, 3, 3, 3, 3]
[3, 3, 3, 3, 3, 3, 3]
[3, 3, 3, 3, 3, 3, 3]
[7, 7, 7, 6, 6, 6, 6]
[3, 3, 3, 3, 3, 3, 3]
[3, 3, 3, 3, 3, 3, 3]
[3, 3, 3, 3, 3, 3, 3]
[3, 3, 3, 3, 3, 3, 3]
[3, 3, 3, 3, 3, 3, 3]
Traceback (most recent call last):
  File "mex.py", line 81, in <module>
    for batch_data in loader:
  File "/usr/local/Caskroom/miniconda/base/envs/monai/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/Caskroom/miniconda/base/envs/monai/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/Caskroom/miniconda/base/envs/monai/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/usr/local/Caskroom/miniconda/base/envs/monai/lib/python3.8/site-packages/monai/data/utils.py", line 275, in list_data_collate
    return default_collate(data)
  File "/usr/local/Caskroom/miniconda/base/envs/monai/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 74, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/usr/local/Caskroom/miniconda/base/envs/monai/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 74, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/usr/local/Caskroom/miniconda/base/envs/monai/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 86, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/Caskroom/miniconda/base/envs/monai/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 86, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/Caskroom/miniconda/base/envs/monai/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 74, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/usr/local/Caskroom/miniconda/base/envs/monai/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 74, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/usr/local/Caskroom/miniconda/base/envs/monai/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 74, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/usr/local/Caskroom/miniconda/base/envs/monai/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 74, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/usr/local/Caskroom/miniconda/base/envs/monai/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 74, in <listcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
KeyError: 'index'
```

Those printed lists come from a modification in `torch/utils/data/_utils/collate.py`, where I print `[len(elem) for elem in it]` in line 81.

**Comment by lyndonboone** [comment]
Thanks @rijobro , that seems to do the trick! Much appreciated.
