### ISSUE TITLE
error from `convert_to_tensor` 

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#3063]
**Describe the bug**
from the cron logs:
```
======================================================================
ERROR: test_dict_matches_4 (tests.test_k_space_spike_noised.TestKSpaceSpikeNoised)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/parameterized/parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/jenkins/agent/workspace/Monai-pytorch-versions/tests/test_k_space_spike_noised.py", line 97, in test_dict_matches
    out = t(deepcopy(data))
  File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/transforms/intensity/dictionary.py", line 1324, in __call__
    d[key] = self.transform(d[key])
  File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/transforms/intensity/array.py", line 1499, in __call__
    k = self.shift_fourier(img, n_dims)
  File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/utils/deprecated.py", line 204, in _wrapper
    return func(*args, **kwargs)
  File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/transforms/utils.py", line 1280, in shift_fourier
    k, *_ = convert_to_dst_type(k, x)
  File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/utils/type_conversion.py", line 284, in convert_to_dst_type
    return convert_data_type(data=src, output_type=output_type, device=device, dtype=dtype)
  File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/utils/type_conversion.py", line 251, in convert_data_type
    data = convert_to_tensor(data, dtype=dtype_, device=device)
  File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/utils/type_conversion.py", line 121, in convert_to_tensor
    return torch.as_tensor(data, dtype=dtype, device=device)  # type: ignore
TypeError: can't convert np.ndarray of type numpy.complex128. The only supported types are: float64, float32, float16, int64, int32, int16, int8, uint8, and bool.
```

**Comment by rijobro** [comment]
Must be for older versions of pytorch because this works for me locally:
```python
torch.as_tensor(np.array(1, dtype=np.complex128))
```

**Comment by Nic-Ma** [comment]
Hi @rijobro ,

PyTorch 1.5 can't support any operation for complex data type.
For example:
```
>>> import torch
>>> import numpy as np
>>> 
>>> print(torch.__version__)
1.5.1
>>> 
>>> torch.as_tensor(np.array(1, dtype=np.complex128), device="cuda")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't convert np.ndarray of type numpy.complex128. The only supported types are: float64, float32, float16, int64, int32, int16, int8, uint8, and bool.
```

So I submitted PR: #3064 to fix this issue.

Thanks.
