### ISSUE TITLE
integration test errors

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#3126]
**Describe the bug**
from cron tests pytorch 1.5 (last success was 12th/Oct):
```
======================================================================
ERROR: test_training (__main__.IntegrationWorkflows)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_integration_workflows.py", line 356, in test_training
    results = self.train_and_infer(idx=i)
  File "tests/test_integration_workflows.py", line 338, in train_and_infer
    _test_saved_files(postfix="seg_handler")
  File "tests/test_integration_workflows.py", line 336, in _test_saved_files
    self.assertTrue(test_integration_value(TASK, key="output_sums", data=values, rtol=1e-2))
  File "/home/jenkins/agent/workspace/Monai-pytorch-versions/tests/testing_data/integration_answers.py", line 443, in test_integration_value
    value = expected[test_name][key]
KeyError: 'output_sums'

----------------------------------------------------------------------
Ran 2 tests in 70.825s
```
from integration tests (last success was 13th/Oct)
https://github.com/Project-MONAI/MONAI/actions/runs/1340133963
```
======================================================================
ERROR: test_training (__main__.IntegrationSegmentation3D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_integration_segmentation_3d.py", line 288, in test_training
    results = self.train_and_infer(i)
  File "tests/test_integration_segmentation_3d.py", line 282, in train_and_infer
    self.assertTrue(test_integration_value(TASK, key="output_sums", data=results[8:], rtol=1e-2))
  File "/__w/MONAI/MONAI/tests/testing_data/integration_answers.py", line 443, in test_integration_value
    value = expected[test_name][key]
KeyError: 'output_sums'

----------------------------------------------------------------------
```

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for raising the issue, sorry for causing it.
Let me try to fix it ASAP.
