### ISSUE TITLE
error from unit tests

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#3165]
**Describe the bug**
see log: https://github.com/Project-MONAI/MONAI/pull/3160/checks?check_run_id=3962013500

```
======================================================================
ERROR: test_requires_meta_dict (tests.test_testtimeaugmentation.TestTestTimeAugmentation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/MONAI/MONAI/monai/transforms/transform.py", line 82, in apply_transform
    return _apply_transform(transform, data, unpack_items)
  File "/__w/MONAI/MONAI/monai/transforms/transform.py", line 53, in _apply_transform
    return transform(parameters)
  File "/__w/MONAI/MONAI/monai/transforms/spatial/dictionary.py", line 292, in inverse
    output_spatial_shape=orig_size,
  File "/__w/MONAI/MONAI/monai/transforms/spatial/array.py", line 224, in __call__
    spatial_size=output_shape if output_spatial_shape is None else output_spatial_shape,
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 577, in __call__
    result = self.forward(*input, **kwargs)
  File "/__w/MONAI/MONAI/monai/networks/layers/spatial_transforms.py", line 508, in forward
    raise ValueError(f"theta must be Nx3x3 or Nx4x4, got {theta.shape}.")
ValueError: theta must be Nx3x3 or Nx4x4, got torch.Size([1, 2, 2]).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/__w/MONAI/MONAI/monai/transforms/inverse_batch_transform.py", line 92, in __call__
    return first(inv_loader)
  File "/__w/MONAI/MONAI/monai/utils/misc.py", line 72, in first
    for i in iterable:
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 347, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 387, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/__w/MONAI/MONAI/monai/transforms/inverse_batch_transform.py", line 44, in __getitem__
    return self.invertible_transform.inverse(data)
  File "/__w/MONAI/MONAI/monai/transforms/compose.py", line 170, in inverse
    data = apply_transform(t.inverse, data, self.map_items, self.unpack_items)
  File "/__w/MONAI/MONAI/monai/transforms/transform.py", line 106, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <bound method Spacingd.inverse of <monai.transforms.spatial.dictionary.Spacingd object at 0x7efc4e06d860>>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/__w/MONAI/MONAI/tests/test_testtimeaugmentation.py", line 155, in test_requires_meta_dict
    tta(self.get_data(1, (20, 20), include_label=False))
  File "/__w/MONAI/MONAI/monai/data/test_time_augmentation.py", line 199, in __call__
    inv_batch = inverter(inferred_dict)
  File "/__w/MONAI/MONAI/monai/transforms/inverse_batch_transform.py", line 97, in __call__
    raise RuntimeError(re_str) from re
RuntimeError: applying transform <bound method Spacingd.inverse of <monai.transforms.spatial.dictionary.Spacingd object at 0x7efc4e06d860>>
```

```
MONAI version: refs/pull/3160/merge
Numpy version: 1.18.5
Pytorch version: 1.6.0a0+9907a3e
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: be253e2132acf2d6de7f1416fca7c82d1bcc376b

Optional dependencies:
Pytorch Ignite version: 0.4.6
Nibabel version: 3.2.1
scikit-image version: 0.15.0
Pillow version: 8.4.0
Tensorboard version: 1.15.0+nv
gdown version: 4.2.0
TorchVision version: 0.7.0a0
tqdm version: 4.62.3
lmdb version: 0.98
psutil version: 5.7.0
pandas version: 0.24.2
einops version: 0.3.2
transformers version: 4.11.3
mlflow version: 1.20.2
```
[logs.txt](https://github.com/Project-MONAI/MONAI/files/7388123/logs.txt)

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Is this bug related to my previous PR: https://github.com/Project-MONAI/MONAI/pull/3157?
If so, sorry about that, let me try to fix it ASAP.

Thanks.

**Comment by wyli** [comment]
this is difficult to reproduce because of this condition: https://github.com/Project-MONAI/MONAI/blob/7da613056fec29ee764857a417d4cca61f07986b/monai/transforms/spatial/array.py#L207-L209.
