### ISSUE TITLE
example/segmentation_3d size & label mismatch

### ISSUE THREAD

**Issue by zswgzx** [Project-MONAI/MONAI#323]
**Describe the bug**
Following example of segmentation_3d and changed with customized images. Unexpected size mismatch: 
  File "unet.py", line 52, in main
    check_data = monai.utils.misc.first(check_loader)
AssertionError: Caught AssertionError in DataLoader worker process 0.
AssertionError: expected size does not match label dim.

**To Reproduce**
1. copy 'examples/segmentation_3d/unet_training_dict.py'
2. edit 'datadir = '../data/'

    images = sorted(glob(os.path.join(datadir, 'train/images/*.nii.gz')))
    segs = sorted(glob(os.path.join(datadir, 'train/labels/*.nii.gz')))
    train_files = [{'img': img, 'seg': seg} for img, seg in zip(images, segs)]

    images = sorted(glob(os.path.join(datadir, 'val/images/*.nii.gz')))
    segs = sorted(glob(os.path.join(datadir, 'val/labels/*.nii.gz')))
    val_files = [{'img': img, 'seg': seg} for img, seg in zip(images, segs)]'
3. Run commands 'python unet.py.'

**Expected behavior**
Load images without error

**Environment (please complete the following information):**
 - OS ubuntu 18.04
 - Python version 3.7.6
 - MONAI version [e.g. git commit hash] 0.1.0
 - CUDA/cuDNN version
 - GPU models and configuration
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 00008A23:00:00.0 Off |                    0 |
| N/A   28C    P8    32W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

**Additional context**
36 subjects for training. 8 for validation

**Comment by Nic-Ma** [comment]
Hi @zswgzx ,

Thanks for the bug report.
Could you please help share the shape of your test **data** and **label**?
Especially whether it has the `channel` dimension.
Thanks.

**Comment by zswgzx** [comment]
Thanks for the update Nic. They're both 256x256x35, no channel dimension.

**Comment by Nic-Ma** [comment]
OK, could you please help share your program and error log?
Thanks.

**Comment by zswgzx** [comment]
MONAI version: 0.1.0
Python version: 3.7.6 | packaged by conda-forge | (default, Mar  5 2020, 15:27:18)  [GCC 7.3.0]
Numpy version: 1.18.3
Pytorch version: 1.5.0
Ignite version: 0.3.0
Traceback (most recent call last):
  File "unet.py", line 143, in <module>
    main()
  File "unet.py", line 52, in main
    check_data = monai.utils.misc.first(check_loader)
  File "/home/szhang/miniconda3-200306/envs/pytorch/lib/python3.7/site-packages/monai/utils/misc.py", line 36, in first
    for i in iterable:
  File "/home/szhang/miniconda3-200306/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/szhang/miniconda3-200306/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/szhang/miniconda3-200306/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/szhang/miniconda3-200306/envs/pytorch/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/szhang/miniconda3-200306/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/szhang/miniconda3-200306/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/szhang/miniconda3-200306/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/szhang/miniconda3-200306/envs/pytorch/lib/python3.7/site-packages/monai/data/dataset.py", line 48, in __getitem__
    data = self.transform(data)
  File "/home/szhang/miniconda3-200306/envs/pytorch/lib/python3.7/site-packages/monai/transforms/compose.py", line 195, in __call__
    input_ = apply_transform(_transform, input_)
  File "/home/szhang/miniconda3-200306/envs/pytorch/lib/python3.7/site-packages/monai/transforms/utils.py", line 240, in apply_transform
    return transform(data)
  File "/home/szhang/miniconda3-200306/envs/pytorch/lib/python3.7/site-packages/monai/transforms/composables.py", line 936, in __call__
    self.randomize(label, image)
  File "/home/szhang/miniconda3-200306/envs/pytorch/lib/python3.7/site-packages/monai/transforms/composables.py", line 930, in randomize
    image, self.image_threshold, self.R)
  File "/home/szhang/miniconda3-200306/envs/pytorch/lib/python3.7/site-packages/monai/transforms/utils.py", line 179, in generate_pos_neg_label_crop_centers
    assert len(max_size) == len(size), 'expected size does not match label dim.'
AssertionError: expected size does not match label dim.

**Comment by zswgzx** [comment]
code can be found here https://drive.google.com/open?id=1_aKPDzhqnvvY7gGSN9vfi9QgyB1K8_Uz

**Comment by Nic-Ma** [comment]
Thanks for providing the details, so it seems related to the `channel dim` as I said.
The UNet example uses data with channel dim but your dataset doesn't have channel dim.
So you need to replace the `AsChannelFirstd(keys=['img', 'seg'], channel_dim=-1)` with `AddChanneld(keys=['image', 'label'])`.
Please have a try and feel free to contact me if still facing some error.
Thanks.

**Comment by zswgzx** [comment]
Worked well Nic! How about the warning below and how would it affect the outcome? Also, what would you recommend to improve the segmentation given this specific data with only 35 slices? Thanks so much!

2020-05-04 16:24:12.422027: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2020-05-04 16:24:12.422156: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2020-05-04 16:24:12.422177: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.

**Comment by Nic-Ma** [comment]
Hi @zswgzx ,

You are welcome.
1. Seems your warning is from TensorFlow related environment, MONAI is a PyTorch based project, so I don't think it's caused by MONAI.
2. The warning message is that NVIDIA TensorRT is missing, if you want to use TensorRT to accelerate inference, please try to install [TensorRT](https://developer.nvidia.com/tensorrt).
3. You can try to save PyTorch model into ONNX format and use TensorRT to do inference, we don't have example in MONAI about that so far.

Thanks.

**Comment by zswgzx** [comment]
Hi again,

I'm using the same data and:

1. added RandZoomd and RandFlipd(axis=2) (for left/right flip) with default parameters
2. changed total epochs to 100

Error messages are as follows:

epoch 1/100
1/17, train_loss: 0.9609
2/17, train_loss: 0.9766
3/17, train_loss: 0.9316
4/17, train_loss: 0.9665
5/17, train_loss: 0.9585
6/17, train_loss: 0.9652
7/17, train_loss: 0.8651
8/17, train_loss: 0.8360
Traceback (most recent call last):
  File "unet.py", line 146, in <module>
    main()
  File "unet.py", line 94, in main
    for batch_data in train_loader:
  File "/home/szhang/miniconda3-200306/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/szhang/miniconda3-200306/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/szhang/miniconda3-200306/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/szhang/miniconda3-200306/envs/pytorch/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/szhang/miniconda3-200306/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/szhang/miniconda3-200306/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/szhang/miniconda3-200306/envs/pytorch/lib/python3.7/site-packages/monai/data/utils.py", line 195, in list_data_collate
    return default_collate(data)
  File "/home/szhang/miniconda3-200306/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 74, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/szhang/miniconda3-200306/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 74, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/szhang/miniconda3-200306/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [1, 32, 32, 32] at entry 0 and [1, 29, 29, 29] at entry 6

Code can be found here:
https://drive.google.com/open?id=1pF4BtGYJg3RoyHC249Ov0erFawIPJ-Ug

Any thought? Thanks!
