### ISSUE TITLE
nightly tests error: test_masked_inference_wsi_dataset

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#3263]
**Describe the bug**
```
======================================================================
ERROR: test_read_patches_cucim_2 (tests.test_masked_inference_wsi_dataset.TestMaskedInferenceWSIDataset)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/parameterized/parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/jenkins/agent/workspace/Monai-latest-image/tests/test_masked_inference_wsi_dataset.py", line 169, in test_read_patches_cucim
    dataset = MaskedInferenceWSIDataset(**input_parameters)
  File "/home/jenkins/agent/workspace/Monai-latest-image/monai/apps/pathology/data/datasets.py", line 197, in __init__
    self.data = self._prepare_data(data)
  File "/home/jenkins/agent/workspace/Monai-latest-image/monai/apps/pathology/data/datasets.py", line 207, in _prepare_data
    prepared_sample = self._prepare_a_sample(sample)
  File "/home/jenkins/agent/workspace/Monai-latest-image/monai/apps/pathology/data/datasets.py", line 230, in _prepare_a_sample
    image = self.image_reader.read(sample["image"])
  File "/home/jenkins/agent/workspace/Monai-latest-image/monai/data/image_reader.py", line 715, in read
    img = self.wsi_reader(name)
ValueError: Cannot find a plugin to handle '/home/jenkins/agent/workspace/Monai-latest-image/tests/testing_data/temp_uc?id=1sGTKZlJBIz53pfqTxoTqiIQzIoEzHLAe'!

======================================================================
ERROR: test_read_patches_cucim_3 (tests.test_masked_inference_wsi_dataset.TestMaskedInferenceWSIDataset)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/parameterized/parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/jenkins/agent/workspace/Monai-latest-image/tests/test_masked_inference_wsi_dataset.py", line 169, in test_read_patches_cucim
    dataset = MaskedInferenceWSIDataset(**input_parameters)
  File "/home/jenkins/agent/workspace/Monai-latest-image/monai/apps/pathology/data/datasets.py", line 197, in __init__
    self.data = self._prepare_data(data)
  File "/home/jenkins/agent/workspace/Monai-latest-image/monai/apps/pathology/data/datasets.py", line 207, in _prepare_data
    prepared_sample = self._prepare_a_sample(sample)
  File "/home/jenkins/agent/workspace/Monai-latest-image/monai/apps/pathology/data/datasets.py", line 230, in _prepare_a_sample
    image = self.image_reader.read(sample["image"])
  File "/home/jenkins/agent/workspace/Monai-latest-image/monai/data/image_reader.py", line 715, in read
    img = self.wsi_reader(name)
ValueError: Cannot find a plugin to handle '/home/jenkins/agent/workspace/Monai-latest-image/tests/testing_data/temp_uc?id=1sGTKZlJBIz53pfqTxoTqiIQzIoEzHLAe'!

======================================================================
ERROR: test_read_patches_cucim_4 (tests.test_masked_inference_wsi_dataset.TestMaskedInferenceWSIDataset)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/parameterized/parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/jenkins/agent/workspace/Monai-latest-image/tests/test_masked_inference_wsi_dataset.py", line 169, in test_read_patches_cucim
    dataset = MaskedInferenceWSIDataset(**input_parameters)
  File "/home/jenkins/agent/workspace/Monai-latest-image/monai/apps/pathology/data/datasets.py", line 197, in __init__
    self.data = self._prepare_data(data)
  File "/home/jenkins/agent/workspace/Monai-latest-image/monai/apps/pathology/data/datasets.py", line 207, in _prepare_data
    prepared_sample = self._prepare_a_sample(sample)
  File "/home/jenkins/agent/workspace/Monai-latest-image/monai/apps/pathology/data/datasets.py", line 230, in _prepare_a_sample
    image = self.image_reader.read(sample["image"])
  File "/home/jenkins/agent/workspace/Monai-latest-image/monai/data/image_reader.py", line 715, in read
    img = self.wsi_reader(name)
ValueError: Cannot find a plugin to handle '/home/jenkins/agent/workspace/Monai-latest-image/tests/testing_data/temp_uc?id=1sGTKZlJBIz53pfqTxoTqiIQzIoEzHLAe'!

```

**Comment by Nic-Ma** [comment]
Hi @wyli,

Thanks for raising this issue.
I tested locally, I can reproduce the issue with latest cuCIM 21.10.01 which just released today, can't reproduce with previous cuCIM.

Thanks.

**Comment by wyli** [comment]
thanks, there are similar issues in `tests.test_smartcache_patch_wsi_dataset` `tests.test_cuimage_reader` `test_smartcache_patch_wsi_dataset` `test_patch_wsi_dataset`
