### ISSUE TITLE
OverflowError: serializing a string larger than 4 GiB requires pickle protocol 4 or higher

### ISSUE THREAD

**Issue by yingdiLee** [Project-MONAI/MONAI#3402]
Thanks for your good work! MONAI helps me a lot.
When I use PersistentDataset, an error occurs. It seems like error comes from pickle:

Traceback (most recent call last):
  File "/data/zyd/beifen_xinsuoqu_/MedSeg/MedSeg/train/Task900TrainerDP.py", line 296, in <module>
    trainer.train(max_epochs=max_epochs, device=device)
  File "/data/zyd/beifen_xinsuoqu_/MedSeg/MedSeg/train/Task900TrainerDP.py", line 88, in train
    for batch_data in self.train_loader:
  File "/home/zyd/anaconda3/envs/med/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/zyd/anaconda3/envs/med/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/zyd/anaconda3/envs/med/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zyd/anaconda3/envs/med/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zyd/MONAI/monai/data/dataset.py", line 96, in __getitem__
    return self._transform(index)
  File "/home/zyd/MONAI/monai/data/dataset.py", line 288, in _transform
    pre_random_item = self._cachecheck(self.data[index])
  File "/home/zyd/MONAI/monai/data/dataset.py", line 277, in _cachecheck
    torch.save(_item_transformed, temp_hash_file)
  File "/home/zyd/anaconda3/envs/med/lib/python3.9/site-packages/torch/serialization.py", line 379, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/home/zyd/anaconda3/envs/med/lib/python3.9/site-packages/torch/serialization.py", line 484, in _save
    pickler.dump(obj)
OverflowError: serializing a string larger than 4 GiB requires pickle protocol 4 or higher

**Comment by Nic-Ma** [comment]
Hi @yingdiLee ,

Thanks for your interest and feedback.
Could you please help share your test program and image data for further analysis?Hi @yingdiLee ,

Thanks for your interest and feedback.
Could you please help share your test program and image data for further analysis?
Seems like maybe it can work well if a image is bigger than 4GB? Or something related to your file system type.
I will investigate it.

Thanks.

Seems like maybe it can work well if a image is bigger than 4GB? Or something related to your file system type.
I will investigate it.

Thanks.

**Comment by Nic-Ma** [comment]
Hi @yingdiLee ,

With a big cache content, I can reproduce this issue locally now, it's not related to file system type.
Let me try to figure out a solution or make it clear in the document ASAP.
Thanks very much for your finding!

**Comment by Nic-Ma** [comment]
BTW, have you edited the issue description? I think the previous log is something related to:
```
serializing a string larger than 4 GiB requires pickle protocol 4 or higher
```

Thanks.
