### ISSUE TITLE
test_wsireader full tests errors

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#3434]
**Describe the bug**
```
======================================================================
ERROR: test_read_rgba_0 (tests.test_wsireader.TestTiffFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/parameterized/parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/tests/test_wsireader.py", line 158, in test_read_rgba
    image[mode], _ = reader.get_data(img_obj)
  File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/data/image_reader.py", line 775, in get_data
    region = self._extract_region(img, location=location, size=size, level=level, dtype=dtype)
  File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/data/image_reader.py", line 850, in _extract_region
    region = region[location[0] : location[0] + size[0], location[1] : location[1] + size[1]]
TypeError: slice indices must be integers or None or have an __index__ method

======================================================================
ERROR: test_read_rgba_1 (tests.test_wsireader.TestTiffFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/parameterized/parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/tests/test_wsireader.py", line 158, in test_read_rgba
    image[mode], _ = reader.get_data(img_obj)
  File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/data/image_reader.py", line 775, in get_data
    region = self._extract_region(img, location=location, size=size, level=level, dtype=dtype)
  File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/data/image_reader.py", line 850, in _extract_region
    region = region[location[0] : location[0] + size[0], location[1] : location[1] + size[1]]
TypeError: slice indices must be integers or None or have an __index__ method

======================================================================
ERROR: test_read_whole_image_0__home_jenkins_agent_workspace_MONAI_postmerge_monai_github_tests_testing_data_temp_1sGTKZlJBIz53pfqTxoTqiIQzIoEzHLAe_tiff (tests.test_wsireader.TestTiffFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/parameterized/parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/tests/test_wsireader.py", line 117, in test_read_whole_image
    img = reader.get_data(img_obj)[0]
  File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/data/image_reader.py", line 775, in get_data
    region = self._extract_region(img, location=location, size=size, level=level, dtype=dtype)
  File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/data/image_reader.py", line 850, in _extract_region
    region = region[location[0] : location[0] + size[0], location[1] : location[1] + size[1]]
TypeError: slice indices must be integers or None or have an __index__ method

======================================================================
ERROR: test_with_dataloader_0__home_jenkins_agent_workspace_MONAI_postmerge_monai_github_tests_testing_data_temp_1sGTKZlJBIz53pfqTxoTqiIQzIoEzHLAe_tiff (tests.test_wsireader.TestTiffFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/transforms/transform.py", line 82, in apply_transform
    return _apply_transform(transform, data, unpack_items)
  File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/transforms/transform.py", line 53, in _apply_transform
    return transform(parameters)
  File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/transforms/io/dictionary.py", line 121, in __call__
    data = self._loader(d[key], reader)
  File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/transforms/io/array.py", line 214, in __call__
    img_array, meta_data = reader.get_data(img)
  File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/data/image_reader.py", line 775, in get_data
    region = self._extract_region(img, location=location, size=size, level=level, dtype=dtype)
  File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/data/image_reader.py", line 850, in _extract_region
    region = region[location[0] : location[0] + size[0], location[1] : location[1] + size[1]]
TypeError: slice indices must be integers or None or have an __index__ method

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/transforms/transform.py", line 82, in apply_transform
    return _apply_transform(transform, data, unpack_items)
  File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/transforms/transform.py", line 53, in _apply_transform
    return transform(parameters)
  File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/transforms/compose.py", line 160, in __call__
    input_ = apply_transform(_transform, input_, self.map_items, self.unpack_items)
  File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/transforms/transform.py", line 106, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.io.dictionary.LoadImaged object at 0x7f2571aca940>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/parameterized/parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/tests/test_wsireader.py", line 173, in test_with_dataloader
    data: dict = first(data_loader)
  File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/utils/misc.py", line 73, in first
    for i in iterable:
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/data/dataset.py", line 97, in __getitem__
    return self._transform(index)
  File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/data/dataset.py", line 83, in _transform
    return apply_transform(self.transform, data_i) if self.transform is not None else data_i
  File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/transforms/transform.py", line 106, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.compose.Compose object at 0x7f23c856a7f0>

----------------------------------------------------------------------
```

env:
```
MONAI version: 0+untagged.251.g5391f7c
Numpy version: 1.18.1
Pytorch version: 1.10.0+cu102
MONAI flags: HAS_EXT = True, USE_COMPILED = True
MONAI rev id: 5391f7cded378f30b0ce0758b19adcf9daf988c8

Optional dependencies:
Pytorch Ignite version: 0.4.6
Nibabel version: 3.2.1
scikit-image version: 0.15.0
Pillow version: 8.4.0
Tensorboard version: 2.1.0
gdown version: 4.2.0
TorchVision version: 0.11.1+cu102
tqdm version: 4.62.3
lmdb version: 0.98
psutil version: 5.6.7
pandas version: 0.24.2
einops version: 0.3.2
transformers version: 4.12.5
mlflow version: 1.22.0
```

**Comment by wyli** [comment]
caused by https://github.com/Project-MONAI/MONAI/pull/3417, could you please look into this? @drbeh

**Comment by drbeh** [comment]
@wyli, I'll take a look at this but do you know how should I reproduce it?

Also do you know why we have not been able to see this in all the checks that we have done before merging?!

**Comment by wyli** [comment]
> Also do you know why we have not been able to see this in all the checks that we have done before merging?!

yes, we only run basic tests before merging so that we handle PRs quickly.. after merging the PRs we have more tests against various environments...

**Comment by wyli** [comment]
the test script is roughly with these commands:
```bash
python -m pip uninstall -y torch torchvision
python -m pip install torch==1.10.0 torchvision==0.11.1
python -m pip install -r requirements-dev.txt
BUILD_MONAI=1 ./runtests.sh --unittests
```
on a v100 GPU, within a docker `nvcr.io/nvidia/pytorch:20.03-py3`

please let me know if these couldn't replicate it
