### ISSUE TITLE
setup errors

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#3750]
**Describe the bug**
recent errors such as [logs here](https://github.com/Project-MONAI/MONAI/runs/5004665493?check_suite_focus=true)
```
BUILD_MONAI_CPP=True, BUILD_MONAI_CUDA=False, TORCH_VERSION=11002.
running develop
Traceback (most recent call last):
  File "setup.py", line 142, in <module>
    setup(
  File "/home/runner/.local/lib/python3.8/site-packages/setuptools/__init__.py", line 155, in setup
    return distutils.core.setup(**attrs)
  File "/home/runner/.local/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/home/runner/.local/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/home/runner/.local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/home/runner/.local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 985, in run_command
    cmd_obj.ensure_finalized()
  File "/home/runner/.local/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/home/runner/.local/lib/python3.8/site-packages/setuptools/command/develop.py", line 52, in finalize_options
    easy_install.finalize_options(self)
  File "/home/runner/.local/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 276, in finalize_options
    self._fix_install_dir_for_user_site()
  File "/home/runner/.local/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 382, in _fix_install_dir_for_user_site
    self.create_home_path()
  File "/home/runner/.local/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1338, in create_home_path
    if path.startswith(home) and not os.path.isdir(path):
AttributeError: 'int' object has no attribute 'startswith'
```

see also https://github.com/pypa/setuptools/issues/3063

**Comment by wyli** [comment]
excluding 60.6 addressed this issue https://github.com/Project-MONAI/MONAI/blob/afcf59376cebb87657bd4023f51c960b7810dba6/requirements-min.txt#L3.
