### ISSUE TITLE
tests.test_config_item

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#3829]
**Describe the bug**
```
======================================================================
ERROR: test_component_6 (tests.test_config_item.TestConfigItem)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/parameterized/parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/jenkins/agent/workspace/Monai-pytorch-versions/tests/test_config_item.py", line 69, in test_component
    ret = configer.instantiate()
  File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/apps/manifest/config_item.py", line 277, in instantiate
    return instantiate(modname, **args)
  File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/utils/module.py", line 216, in instantiate
    return component(**kwargs)
  File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/transforms/utility/dictionary.py", line 1376, in __init__
    self.trans = TorchVision(name, *args, **kwargs)
  File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/transforms/utility/array.py", line 1019, in __init__
    self.trans = transform(*args, **kwargs)
  File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/utils/module.py", line 383, in __call__
    raise self._exception
monai.utils.module.OptionalImportError: from torchvision.transforms import ColorJitter (requires 'torchvision.transforms 0.8.0' by 'min_version').

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

======================================================================
ERROR: test_resolve_2 (tests.test_reference_resolver.TestReferenceResolver)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/parameterized/parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/jenkins/agent/workspace/Monai-pytorch-versions/tests/test_reference_resolver.py", line 94, in test_resolve
    result = resolver.get_resolved_content(expected_id)  # the root id is `expected_id` here
  File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/apps/manifest/reference_resolver.py", line 137, in get_resolved_content
    self._resolve_one_item(id=id)
  File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/apps/manifest/reference_resolver.py", line 122, in _resolve_one_item
    self.resolved_content[id] = item.instantiate()
  File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/apps/manifest/config_item.py", line 277, in instantiate
    return instantiate(modname, **args)
  File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/utils/module.py", line 216, in instantiate
    return component(**kwargs)
  File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/transforms/utility/dictionary.py", line 1376, in __init__
    self.trans = TorchVision(name, *args, **kwargs)
  File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/transforms/utility/array.py", line 1019, in __init__
    self.trans = transform(*args, **kwargs)
  File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/utils/module.py", line 383, in __call__
    raise self._exception
monai.utils.module.OptionalImportError: from torchvision.transforms import ColorJitter (requires 'torchvision.transforms 0.8.0' by 'min_version').

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

----------------------------------------------------------------------
```

for torch==1.6.0 and torchvision==0.7.0

could you please help fix it in #3822?

**Comment by Nic-Ma** [comment]
OK, sure, let me take a look.

Thanks.

**Comment by Nic-Ma** [comment]
Fixed in https://github.com/Project-MONAI/MONAI/pull/3822.

Thanks.
