### ISSUE TITLE
PadListDataCollate crashes when using list of dict input

### ISSUE THREAD

**Issue by ashgillman** [Project-MONAI/MONAI#3936]
**Describe the bug**
PadListDataCollate crashes when using list of dict input.

```
RuntimeError: Caught RuntimeError in DataLoader worker process 0.                                                                                        
Original Traceback (most recent call last):                                                                                                                File "/datasets/work/hb-atlas/source/apps/miniconda3/envs/tb_detection/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop                                                                                                                                                
    data = fetcher.fetch(index)                                             
  File "/datasets/work/hb-atlas/source/apps/miniconda3/envs/tb_detection/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch    return self.collate_fn(data)                                                                                                                           File "/datasets/work/hb-atlas/source/apps/miniconda3/envs/tb_detection/lib/python3.9/site-packages/monai/transforms/croppad/batch.py", line 82, in __ca
ll__                                                                                                                                                     
    for key_or_idx in batch[0].keys() if is_list_of_dicts else range(len(batch[0])):                                                                     RuntimeError: dictionary changed size during iteration 
```

https://github.com/Project-MONAI/MONAI/blob/dev/monai/transforms/croppad/batch.py#L83

**To Reproduce**
Use a `DataLoader` with `collate_fn=PadListDataCollate()` and where `data` returns a dict.

**Expected behavior**
Documentation indicates the class should handle Dict inputs.

**Environment**

```
================================
Printing MONAI config...
================================
MONAI version: 0.8.1
Numpy version: 1.22.3
Pytorch version: 1.11.0
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: 71ff399a3ea07aef667b23653620a290364095b1

Optional dependencies:
Pytorch Ignite version: NOT INSTALLED or UNKNOWN VERSION.
Nibabel version: 3.2.2
scikit-image version: NOT INSTALLED or UNKNOWN VERSION.
Pillow version: 9.0.1
Tensorboard version: 2.8.0
gdown version: NOT INSTALLED or UNKNOWN VERSION.
TorchVision version: 0.12.0
tqdm version: 4.62.3
lmdb version: NOT INSTALLED or UNKNOWN VERSION.
psutil version: NOT INSTALLED or UNKNOWN VERSION.
pandas version: 1.4.1
einops version: NOT INSTALLED or UNKNOWN VERSION.
transformers version: NOT INSTALLED or UNKNOWN VERSION.
mlflow version: NOT INSTALLED or UNKNOWN VERSION.

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies


================================
Printing system config...
================================
`psutil` required for `print_system_info`

================================
Printing GPU config...
================================
Num GPUs: 4
Has CUDA: True
CUDA version: 10.2
cuDNN enabled: True
cuDNN version: 7605
Current device: 0
Library compiled for CUDA architectures: ['sm_37', 'sm_50', 'sm_60', 'sm_61', 'sm_70', 'sm_75', 'compute_37']
GPU 0 Name: Tesla P100-SXM2-16GB
GPU 0 Is integrated: False
GPU 0 Is multi GPU board: False
GPU 0 Multi processor count: 56
GPU 0 Total memory (GB): 15.9
GPU 0 CUDA capability (maj.min): 6.0
GPU 1 Name: Tesla P100-SXM2-16GB
GPU 1 Is integrated: False
GPU 1 Is multi GPU board: False
GPU 1 Multi processor count: 56
GPU 1 Total memory (GB): 15.9
GPU 1 CUDA capability (maj.min): 6.0
GPU 2 Name: Tesla P100-SXM2-16GB
GPU 2 Is integrated: False
GPU 2 Is multi GPU board: False
GPU 2 Multi processor count: 56
GPU 2 Total memory (GB): 15.9
GPU 2 CUDA capability (maj.min): 6.0
GPU 3 Name: Tesla P100-SXM2-16GB
GPU 3 Is integrated: False
GPU 3 Is multi GPU board: False
GPU 3 Multi processor count: 56
GPU 3 Total memory (GB): 15.9
GPU 3 CUDA capability (maj.min): 6.0

```

**Additional context**
I was able to fix by replacing 
https://github.com/Project-MONAI/MONAI/blob/dev/monai/transforms/croppad/batch.py#L83
with:
```python
        key_or_idxs = list(batch[0].keys()) if is_list_of_dicts else range(len(batch[0]))
        for key_or_idx in key_or_idxs:
            ...
```

**Comment by Nic-Ma** [comment]
Hi @ashgillman ,

Thanks for your finding, yes, welcome to submit a fix PR with unit tests to cover the case.

Thanks in advance.

**Comment by ashgillman** [comment]
I'll be on leave for 3 weeks but happy to do so upon my return.

**Comment by wyli** [comment]
thanks, this issue happens to have been fixed when we develop other features, now the dev version is correct https://github.com/Project-MONAI/MONAI/blob/40717509198909b444d9566052602b7db0cfd0cb/monai/transforms/croppad/batch.py#L79-L80
