### ISSUE TITLE
Transform issue during training

### ISSUE THREAD

**Issue by pritamrungta** [Project-MONAI/MONAI#3950]
Training a deepgrow_3d model

image -> dataset/train1.nii.gz
label -> dataset/labels/final/train1.nii.gz
request -> {"num_epochs": 50, "datalist": [{"image": "train1.nii.gz", "label": "train1.nii.gz"}]}

get this error
```
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/monai/transforms/transform.py", line 89, in apply_transform
    return _apply_transform(transform, data, unpack_items)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/monai/transforms/transform.py", line 53, in _apply_transform
    return transform(parameters)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/monai/transforms/spatial/dictionary.py", line 377, in __call__
    d[key], old_affine, new_affine = self.ornt_transform(d[key], affine=meta_data["affine"])
  File "/home/ubuntu/.local/lib/python3.8/site-packages/monai/transforms/spatial/array.py", line 326, in __call__
    spatial_ornt = nib.orientations.ornt_transform(src, dst)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nibabel/orientations.py", line 128, in ornt_transform
    raise ValueError("Unable to find out axis %d in start_ornt" %
ValueError: Unable to find out axis 0 in start_ornt
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/monailabel/interfaces/utils/app.py", line 132, in <module>
    run_main()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/monailabel/interfaces/utils/app.py", line 117, in run_main
    result = a.train(request)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/monailabel/interfaces/app.py", line 366, in train
    result = task(request, self.datastore())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/monailabel/tasks/train/basic_train.py", line 350, in __call__
    datalist = self.pre_process(req, datastore)
  File "/home/ubuntu/deepgrow/lib/train.py", line 88, in pre_process
    datalist = create_dataset(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/monai/apps/deepgrow/dataset.py", line 101, in create_dataset
    data = transforms({image_key: image, label_key: label})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/monai/transforms/compose.py", line 173, in __call__
    input_ = apply_transform(_transform, input_, self.map_items, self.unpack_items, self.log_stats)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/monai/transforms/transform.py", line 113, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.spatial.dictionary.Orientationd object at 0x7f1c9bdcc520>
[2022-03-16 08:56:01,683] [2426] [ThreadPoolExecutor-0_0] [INFO] (monailabel.utils.async_tasks.utils:76) - Return code: 1
```

**Comment by wyli** [comment]
this is probably a usage question, could you please share some data samples and the transforms you are using? (converting to a discussion)
