### ISSUE TITLE
pip packaging error 

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#4054]
**Describe the bug**
```
09:41:44  + python -m twine check dist/monai-0.8.1+68.gde973911-py3-none-any.whl dist/monai-0.8.1+68.gde973911.tar.gz
09:41:44  /opt/conda/lib/python3.8/site-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (3.0.4) doesn't match a supported version!
09:41:44    warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
09:41:44  Traceback (most recent call last):
09:41:44    File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
09:41:44      return _run_code(code, main_globals, None,
09:41:44    File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
09:41:44      exec(code, run_globals)
09:41:44    File "/opt/conda/lib/python3.8/site-packages/twine/__main__.py", line 22, in <module>
09:41:44      from twine import cli
09:41:44    File "/opt/conda/lib/python3.8/site-packages/twine/cli.py", line 20, in <module>
09:41:44      import rich.highlighter
09:41:44    File "/opt/conda/lib/python3.8/site-packages/rich/highlighter.py", line 5, in <module>
09:41:44      from .text import Span, Text
09:41:44    File "/opt/conda/lib/python3.8/site-packages/rich/text.py", line 5, in <module>
09:41:44      from rich.emoji import EmojiVariant
09:41:44    File "/opt/conda/lib/python3.8/site-packages/rich/emoji.py", line 4, in <module>
09:41:44      from .jupyter import JupyterMixin
09:41:44    File "/opt/conda/lib/python3.8/site-packages/rich/jupyter.py", line 4, in <module>
09:41:44      from .segment import Segment
09:41:44    File "/opt/conda/lib/python3.8/site-packages/rich/segment.py", line 19, in <module>
09:41:44      from .cells import (
09:41:44    File "/opt/conda/lib/python3.8/site-packages/rich/cells.py", line 6, in <module>
09:41:44      from ._lru_cache import LRUCache
09:41:44    File "/opt/conda/lib/python3.8/site-packages/rich/_lru_cache.py", line 8, in <module>
09:41:44      from typing_extensions import OrderedDict
09:41:44  ImportError: cannot import name 'OrderedDict' from 'typing_extensions' (/opt/conda/lib/python3.8/site-packages/typing_extensions.py)

```
https://github.com/Textualize/rich/issues/2150

the ticket is for progress tracking, I've updated the blossom config and there's no need to update the core codebase at the moment.

**Comment by wyli** [comment]
the workaround was `python -m pip install --upgrade pip wheel twine!=4.0.0`
