### ISSUE TITLE
tests.test_bundle_download issue

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#4166]
**Describe the bug**
```
01:01:36  ======================================================================
01:01:36  ERROR: test_load_ts_module_0 (tests.test_bundle_download.TestLoad)
01:01:36  ----------------------------------------------------------------------
01:01:36  Traceback (most recent call last):
01:01:36    File "/opt/conda/lib/python3.8/site-packages/parameterized/parameterized.py", line 533, in standalone_func
01:01:36      return func(*(a + p.args), **p.kwargs)
01:01:36    File "/home/jenkins/agent/workspace/Monai-latest-image/tests/test_bundle_download.py", line 149, in test_load_ts_module
01:01:36      model_ts, metadata, extra_file_dict = load(
01:01:36    File "/home/jenkins/agent/workspace/Monai-latest-image/monai/bundle/scripts.py", line 285, in load
01:01:36      return load_net_with_metadata(full_path, map_location=torch.device(device), more_extra_files=config_files)
01:01:36    File "/home/jenkins/agent/workspace/Monai-latest-image/monai/data/torchscript_utils.py", line 119, in load_net_with_metadata
01:01:36      jit_obj = torch.jit.load(filename_prefix_or_stream, map_location, extra_files)
01:01:36    File "/opt/conda/lib/python3.8/site-packages/torch/jit/_serialization.py", line 161, in load
01:01:36      cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
01:01:36  RuntimeError: 
01:01:36  
01:01:36  prim::RaiseException(str msg) -> ():
01:01:36  Expected at most 1 arguments but found 2 positional arguments.
01:01:36  :
01:01:36    File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 2388
01:01:36          size_prods *= size[i + 2]
01:01:36      if size_prods == 1:
01:01:36          raise ValueError("Expected more than 1 value per channel when training, got input size {}".format(size))
01:01:36          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
01:01:36  Serialized   File "code/__torch__/torch/nn/functional.py", line 42
01:01:36      size_prods0 = size_prods1
01:01:36    if torch.eq(size_prods0, 1):
01:01:36      ops.prim.RaiseException(torch.format(_6, size), "builtins.ValueError")
01:01:36      ~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
01:01:36    else:
01:01:36      pass
01:01:36  '_verify_batch_size' is being compiled since it was called from 'batch_norm'
01:01:36  Serialized   File "code/__torch__/torch/nn/functional.py", line 9
01:01:36      momentum: float=0.10000000000000001,
01:01:36      eps: float=1.0000000000000001e-05) -> Tensor:
01:01:36    _0 = __torch__.torch.nn.functional._verify_batch_size
01:01:36    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
01:01:36    if training:
01:01:36      _1 = _0(torch.size(input), )
01:01:36  'batch_norm' is being compiled since it was called from 'BatchNorm3d.forward'
01:01:36  Serialized   File "code/__torch__/torch/nn/modules/batchnorm.py", line 18
01:01:36    def forward(self: __torch__.torch.nn.modules.batchnorm.BatchNorm3d,
01:01:36      input: Tensor) -> Tensor:
01:01:36      _0 = __torch__.torch.nn.functional.batch_norm
01:01:36      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
01:01:36      _1 = (self)._check_input_dim(input, )
01:01:36      training = self.training
01:01:36  
01:01:36  
01:01:36  ----------------------------------------------------------------------
01:01:36  Ran 8511 tests in 1547.515s
```

with docker 21.10
```
00:54:23  .================================
00:54:23  Printing MONAI config...
00:54:23  ================================
00:54:23  MONAI version: 0.8.1+220.g0cdec837
00:54:23  Numpy version: 1.22.3
00:54:23  Pytorch version: 1.10.0a0+0aef44c
00:54:23  MONAI flags: HAS_EXT = True, USE_COMPILED = True
00:54:23  MONAI rev id: 0cdec837a6ae43cdc46d2ce80befb0362b07e47c
00:54:23  MONAI __file__: /home/jenkins/agent/workspace/Monai-latest-image/monai/__init__.py
00:54:23  
00:54:23  Optional dependencies:
00:54:23  Pytorch Ignite version: 0.4.8
00:54:23  Nibabel version: 3.2.2
00:54:23  scikit-image version: 0.19.1
00:54:23  Pillow version: 9.0.1
00:54:23  Tensorboard version: 2.6.0
00:54:23  gdown version: 4.2.1
00:54:23  TorchVision version: 0.11.0a0
00:54:23  tqdm version: 4.62.3
00:54:23  lmdb version: 1.2.1
00:54:23  psutil version: 5.8.0
00:54:23  pandas version: 1.4.1
00:54:23  einops version: 0.4.0
00:54:23  transformers version: 4.16.2
00:54:23  mlflow version: 1.23.1
```

**Comment by Nic-Ma** [comment]
Hi @yiheng-wang-nv ,

Could you please help take a look at this issue? Seems the test code is not compatible with old PyTorch.

Thanks in advance.

**Comment by wyli** [comment]
a similar issue with docker 21.02:
```
01:12:47  ======================================================================
01:12:47  ERROR: test_load_ts_module_0 (tests.test_bundle_download.TestLoad)
01:12:47  ----------------------------------------------------------------------
01:12:47  Traceback (most recent call last):
01:12:47    File "/opt/conda/lib/python3.8/site-packages/parameterized/parameterized.py", line 533, in standalone_func
01:12:47      return func(*(a + p.args), **p.kwargs)
01:12:47    File "/home/jenkins/agent/workspace/Monai-latest-image/tests/test_bundle_download.py", line 149, in test_load_ts_module
01:12:47      model_ts, metadata, extra_file_dict = load(
01:12:47    File "/home/jenkins/agent/workspace/Monai-latest-image/monai/bundle/scripts.py", line 285, in load
01:12:47      return load_net_with_metadata(full_path, map_location=torch.device(device), more_extra_files=config_files)
01:12:47    File "/home/jenkins/agent/workspace/Monai-latest-image/monai/data/torchscript_utils.py", line 119, in load_net_with_metadata
01:12:47      jit_obj = torch.jit.load(filename_prefix_or_stream, map_location, extra_files)
01:12:47    File "/opt/conda/lib/python3.8/site-packages/torch/jit/_serialization.py", line 161, in load
01:12:47      cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
01:12:47  RuntimeError: 
01:12:47  Unknown type name 'NoneType':
01:12:47  Serialized   File "code/__torch__/torch/nn/modules/container.py", line 5
01:12:47    __buffers__ = []
01:12:47    training : bool
01:12:47    _is_full_backward_hook : NoneType
01:12:47                             ~~~~~~~~ <--- HERE
01:12:47    __annotations__["0"] = __torch__.monai.networks.blocks.convolutions.Convolution
01:12:47    __annotations__["1"] = __torch__.monai.networks.layers.simplelayers.SkipConnection
01:12:47  
01:12:47  
01:12:47  ----------------------------------------------------------------------
```
