### ISSUE TITLE
integration errors metatensor

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#4246]
**Describe the bug**
mainly from the cron tests
https://github.com/Project-MONAI/MONAI/runs/6324311456?check_suite_focus=true
```
======================================================================
ERROR: test_training (__main__.IntegrationClassification2D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_integration_classification_2d.py", line 266, in test_training
    results = self.train_and_infer(i)
  File "tests/test_integration_classification_2d.py", line 242, in train_and_infer
    losses, best_metric, best_metric_epoch = run_training_test(
  File "tests/test_integration_classification_2d.py", line 134, in run_training_test
    y_pred = [y_pred_trans(i) for i in decollate_batch(y_pred)]
  File "/__w/MONAI/MONAI/monai/data/utils.py", line 480, in decollate_batch
    metas = decollate_batch(batch.meta)
  File "/__w/MONAI/MONAI/monai/data/utils.py", line 488, in decollate_batch
    b, non_iterable, deco = _non_zipping_check(batch, detach, pad, fill_value)
  File "/__w/MONAI/MONAI/monai/data/utils.py", line 395, in _non_zipping_check
    _deco = {key: decollate_batch(batch_data[key], detach, pad=pad, fill_value=fill_value) for key in batch_data}
  File "/__w/MONAI/MONAI/monai/data/utils.py", line 395, in <dictcomp>
    _deco = {key: decollate_batch(batch_data[key], detach, pad=pad, fill_value=fill_value) for key in batch_data}
  File "/__w/MONAI/MONAI/monai/data/utils.py", line 488, in decollate_batch
    b, non_iterable, deco = _non_zipping_check(batch, detach, pad, fill_value)
  File "/__w/MONAI/MONAI/monai/data/utils.py", line 397, in _non_zipping_check
    _deco = [decollate_batch(b, detach, pad=pad, fill_value=fill_value) for b in batch_data]
  File "/__w/MONAI/MONAI/monai/data/utils.py", line 397, in <listcomp>
    _deco = [decollate_batch(b, detach, pad=pad, fill_value=fill_value) for b in batch_data]
  File "/__w/MONAI/MONAI/monai/data/utils.py", line 488, in decollate_batch
    b, non_iterable, deco = _non_zipping_check(batch, detach, pad, fill_value)
  File "/__w/MONAI/MONAI/monai/data/utils.py", line 399, in _non_zipping_check
    raise NotImplementedError(f"Unable to de-collate: {batch_data}, type: {type(batch_data)}.")
NotImplementedError: Unable to de-collate: 64, type: <class 'numpy.int64'>.

----------------------------------------------------------------------
```
there might be further issues as the integration tests are in fail-fast mode. I'll try to fix all.

**Comment by wyli** [comment]
addressed in https://github.com/Project-MONAI/MONAI/pull/4248
