### ISSUE TITLE
tests.test_resize error

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#4315]
**Describe the bug**
```
[2022-05-22T09:30:59.623Z] ======================================================================
[2022-05-22T09:30:59.623Z] FAIL: test_correct_results_2 (tests.test_resize.TestResize)
[2022-05-22T09:30:59.623Z] ----------------------------------------------------------------------
[2022-05-22T09:30:59.623Z] Traceback (most recent call last):
[2022-05-22T09:30:59.623Z]   File "/opt/conda/lib/python3.8/site-packages/parameterized/parameterized.py", line 533, in standalone_func
[2022-05-22T09:30:59.623Z]     return func(*(a + p.args), **p.kwargs)
[2022-05-22T09:30:59.623Z]   File "/home/jenkins/agent/workspace/MONAI-premerge/monai/tests/test_resize.py", line 77, in test_correct_results
[2022-05-22T09:30:59.623Z]     self.assertLessEqual(
[2022-05-22T09:30:59.623Z] AssertionError: 0.201171875 not less than or equal to 0.2 : at most 20 percent mismatch 
[2022-05-22T09:30:59.623Z] 
[2022-05-22T09:30:59.623Z] ----------------------------------------------------------------------
[2022-05-22T09:30:59.623Z] Ran 8676 tests in 1098.951s
```

- nvcr.io/nvidia/pytorch:21.03-py3
- cuda 11.2

(couldn't reliably replicate this issue)

**Comment by wyli** [comment]
workaround included in https://github.com/Project-MONAI/MONAI/pull/4307
