### ISSUE TITLE
integration error `protobuf`

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#4354]
**Describe the bug**
```
[2022-05-26T02:21:23.668Z] Traceback (most recent call last):
[2022-05-26T02:21:23.668Z]   File "./tests/runner.py", line 133, in <module>
[2022-05-26T02:21:23.668Z]     tests = unittest.TestLoader().loadTestsFromNames(cases)
[2022-05-26T02:21:23.668Z]   File "/usr/lib/python3.8/unittest/loader.py", line 220, in loadTestsFromNames
[2022-05-26T02:21:23.668Z]     suites = [self.loadTestsFromName(name, module) for name in names]
[2022-05-26T02:21:23.668Z]   File "/usr/lib/python3.8/unittest/loader.py", line 220, in <listcomp>
[2022-05-26T02:21:23.668Z]     suites = [self.loadTestsFromName(name, module) for name in names]
[2022-05-26T02:21:23.668Z]   File "/usr/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
[2022-05-26T02:21:23.668Z]     module = __import__(module_name)
[2022-05-26T02:21:23.668Z]   File "/home/jenkins/agent/workspace/Monai-pytorch-versions/tests/test_plot_2d_or_3d_image.py", line 18, in <module>
[2022-05-26T02:21:23.668Z]     from torch.utils.tensorboard import SummaryWriter
[2022-05-26T02:21:23.668Z]   File "/usr/local/lib/python3.8/dist-packages/torch/utils/tensorboard/__init__.py", line 13, in <module>
[2022-05-26T02:21:23.668Z]     from .writer import FileWriter, SummaryWriter  # noqa: F401
[2022-05-26T02:21:23.668Z]   File "/usr/local/lib/python3.8/dist-packages/torch/utils/tensorboard/writer.py", line 9, in <module>
[2022-05-26T02:21:23.668Z]     from tensorboard.compat.proto.event_pb2 import SessionLog
[2022-05-26T02:21:23.668Z]   File "/usr/local/lib/python3.8/dist-packages/tensorboard/compat/proto/event_pb2.py", line 17, in <module>
[2022-05-26T02:21:23.668Z]     from tensorboard.compat.proto import summary_pb2 as tensorboard_dot_compat_dot_proto_dot_summary__pb2
[2022-05-26T02:21:23.668Z]   File "/usr/local/lib/python3.8/dist-packages/tensorboard/compat/proto/summary_pb2.py", line 17, in <module>
[2022-05-26T02:21:23.668Z]     from tensorboard.compat.proto import tensor_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__pb2
[2022-05-26T02:21:23.668Z]   File "/usr/local/lib/python3.8/dist-packages/tensorboard/compat/proto/tensor_pb2.py", line 16, in <module>
[2022-05-26T02:21:23.668Z]     from tensorboard.compat.proto import resource_handle_pb2 as tensorboard_dot_compat_dot_proto_dot_resource__handle__pb2
[2022-05-26T02:21:23.668Z]   File "/usr/local/lib/python3.8/dist-packages/tensorboard/compat/proto/resource_handle_pb2.py", line 16, in <module>
[2022-05-26T02:21:23.668Z]     from tensorboard.compat.proto import tensor_shape_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__shape__pb2
[2022-05-26T02:21:23.668Z]   File "/usr/local/lib/python3.8/dist-packages/tensorboard/compat/proto/tensor_shape_pb2.py", line 36, in <module>
[2022-05-26T02:21:23.668Z]     _descriptor.FieldDescriptor(
[2022-05-26T02:21:23.668Z]   File "/usr/local/lib/python3.8/dist-packages/google/protobuf/descriptor.py", line 560, in __new__
[2022-05-26T02:21:23.668Z]     _message.Message._CheckCalledFromGeneratedFile()
[2022-05-26T02:21:23.668Z] TypeError: Descriptors cannot not be created directly.
[2022-05-26T02:21:23.668Z] If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
[2022-05-26T02:21:23.668Z] If you cannot immediately regenerate your protos, some other possible workarounds are:
[2022-05-26T02:21:23.668Z]  1. Downgrade the protobuf package to 3.20.x or lower.
[2022-05-26T02:21:23.668Z]  2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
[2022-05-26T02:21:23.668Z] 
[2022-05-26T02:21:23.668Z] More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by wyli** [comment]
the main issue is a BC breaking change from protobuf 4.21 https://pypi.org/project/protobuf/#history

**Comment by wyli** [comment]
workaround included https://github.com/Project-MONAI/MONAI/blob/40717509198909b444d9566052602b7db0cfd0cb/runtests.sh#L17-L22
