### ISSUE TITLE
ERROR: test_metrics_track

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#4375]
**Describe the bug**
```
[2022-05-28T01:55:47.732Z] ======================================================================
[2022-05-28T01:55:47.732Z] ERROR: test_metrics_track (tests.test_handler_mlflow.TestHandlerMLFlow)
[2022-05-28T01:55:47.732Z] ----------------------------------------------------------------------
[2022-05-28T01:55:47.732Z] Traceback (most recent call last):
[2022-05-28T01:55:47.732Z]   File "/home/jenkins/agent/workspace/MONAI-premerge/monai/tests/test_handler_mlflow.py", line 42, in test_metrics_track
[2022-05-28T01:55:47.732Z]     handler = MLFlowHandler(
[2022-05-28T01:55:47.732Z]   File "/home/jenkins/agent/workspace/MONAI-premerge/monai/monai/handlers/mlflow_handler.py", line 91, in __init__
[2022-05-28T01:55:47.733Z]     mlflow.set_tracking_uri(tracking_uri)
[2022-05-28T01:55:47.733Z]   File "/home/jenkins/agent/workspace/MONAI-premerge/monai/monai/utils/module.py", line 378, in __getattr__
[2022-05-28T01:55:47.733Z]     raise self._exception
[2022-05-28T01:55:47.733Z]   File "/home/jenkins/agent/workspace/MONAI-premerge/monai/monai/utils/module.py", line 337, in optional_import
[2022-05-28T01:55:47.733Z]     pkg = __import__(module)  # top level module
[2022-05-28T01:55:47.733Z]   File "/opt/conda/lib/python3.8/site-packages/mlflow/__init__.py", line 32, in <module>
[2022-05-28T01:55:47.733Z]     import mlflow.tracking._model_registry.fluent
[2022-05-28T01:55:47.733Z]   File "/opt/conda/lib/python3.8/site-packages/mlflow/tracking/__init__.py", line 8, in <module>
[2022-05-28T01:55:47.733Z]     from mlflow.tracking.client import MlflowClient
[2022-05-28T01:55:47.733Z]   File "/opt/conda/lib/python3.8/site-packages/mlflow/tracking/client.py", line 16, in <module>
[2022-05-28T01:55:47.733Z]     from mlflow.entities import Experiment, Run, RunInfo, Param, Metric, RunTag, FileInfo, ViewType
[2022-05-28T01:55:47.733Z]   File "/opt/conda/lib/python3.8/site-packages/mlflow/entities/__init__.py", line 6, in <module>
[2022-05-28T01:55:47.733Z]     from mlflow.entities.experiment import Experiment
[2022-05-28T01:55:47.733Z]   File "/opt/conda/lib/python3.8/site-packages/mlflow/entities/experiment.py", line 2, in <module>
[2022-05-28T01:55:47.733Z]     from mlflow.entities.experiment_tag import ExperimentTag
[2022-05-28T01:55:47.733Z]   File "/opt/conda/lib/python3.8/site-packages/mlflow/entities/experiment_tag.py", line 2, in <module>
[2022-05-28T01:55:47.733Z]     from mlflow.protos.service_pb2 import ExperimentTag as ProtoExperimentTag
[2022-05-28T01:55:47.733Z]   File "/opt/conda/lib/python3.8/site-packages/mlflow/protos/service_pb2.py", line 18, in <module>
[2022-05-28T01:55:47.733Z]     from .scalapb import scalapb_pb2 as scalapb_dot_scalapb__pb2
[2022-05-28T01:55:47.733Z]   File "/opt/conda/lib/python3.8/site-packages/mlflow/protos/scalapb/scalapb_pb2.py", line 22, in <module>
[2022-05-28T01:55:47.733Z]     options = DESCRIPTOR.extensions_by_name['options']
[2022-05-28T01:55:47.733Z] monai.utils.module.OptionalImportError: import mlflow ('NoneType' object has no attribute 'extensions_by_name').
[2022-05-28T01:55:47.733Z] 
[2022-05-28T01:55:47.733Z] For details about installing the optional dependencies, please visit:
[2022-05-28T01:55:47.733Z]     https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies
[2022-05-28T01:55:47.733Z] 
[2022-05-28T01:55:47.733Z] ----------------------------------------------------------------------
```

**Comment by Nic-Ma** [comment]
Seems MLFlow updated the API recently.
Let me try to investigate it deeper.

Thanks.

**Comment by wyli** [comment]
mlflow  1.26.1, protobuf 3.15.6 filed a ticket https://github.com/mlflow/mlflow/issues/5968

**Comment by wyli** [comment]
> Seems MLFlow updated the API recently. Let me try to investigate it deeper.
> 
> Thanks.

didn't see your comment earlier, I think it's fine to skip 1.26.1 for now
