### ISSUE TITLE
deepcopy metatensor []

### ISSUE THREAD

**Issue by mjq93** [Project-MONAI/MONAI#4699]
**Describe the bug**

Error while training detection model：
"RuntimeError: The default implementation of __deepcopy__() for wrapper subclasses only works for subclass types that implement clone() and for which cloning returns another instance of the same subclass. You should either properly implement clone() for your subclass or override __deepcopy__() if it is intended behavior for clone() to return an instance of a different type."

Further debugging revealed that it was the deepcopy function that reported an error on a MetaTensor variable if it was empty size.

<img width="512" alt="image" src="https://user-images.githubusercontent.com/11666931/178977185-a32663bb-d15d-486b-a246-c441ead7474a.png">

**Comment by wyli** [comment]
I can replicate this one:
```py
>>> from copy import deepcopy
>>> from monai.data import MetaTensor
>>> deepcopy(MetaTensor([]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "py38/lib/python3.8/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "py38/lib/python3.8/site-packages/torch/_tensor.py", line 87, in __deepcopy__
    return handle_torch_function(Tensor.__deepcopy__, (self,), self, memo)
  File "py38/lib/python3.8/site-packages/torch/overrides.py", line 1498, in handle_torch_function
    result = torch_func_method(public_api, types, args, kwargs)
  File "MONAI/monai/data/meta_tensor.py", line 266, in __torch_function__
    ret = super().__torch_function__(func, types, args, kwargs)
  File "py38/lib/python3.8/site-packages/torch/_tensor.py", line 1121, in __torch_function__
    ret = func(*args, **kwargs)
  File "py38/lib/python3.8/site-packages/torch/_tensor.py", line 103, in __deepcopy__
    raise RuntimeError("The default implementation of __deepcopy__() for wrapper subclasses "
RuntimeError: The default implementation of __deepcopy__() for wrapper subclasses only works for subclass types that implement clone() and for which cloning returns another instance of the same subclass. You should either properly implement clone() for your subclass or override __deepcopy__() if it is intended behavior for clone() to return an instance of a different type.
>>> 
```
