### ISSUE TITLE
Why does get_default_applied_operations for MetaObj only return an empty list?

### ISSUE THREAD

**Issue by ltsc256** [Project-MONAI/MONAI#4754]
I have been getting this error (see below) and found that the error was caused by an empty list for all_transforms. Looking at the code in inverse.py, the problem was in line 186 where all_transforms = data.get(self.trace_key(key), MetaTensor.get_default_applied_operations()). But get_default_applied_operations() only returns an empty list according to the source code provided here: https://docs.monai.io/en/stable/_modules/monai/data/meta_obj.html#MetaObj.get_default_applied_operations

How can I resolve this issue? (Config also pasted below)

Traceback (most recent call last):
  File "/home/user1/monai/MONAI/monai/transforms/transform.py", line 90, in apply_transform
    return _apply_transform(transform, data, unpack_items)
  File "/home/user1/monai/MONAI/monai/transforms/transform.py", line 54, in _apply_transform
    return transform(parameters)
  File "/home/user1/monai/MONAI/monai/transforms/utility/dictionary.py", line 523, in inverse
    self.pop_transform(d, key)
  File "/home/user1/monai/MONAI/monai/transforms/inverse.py", line 210, in pop_transform
    return self.get_most_recent_transform(data, key, check, pop=True)
  File "/home/user1/monai/MONAI/monai/transforms/inverse.py", line 192, in get_most_recent_transform
    self.check_transforms_match(all_transforms[-1])
IndexError: **list index out of range**

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user1/monai/MONAI/monai/transforms/transform.py", line 90, in apply_transform
    return _apply_transform(transform, data, unpack_items)
  File "/home/user1/monai/MONAI/monai/transforms/transform.py", line 54, in _apply_transform
    return transform(parameters)
  File "/home/user1/monai/MONAI/monai/transforms/post/dictionary.py", line 664, in __call__
    inverted = self.transform.inverse(input_dict)
  File "/home/user1/monai/MONAI/monai/transforms/compose.py", line 183, in inverse
    data = apply_transform(t.inverse, data, self.map_items, self.unpack_items, self.log_stats)
  File "/home/user1/monai/MONAI/monai/transforms/transform.py", line 114, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <bound method ToTensord.inverse of <monai.transforms.utility.dictionary.ToTensord object at 0x7f04da6b8cd0>>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user1/monai/MONAI/unetr_inference.py", line 143, in <module>
    main()
  File "/home/user1/monai/MONAI/unetr_inference.py", line 133, in main
    d = [post_transforms(i) for i in decollate_batch(d)]
  File "/home/user1/monai/MONAI/unetr_inference.py", line 133, in <listcomp>
    d = [post_transforms(i) for i in decollate_batch(d)]
  File "/home/user1/monai/MONAI/monai/transforms/compose.py", line 173, in __call__
    input_ = apply_transform(_transform, input_, self.map_items, self.unpack_items, self.log_stats)
  File "/home/user1/monai/MONAI/monai/transforms/transform.py", line 114, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.post.dictionary.Invertd object at 0x7f04da67aa90>

MONAI version: 0.9.1rc4+12.g5e36e23c.dirty
Numpy version: 1.22.4
Pytorch version: 1.11.0+cu102
MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
MONAI rev id: 5e36e23c06a7f6cc4bc895d0cc37959535daba6b
MONAI __file__: /home/user1/monai/MONAI/monai/__init__.py

Optional dependencies:
Pytorch Ignite version: 0.4.8
Nibabel version: 3.2.2
scikit-image version: 0.19.2
Pillow version: 9.0.1
Tensorboard version: 2.9.1
gdown version: 4.4.0
TorchVision version: 0.12.0+cu102
tqdm version: 4.64.0
lmdb version: 1.3.0
psutil version: 5.9.1
pandas version: 1.4.2
einops version: 0.4.1
transformers version: 4.20.0
mlflow version: 1.26.1
pynrrd version: 0.4.3

**Comment by wyli** [comment]
Looks like the ToTensord transform has converted a metatensor to a regular tensor and applied operations history was therefore dropped. Please try removing the ToTensord.

**Comment by ltsc256** [comment]
Hello! Thank you for quick response. track_meta to True did not resolve error but removing ToTensord fixed it. However, now pred_meta_dict is None. I can work around this however so yay thank you so much for resolving this so quickly.

**Comment by wyli** [comment]
sure, thanks for the follow up, you can get the meta dict by `d['pred'].meta` for the previously `d['pred_meta_dict']`.
