### ISSUE TITLE
Switching from v0.8 to v0.9.1 breaks my code

### ISSUE THREAD

**Issue by dzenanz** [Project-MONAI/MONAI#4763]
**Describe the bug**
A code that used to run now crashes.

**To Reproduce**
1. I upgraded PyTorch to 1.12 (I don't remember which version I had before, maybe 1.9?)
2. I upgraded MONAI from 0.8 to 0.9
3. Click `Run 'Train Small' Ctrl+F5` in PyCharm

**Expected behavior**
Network is trained.

**Source code**
https://github.com/OpenImaging/miqa/blob/36b3590e32828c0a76a0a6fdd889402d99dad5b5/miqa/learning/nn_training.py

**Run log**
```log
"C:\Program Files\Python39\python.exe" M:/MIQA/miqa/miqa/learning/nn_training.py -f M:/MIQA/T1bis_fold -p M:/MIQA/PredictHD_small/ -c 3 -v 2
MONAI version: 0.9.1
Numpy version: 1.21.2
Pytorch version: 1.12.0+cu116
MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
MONAI rev id: 356d2d2f41b473f588899d705bbc682308cee52c
MONAI __file__: C:\Program Files\Python39\lib\site-packages\monai\__init__.py

Optional dependencies:
INFO:__main__:Namespace(predicthd='M:/MIQA/PredictHD_small/', ncanda=None, folds='M:/MIQA/T1bis_fold', vfold=2, nfolds=3, evaluate=False, all=False, evaluate1=None, modelfile=None)
Pytorch Ignite version: NOT INSTALLED or UNKNOWN VERSION.
Nibabel version: 3.2.1
scikit-image version: 0.18.3
Pillow version: 9.2.0
Tensorboard version: 2.6.0
gdown version: NOT INSTALLED or UNKNOWN VERSION.
TorchVision version: 0.13.0+cu116
tqdm version: 4.62.2
lmdb version: NOT INSTALLED or UNKNOWN VERSION.
psutil version: 5.8.0
pandas version: 1.3.2
einops version: NOT INSTALLED or UNKNOWN VERSION.
transformers version: NOT INSTALLED or UNKNOWN VERSION.
mlflow version: NOT INSTALLED or UNKNOWN VERSION.
pynrrd version: NOT INSTALLED or UNKNOWN VERSION.

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

Verifying input data integrity of M:/MIQA/T1bis_fold0.csv
Verifying input data integrity of M:/MIQA/T1bis_fold1.csv
Verifying input data integrity of M:/MIQA/T1bis_fold2.csv
INFO:__main__:
     participant_id  session_id  ... exists       dimensions
0             45760       24071  ...   True  (192, 256, 104)
1             45760       56022  ...   True  (192, 256, 104)
2             45760       58140  ...   True  (192, 256, 104)
3             12740       39997  ...   True  (192, 256, 128)
4             50486       41791  ...   True  (192, 256, 128)
..              ...         ...  ...    ...              ...
266          668817       50846  ...   True  (256, 256, 100)
267          675282       39187  ...   True  (288, 288, 100)
268          693332       46059  ...   True  (256, 256, 124)
269          448184       34147  ...   True  (240, 320, 320)
270          638921       26071  ...   True  (256, 256, 100)

[271 rows x 24 columns]
INFO:__main__:Using fold 2 for validation
wandb: Currently logged in as: dzenanz. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.12.21
wandb: Run data is saved locally in M:\MIQA\miqa\miqa\learning\wandb\run-20220725_154640-34l81fag
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run distinctive-snowflake-10
wandb:  View project at https://wandb.ai/dzenanz/miqaMix
wandb:  View run at https://wandb.ai/dzenanz/miqaMix/runs/34l81fag
INFO:__main__:weights_array: [[0.82634731 0.92215569 0.07185629 0.98203593 0.59281437 0.50299401
  0.86826347 0.59281437 0.76646707 0.7005988 ]
 [0.17365269 0.07784431 0.92814371 0.01796407 0.02994012 0.11976048
  0.13173653 0.02994012 0.23353293 0.2994012 ]]
INFO:nn_inference:NN model is initialized with random weights
INFO:__main__:-------------------------
INFO:__main__:epoch 1/110
INFO:__main__:epoch_len: 167
Traceback (most recent call last):
  File "M:\MIQA\miqa\miqa\learning\nn_training.py", line 742, in <module>
    process_folds(args.folds, args.vfold, args.evaluate, args.nfolds)
  File "M:\MIQA\miqa\miqa\learning\nn_training.py", line 692, in process_folds
    sizes = train_and_save_model(
  File "M:\MIQA\miqa\miqa\learning\nn_training.py", line 598, in train_and_save_model
    for batch_data in train_loader:
  File "C:\Program Files\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 652, in __next__
    data = self._next_data()
  File "C:\Program Files\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 1347, in _next_data
    return self._process_data(data)
  File "C:\Program Files\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 1373, in _process_data
    data.reraise()
  File "C:\Program Files\Python39\lib\site-packages\torch\_utils.py", line 461, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Program Files\Python39\lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "C:\Program Files\Python39\lib\site-packages\torch\utils\data\_utils\collate.py", line 160, in default_collate
    return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
  File "C:\Program Files\Python39\lib\site-packages\torch\utils\data\_utils\collate.py", line 160, in <dictcomp>
    return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
  File "C:\Program Files\Python39\lib\site-packages\torch\utils\data\_utils\collate.py", line 160, in default_collate
    return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
  File "C:\Program Files\Python39\lib\site-packages\torchio\data\image.py", line 639, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Program Files\Python39\lib\site-packages\torchio\data\image.py", line 156, in __init__
    self.path = self._parse_path(path)
  File "C:\Program Files\Python39\lib\site-packages\torchio\data\image.py", line 418, in _parse_path
    return [self._parse_single_path(p) for p in path]
  File "C:\Program Files\Python39\lib\site-packages\torchio\data\image.py", line 418, in <listcomp>
    return [self._parse_single_path(p) for p in path]
  File "C:\Program Files\Python39\lib\site-packages\torchio\data\image.py", line 408, in _parse_single_path
    raise FileNotFoundError(f'File not found: "{path}"')
FileNotFoundError: File not found: "data"

wandb: Waiting for W&B process to finish... (failed 1). Press Ctrl-C to abort syncing.
wandb:                                                                                
wandb: Synced distinctive-snowflake-10: https://wandb.ai/dzenanz/miqaMix/runs/34l81fag
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 3 other file(s)
wandb: Find logs at: .\wandb\run-20220725_154640-34l81fag\logs

Process finished with exit code 1
```

**Comment by wyli** [comment]
Hi @dzenanz, looking at the error traceback, it's from `site-packages\torchio`, could you please create a smaller example to reproduce this issue?

**Comment by dzenanz** [comment]
You are right, `pip3 install --upgrade torchio` solved the problem.
This moved me from `torchio-0.18.53` to `torchio-0.18.83`.
