### ISSUE TITLE
Bug in deepgrow dataset

### ISSUE THREAD

**Issue by KumoLiu** [Project-MONAI/MONAI#4828]
**Describe the bug**
It does't work when replace `AsChannelFirstd` with `EnsureChannelFirstd` in [deepgrow's dataset](https://github.com/Project-MONAI/MONAI/blob/dev/monai/apps/deepgrow/dataset.py). 
It mainly due to `_save_data_2d` only works on the image since `EnsureChannelFirstd` also makes the label 4-dimensional(with channel 1 at the first).
https://github.com/Project-MONAI/MONAI/blob/f317aeb1ed93f6d7c43d7d119eca0c00f5c6fdb3/monai/apps/deepgrow/dataset.py#L138-L148

**To Reproduce**
python -m unittest test_deepgrow_dataset.py

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/parameterized/parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/workspace/Code/MONAI/tests/test_deepgrow_dataset.py", line 87, in test_create_dataset
    deepgrow_datalist = create_dataset(datalist=datalist, output_dir=self.tempdir, **args)
  File "/workspace/Code/MONAI/monai/apps/deepgrow/dataset.py", line 105, in create_dataset
    data = _save_data_2d(
  File "/workspace/Code/MONAI/monai/apps/deepgrow/dataset.py", line 159, in _save_data_2d
    label = vol_label[sid, ...] if vol_label is not None else None
IndexError: index 1 is out of bounds for axis 0 with size 1

(cc @SachidanandAlle @diazandr3s @wyli @Nic-Ma)

**Comment by SachidanandAlle** [comment]
@finalelement can you please have a look
