### ISSUE TITLE
integration error IntegrationFastTrain

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#4926]
**Describe the bug**
```
[2022-08-18T00:38:37.360Z] tests/test_integration_fast_train.py
[2022-08-18T00:38:42.610Z] MONAI version: 0.9.1+46.gfb976d7c.dirty
[2022-08-18T00:38:42.612Z] Numpy version: 1.19.2
[2022-08-18T00:38:42.612Z] Pytorch version: 1.8.0a0+52ea372
[2022-08-18T00:38:42.612Z] MONAI flags: HAS_EXT = True, USE_COMPILED = True, USE_META_DICT = False
[2022-08-18T00:38:42.612Z] MONAI rev id: fb976d7c6a2fc01640b3593775395f0a7f27b1db
[2022-08-18T00:38:42.612Z] MONAI __file__: /home/jenkins/agent/workspace/Monai-latest-image/monai/__init__.py
[2022-08-18T00:38:42.612Z] 
[2022-08-18T00:38:42.612Z] Optional dependencies:
[2022-08-18T00:38:42.612Z] Pytorch Ignite version: 0.4.9
[2022-08-18T00:38:42.612Z] Nibabel version: 4.0.1
[2022-08-18T00:38:42.612Z] scikit-image version: 0.19.3
[2022-08-18T00:38:42.612Z] Pillow version: 9.2.0
[2022-08-18T00:38:42.612Z] Tensorboard version: 1.15.0+nv
[2022-08-18T00:38:42.612Z] gdown version: 4.5.1
[2022-08-18T00:38:42.612Z] TorchVision version: 0.9.0a0
[2022-08-18T00:38:42.612Z] tqdm version: 4.53.0
[2022-08-18T00:38:42.612Z] lmdb version: 1.1.1
[2022-08-18T00:38:42.612Z] psutil version: 5.8.0
[2022-08-18T00:38:42.612Z] pandas version: 1.1.4
[2022-08-18T00:38:42.612Z] einops version: 0.4.1
[2022-08-18T00:38:42.612Z] transformers version: 4.21.1
[2022-08-18T00:38:42.612Z] mlflow version: 1.28.0
[2022-08-18T00:38:42.612Z] pynrrd version: 0.4.3
[2022-08-18T00:38:42.612Z] 
[2022-08-18T00:38:42.612Z] For details about installing the optional dependencies, please visit:
[2022-08-18T00:38:42.612Z]     https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies
[2022-08-18T00:38:42.612Z] 
[2022-08-18T00:38:56.126Z] 
Loading dataset:   0%|          | 0/32 [00:00<?, ?it/s]
Loading dataset:   3%|▎         | 1/32 [00:02<01:11,  2.30s/it]
Loading dataset:  28%|██▊       | 9/32 [00:02<00:37,  1.62s/it]
Loading dataset:  53%|█████▎    | 17/32 [00:03<00:17,  1.15s/it]
Loading dataset:  78%|███████▊  | 25/32 [00:03<00:05,  1.22it/s]
Loading dataset: 100%|██████████| 32/32 [00:03<00:00,  9.46it/s]
[2022-08-18T00:39:18.534Z] 
Loading dataset:   0%|          | 0/9 [00:00<?, ?it/s]
Loading dataset:  11%|█         | 1/9 [00:00<00:02,  3.97it/s]
Loading dataset:  67%|██████▋   | 6/9 [00:00<00:00,  5.41it/s]
Loading dataset: 100%|██████████| 9/9 [00:00<00:00, 21.92it/s]----------
[2022-08-18T00:39:18.535Z] epoch 1/5
[2022-08-18T00:39:18.535Z] 1/8, train_loss: 1.2720 step time: 1.1163
[2022-08-18T00:39:18.535Z] 2/8, train_loss: 1.2866 step time: 0.1583
[2022-08-18T00:39:18.535Z] 3/8, train_loss: 1.2420 step time: 0.1234
[2022-08-18T00:39:18.535Z] 4/8, train_loss: 1.1847 step time: 0.1793
[2022-08-18T00:39:18.535Z] 5/8, train_loss: 1.1652 step time: 0.1353
[2022-08-18T00:39:18.535Z] 6/8, train_loss: 1.1115 step time: 0.1393
[2022-08-18T00:39:18.535Z] 7/8, train_loss: 1.0635 step time: 0.1516
[2022-08-18T00:39:18.535Z] 8/8, train_loss: 1.0239 step time: 0.1090
[2022-08-18T00:39:18.535Z] epoch 1 average loss: 1.1687
[2022-08-18T00:39:18.535Z] epoch: 1 current mean dice: 0.6315, best mean dice: 0.6315
[2022-08-18T00:39:18.535Z] time consuming of epoch 1 is: 5.2572
[2022-08-18T00:39:18.535Z] ----------
[2022-08-18T00:39:18.535Z] epoch 2/5
[2022-08-18T00:39:18.535Z] 1/8, train_loss: 0.9874 step time: 0.1354
[2022-08-18T00:39:18.535Z] 2/8, train_loss: 0.9417 step time: 0.1443
[2022-08-18T00:39:18.535Z] 3/8, train_loss: 0.9094 step time: 0.1286
[2022-08-18T00:39:18.535Z] 4/8, train_loss: 0.8882 step time: 0.1495
[2022-08-18T00:39:18.535Z] 5/8, train_loss: 0.8600 step time: 0.1551
[2022-08-18T00:39:18.535Z] 6/8, train_loss: 0.8587 step time: 0.1525
[2022-08-18T00:39:18.535Z] 7/8, train_loss: 0.8021 step time: 0.1472
[2022-08-18T00:39:18.535Z] 8/8, train_loss: 0.8104 step time: 0.1082
[2022-08-18T00:39:18.535Z] epoch 2 average loss: 0.8822
[2022-08-18T00:39:18.535Z] epoch: 2 current mean dice: 0.7135, best mean dice: 0.7135
[2022-08-18T00:39:18.535Z] time consuming of epoch 2 is: 3.3445
[2022-08-18T00:39:18.535Z] ----------
[2022-08-18T00:39:18.535Z] epoch 3/5
[2022-08-18T00:39:18.535Z] 1/8, train_loss: 0.7365 step time: 0.1579
[2022-08-18T00:39:18.535Z] 2/8, train_loss: 0.7155 step time: 0.1474
[2022-08-18T00:39:18.535Z] 3/8, train_loss: 0.6753 step time: 0.1424
[2022-08-18T00:39:18.535Z] 4/8, train_loss: 0.6412 step time: 0.1720
[2022-08-18T00:39:18.535Z] 5/8, train_loss: 0.6320 step time: 0.1540
[2022-08-18T00:39:18.535Z] 6/8, train_loss: 0.5749 step time: 0.1432
[2022-08-18T00:39:18.535Z] 7/8, train_loss: 0.5430 step time: 0.1393
[2022-08-18T00:39:18.535Z] 8/8, train_loss: 0.5349 step time: 0.1103
[2022-08-18T00:39:18.535Z] epoch 3 average loss: 0.6317
[2022-08-18T00:39:18.535Z] epoch: 3 current mean dice: 0.8878, best mean dice: 0.8878
[2022-08-18T00:39:18.535Z] time consuming of epoch 3 is: 3.2127
[2022-08-18T00:39:18.535Z] ----------
[2022-08-18T00:39:18.535Z] epoch 4/5
[2022-08-18T00:39:18.535Z] 1/8, train_loss: 0.4594 step time: 0.1523
[2022-08-18T00:39:18.535Z] 2/8, train_loss: 0.4142 step time: 0.1279
[2022-08-18T00:39:18.535Z] 3/8, train_loss: 0.3812 step time: 0.1603
[2022-08-18T00:39:18.535Z] 4/8, train_loss: 0.3536 step time: 0.1557
[2022-08-18T00:39:18.535Z] 5/8, train_loss: 0.3181 step time: 0.1311
[2022-08-18T00:39:18.535Z] 6/8, train_loss: 0.3006 step time: 0.1479
[2022-08-18T00:39:18.535Z] 7/8, train_loss: 0.2692 step time: 0.1480
[2022-08-18T00:39:18.535Z] 8/8, train_loss: 0.2432 step time: 0.1094
[2022-08-18T00:39:18.535Z] epoch 4 average loss: 0.3425
[2022-08-18T00:39:18.535Z] epoch: 4 current mean dice: 0.8964, best mean dice: 0.8964
[2022-08-18T00:39:18.535Z] time consuming of epoch 4 is: 3.4288
[2022-08-18T00:39:18.535Z] ----------
[2022-08-18T00:39:18.535Z] epoch 5/5
[2022-08-18T00:39:18.535Z] 1/8, train_loss: 0.2302 step time: 0.1783
[2022-08-18T00:39:18.535Z] 2/8, train_loss: 0.2095 step time: 0.1393
[2022-08-18T00:39:18.535Z] 3/8, train_loss: 0.1934 step time: 0.1849
[2022-08-18T00:39:18.535Z] 4/8, train_loss: 0.1835 step time: 0.1435
[2022-08-18T00:39:18.535Z] 5/8, train_loss: 0.1650 step time: 0.1421
[2022-08-18T00:39:18.535Z] 6/8, train_loss: 0.1663 step time: 0.1369
[2022-08-18T00:39:18.535Z] 7/8, train_loss: 0.1463 step time: 0.1468
[2022-08-18T00:39:18.535Z] 8/8, train_loss: 0.1378 step time: 0.1058
[2022-08-18T00:39:18.535Z] epoch 5 average loss: 0.1790
[2022-08-18T00:39:18.535Z] epoch: 5 current mean dice: 0.9371, best mean dice: 0.9371
[2022-08-18T00:39:18.535Z] time consuming of epoch 5 is: 3.3944
[2022-08-18T00:39:18.535Z] train completed, best_metric: 0.9371 total time: 18.6376
[2022-08-18T00:39:18.535Z] 
[2022-08-18T00:39:18.535Z] E
[2022-08-18T00:39:18.535Z] ======================================================================
[2022-08-18T00:39:18.535Z] ERROR: test_train_timing (__main__.IntegrationFastTrain)
[2022-08-18T00:39:18.535Z] ----------------------------------------------------------------------
[2022-08-18T00:39:18.535Z] AssertionError: 0.9371276497840881 not greater than 0.95
[2022-08-18T00:39:18.535Z] 
[2022-08-18T00:39:18.535Z] The above exception was the direct cause of the following exception:
[2022-08-18T00:39:18.535Z] 
[2022-08-18T00:39:18.535Z] Traceback (most recent call last):
[2022-08-18T00:39:18.535Z]   File "/home/jenkins/agent/workspace/Monai-latest-image/tests/utils.py", line 596, in _wrapper
[2022-08-18T00:39:18.536Z]     raise RuntimeError(res.traceback) from res
[2022-08-18T00:39:18.536Z] RuntimeError: Traceback (most recent call last):
[2022-08-18T00:39:18.536Z]   File "/home/jenkins/agent/workspace/Monai-latest-image/tests/utils.py", line 547, in run_process
[2022-08-18T00:39:18.536Z]     output = func(*args, **kwargs)
[2022-08-18T00:39:18.536Z]   File "/home/jenkins/agent/workspace/Monai-latest-image/tests/utils.py", line 628, in _call_original_func
[2022-08-18T00:39:18.536Z]     return f(*args, **kwargs)
[2022-08-18T00:39:18.536Z]   File "/home/jenkins/agent/workspace/Monai-latest-image/tests/test_integration_fast_train.py", line 225, in test_train_timing
[2022-08-18T00:39:18.536Z]     self.assertGreater(best_metric, 0.95)
[2022-08-18T00:39:18.536Z]   File "/opt/conda/lib/python3.8/unittest/case.py", line 1310, in assertGreater
[2022-08-18T00:39:18.536Z]     self.fail(self._formatMessage(msg, standardMsg))
[2022-08-18T00:39:18.536Z]   File "/opt/conda/lib/python3.8/unittest/case.py", line 753, in fail
[2022-08-18T00:39:18.536Z]     raise self.failureException(msg)
[2022-08-18T00:39:18.536Z] AssertionError: 0.9371276497840881 not greater than 0.95
[2022-08-18T00:39:18.536Z] 
[2022-08-18T00:39:18.536Z] 
[2022-08-18T00:39:18.536Z] ----------------------------------------------------------------------
```

[log link](https://blossom.nvidia.com/dlmed-clara-jenkins/blue/organizations/jenkins/Monai-latest-image/detail/Monai-latest-image/515/pipeline)

**Comment by wyli** [comment]
couldn't replicate it now
