### ISSUE TITLE
test error tests.test_bundle_verify_net.TestVerifyNetwork

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#4929]
**Describe the bug**

```
[2022-08-18T08:49:08.855Z] ======================================================================
[2022-08-18T08:49:08.855Z] ERROR: test_verify_0__home_jenkins_agent_workspace_MONAI_premerge_monai_tests_testing_data_metadata_json (tests.test_bundle_verify_net.TestVerifyNetwork)
[2022-08-18T08:49:08.855Z] ----------------------------------------------------------------------
[2022-08-18T08:49:08.855Z] Traceback (most recent call last):
[2022-08-18T08:49:08.855Z]   File "/opt/conda/lib/python3.8/site-packages/parameterized/parameterized.py", line 533, in standalone_func
[2022-08-18T08:49:08.855Z]     return func(*(a + p.args), **p.kwargs)
[2022-08-18T08:49:08.855Z]   File "/home/jenkins/agent/workspace/MONAI-premerge/monai/tests/test_bundle_verify_net.py", line 43, in test_verify
[2022-08-18T08:49:08.855Z]     subprocess.check_call(cmd, env=test_env)
[2022-08-18T08:49:08.855Z]   File "/opt/conda/lib/python3.8/subprocess.py", line 364, in check_call
[2022-08-18T08:49:08.855Z]     raise CalledProcessError(retcode, cmd)
[2022-08-18T08:49:08.855Z] subprocess.CalledProcessError: Command '['coverage', 'run', '-m', 'monai.bundle', 'verify_net_in_out', 'network_def', '--meta_file', '/home/jenkins/agent/workspace/MONAI-premerge/monai/tests/testing_data/metadata.json', '--config_file', '/home/jenkins/agent/workspace/MONAI-premerge/monai/tests/testing_data/inference.json', '-n', '4', '--any', '16', '--args_file', '/tmp/tmpqvpuszm0/def_args.json', '--_meta_#network_data_format#inputs#image#spatial_shape', "[16,'*','2**p*n']"]' returned non-zero exit status 1.
[2022-08-18T08:49:08.855Z] 
[2022-08-18T08:49:08.855Z] ----------------------------------------------------------------------
[2022-08-18T08:49:08.855Z] Ran 10099 tests in 1187.059s
[2022-08-18T08:49:08.855Z] 
[2022-08-18T08:49:08.855Z] FAILED (errors=1, skipped=187)
```

from branch https://github.com/Project-MONAI/MONAI/pull/4925 but looks like an irrelevant error to the PR.

[log link](https://blossom.nvidia.com/dlmed-clara-jenkins/blue/organizations/jenkins/MONAI-premerge/detail/MONAI-premerge/1595/pipeline)

**Comment by wyli** [comment]
https://github.com/Project-MONAI/MONAI/pull/4937 improved the output log, please create new tickets if this error occurs again.
