### ISSUE TITLE
RuntimeError: applying transform <monai.transforms.compose.Compose object at 0x7fd33e7bcd60>

### ISSUE THREAD

**Issue by poG515** [Project-MONAI/MONAI#5018]
monai version:0.9.1

epoch 1/50
/opt/conda/lib/python3.8/site-packages/monai/data/utils.py:766: UserWarning: Modifying image pixdim from [1.2000012 0.9375    0.9375    0.       ] to [  1.20000124   0.9375       0.9375     442.02576912]
  warnings.warn(f"Modifying image pixdim from {pixdim} to {norm}")
/opt/conda/lib/python3.8/site-packages/monai/data/utils.py:766: UserWarning: Modifying image pixdim from [1.2000012 0.9375    0.9375    0.       ] to [  1.20000124   0.9375       0.9375     452.94337004]
  warnings.warn(f"Modifying image pixdim from {pixdim} to {norm}")
Traceback (most recent call last):
  File "Densenet_ADvCN.py", line 147, in <module>
    main()
  File "Densenet_ADvCN.py", line 92, in main
    for batch_data in train_loader:
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1347, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1373, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/monai/transforms/transform.py", line 98, in apply_transform
    return _apply_transform(transform, data, unpack_items)
  File "/opt/conda/lib/python3.8/site-packages/monai/transforms/transform.py", line 62, in _apply_transform
    return transform(parameters)
  File "/opt/conda/lib/python3.8/site-packages/monai/transforms/intensity/array.py", line 450, in __call__
    img = convert_to_tensor(img, track_meta=get_track_meta())
TypeError: convert_to_tensor() got an unexpected keyword argument 'track_meta'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.8/site-packages/monai/apps/datasets.py", line 536, in __getitem__
    img = apply_transform(self.transform, img)
  File "/opt/conda/lib/python3.8/site-packages/monai/transforms/transform.py", line 122, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.compose.Compose object at 0x7fd33e7bcd60>

This is my code

    file_x = "/user-data/CN/*/MP-RAGE/*/*/*.nii"
    images_x = glob.glob(file_x)
    file_y = "/user-data/AD/*/MP-RAGE/*/*/*.nii"
    images_y = glob.glob(file_y)

    x1 = round(0.7 * len(images_x))  # num_train_x
    x2 = len(images_x) - x1  # num_val_x
    y1 = round(0.7 * len(images_y))  # num_train_y
    y2 = len(images_y) - y1  # num_val_y

    train_images_x = images_x[:x1]
    val_images_x = images_x[-x2:]

    train_images_y = images_y[:y1]
    val_images_y = images_y[-y2:]

    train_images = train_images_x + train_images_y
    val_images = val_images_x + val_images_y

    train_labels = np.concatenate((np.zeros(x1, dtype=np.int64), np.ones(y1, dtype=np.int64)))
    val_labels = np.concatenate((np.zeros(x2, dtype=np.int64), np.ones(y2, dtype=np.int64)))

    # Define transforms
    train_transforms = Compose([ScaleIntensity(), AsChannelFirst(), Resize((180, 180, 180)), RandRotate90(), EnsureType()])
    val_transforms = Compose([ScaleIntensity(), AsChannelFirst(), Resize((180, 180, 180)), EnsureType()])

    post_pred = Compose([EnsureType(), Activations(softmax=True)])
    post_label = Compose([EnsureType(), AsDiscrete(to_onehot=2)])

    #Define image dataset, data loader
    check_dataset = NiftiDataset(image_files=train_images, labels=train_labels, transform=train_transforms)
    check_loader = DataLoader(check_dataset,  batch_size=2, shuffle=True, num_workers=1, pin_memory=torch.cuda.is_available())
    im, label = monai.utils.misc.first(check_loader)
    print(type(im), im.shape, label)
    os.system("pause")

**Comment by KumoLiu** [comment]
Hi @poG515, `NiftiDataset` had been removed from monai0.5.0, you can confirm it from [CHANGELOG](https://github.com/Project-MONAI/MONAI/blob/dev/CHANGELOG.md). So try to confirm your monai version?

```
from monai.config import print_config
print_config()
```
