### ISSUE TITLE
transformer 4.22.0 causes integration issues

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#5150]
```
The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00,  3.10it/s]
100%|██████████| 1/1 [00:00<00:00,  3.10it/s]
Moving 1 files to the new cache system 2,1
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py", line 217, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
1.13.0a0+d321be6
0 of GPUs available
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py", line 217, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
```

**Comment by wyli** [comment]
log: https://github.com/Project-MONAI/MONAI/actions/runs/3055662238/jobs/4928965598 workaround:  https://github.com/Project-MONAI/MONAI/blob/a1e1af5be768e82061bffa4caf2f5a712dceeed4/requirements-dev.txt#L41

**Comment by Nic-Ma** [comment]
workaround looks good.

Thanks.

**Comment by wyli** [comment]
the root cause is some CLI outputs got returned to system environment variable, I'll try to  create a patch
```bash
/opt/monai# export CUDA_VISIBLE_DEVICES=$(coverage run -m tests.utils)
The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
0it [00:00, ?it/s]

/opt/monai# echo $CUDA_VISIBLE_DEVICES
Moving 0 files to the new cache system output b'61.64, 38, 447\n9.31, 25, 4\n' end 1,0
```
