### ISSUE TITLE
cpp_ext and cuda arch versions

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#5313]
```
01:16:46  ======================================================================
01:16:46  ERROR: test_cuda_1_1_batches_1_dimensions_5_channels_2_classes_1_mixtures (tests.test_gmm.GMMTestCase)
01:16:46  ----------------------------------------------------------------------
01:16:46  Traceback (most recent call last):
01:16:46    File "/opt/conda/lib/python3.8/site-packages/parameterized/parameterized.py", line 533, in standalone_func
01:16:46      return func(*(a + p.args), **p.kwargs)
01:16:46    File "/tmp/tmp.39DiwV78rf/tests/test_gmm.py", line 285, in test_cuda
01:16:46      gmm = GaussianMixtureModel(features_tensor.size(1), mixture_count, class_count, verbose_build=True)
01:16:46    File "/opt/conda/lib/python3.8/site-packages/monai/networks/layers/gmm.py", line 42, in __init__
01:16:46      self.compiled_extension = load_module(
01:16:46    File "/opt/conda/lib/python3.8/site-packages/monai/_extensions/loader.py", line 86, in load_module
01:16:46      module = load(
01:16:46    File "/opt/conda/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1202, in load
01:16:46      return _jit_compile(
01:16:46    File "/opt/conda/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1425, in _jit_compile
01:16:46      _write_ninja_file_and_build_library(
01:16:46    File "/opt/conda/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1524, in _write_ninja_file_and_build_library
01:16:46      _write_ninja_file_to_build_library(
01:16:46    File "/opt/conda/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1922, in _write_ninja_file_to_build_library
01:16:46      cuda_flags = common_cflags + COMMON_NVCC_FLAGS + _get_cuda_arch_flags()
01:16:46    File "/opt/conda/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1707, in _get_cuda_arch_flags
01:16:46      raise ValueError(f"Unknown CUDA arch ({arch}) or GPU not supported")
01:16:46  ValueError: Unknown CUDA arch (9.0+PTX) or GPU not supported
```
the currently supported:
```py
    named_arches = collections.OrderedDict([
        ('Kepler+Tesla', '3.7'),
        ('Kepler', '3.5+PTX'),
        ('Maxwell+Tegra', '5.3'),
        ('Maxwell', '5.0;5.2+PTX'),
        ('Pascal', '6.0;6.1+PTX'),
        ('Volta', '7.0+PTX'),
        ('Turing', '7.5+PTX'),
        ('Ampere', '8.0;8.6+PTX'),
    ])

    supported_arches = ['3.5', '3.7', '5.0', '5.2', '5.3', '6.0', '6.1', '6.2',
                        '7.0', '7.2', '7.5', '8.0', '8.6']
    valid_arch_strings = supported_arches + [s + "+PTX" for s in supported_arches]
```
https://github.com/pytorch/pytorch/blob/v1.12.1/torch/utils/cpp_extension.py#L1654-L1667

**Comment by wyli** [comment]
workaround in blossom config, set env variable `export TORCH_CUDA_ARCH_LIST="7.0;8.0;8.6"` to avoid the unsupported 9.0.
