### ISSUE TITLE
runtests.sh with python 3.10 issue  '_SixMetaPathImporter' object has no attribute 'find_spec'

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#5375]
issue testing with python 3.10
```
[2022-10-21T10:57:44.211Z] + ./runtests.sh --build --quick --unittests
[2022-10-21T10:57:44.768Z] PYTHONPATH: /home/jenkins/agent/workspace/MONAI-postmerge/monai_github:
[2022-10-21T10:57:44.768Z] Python: /usr/bin/python
[2022-10-21T10:57:46.125Z] Traceback (most recent call last):
[2022-10-21T10:57:46.125Z]   File "<frozen importlib._bootstrap>", line 939, in _find_spec
[2022-10-21T10:57:46.125Z] AttributeError: '_SixMetaPathImporter' object has no attribute 'find_spec'
[2022-10-21T10:57:46.125Z] 
[2022-10-21T10:57:46.125Z] During handling of the above exception, another exception occurred:
[2022-10-21T10:57:46.125Z] 
[2022-10-21T10:57:46.125Z] Traceback (most recent call last):
[2022-10-21T10:57:46.125Z]   File "<string>", line 1, in <module>
[2022-10-21T10:57:46.125Z]   File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/__init__.py", line 38, in <module>
[2022-10-21T10:57:46.125Z]     from .utils.module import load_submodules  # noqa: E402
[2022-10-21T10:57:46.125Z]   File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/utils/__init__.py", line 56, in <module>
[2022-10-21T10:57:46.125Z]     from .jupyter_utils import StatusMembers, ThreadContainer
[2022-10-21T10:57:46.125Z]   File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/utils/jupyter_utils.py", line 28, in <module>
[2022-10-21T10:57:46.125Z]     import matplotlib.pyplot as plt
[2022-10-21T10:57:46.125Z]   File "/usr/local/lib/python3.10/dist-packages/matplotlib/pyplot.py", line 60, in <module>
[2022-10-21T10:57:46.125Z]     from matplotlib.figure import Figure, FigureBase, figaspect
[2022-10-21T10:57:46.125Z]   File "/usr/local/lib/python3.10/dist-packages/matplotlib/figure.py", line 26, in <module>
[2022-10-21T10:57:46.125Z]     from matplotlib import _blocking_input, backend_bases, _docstring, projections
[2022-10-21T10:57:46.125Z]   File "/usr/local/lib/python3.10/dist-packages/matplotlib/projections/__init__.py", line 55, in <module>
[2022-10-21T10:57:46.125Z]     from .. import axes, _docstring
[2022-10-21T10:57:46.125Z]   File "/usr/local/lib/python3.10/dist-packages/matplotlib/axes/__init__.py", line 1, in <module>
[2022-10-21T10:57:46.125Z]     from ._subplots import *
[2022-10-21T10:57:46.125Z]   File "/usr/local/lib/python3.10/dist-packages/matplotlib/axes/_subplots.py", line 3, in <module>
[2022-10-21T10:57:46.125Z]     from matplotlib.axes._axes import Axes
[2022-10-21T10:57:46.125Z]   File "/usr/local/lib/python3.10/dist-packages/matplotlib/axes/_axes.py", line 11, in <module>
[2022-10-21T10:57:46.125Z]     import matplotlib.category  # Register category unit converter as side-effect.
[2022-10-21T10:57:46.125Z]   File "/usr/local/lib/python3.10/dist-packages/matplotlib/category.py", line 14, in <module>
[2022-10-21T10:57:46.125Z]     import dateutil.parser
[2022-10-21T10:57:46.125Z]   File "/usr/local/lib/python3.10/dist-packages/dateutil/parser/__init__.py", line 2, in <module>
[2022-10-21T10:57:46.125Z]     from ._parser import parse, parser, parserinfo, ParserError
[2022-10-21T10:57:46.125Z]   File "/usr/local/lib/python3.10/dist-packages/dateutil/parser/_parser.py", line 50, in <module>
[2022-10-21T10:57:46.125Z]     from .. import tz
[2022-10-21T10:57:46.125Z]   File "/usr/local/lib/python3.10/dist-packages/dateutil/tz/__init__.py", line 2, in <module>
[2022-10-21T10:57:46.125Z]     from .tz import *
[2022-10-21T10:57:46.125Z]   File "/usr/local/lib/python3.10/dist-packages/dateutil/tz/tz.py", line 21, in <module>
[2022-10-21T10:57:46.125Z]     from six.moves import _thread
[2022-10-21T10:57:46.125Z]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
[2022-10-21T10:57:46.125Z]   File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
[2022-10-21T10:57:46.125Z]   File "<frozen importlib._bootstrap>", line 941, in _find_spec
[2022-10-21T10:57:46.125Z]   File "<frozen importlib._bootstrap>", line 914, in _find_spec_legacy
[2022-10-21T10:57:46.125Z] ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
```

**Comment by wyli** [comment]
this is addressed by `python -m pip install -U six`
