### ISSUE TITLE
tests for torch 1.13 (and drop support for torch 1.7.x?)

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#5431]
**Is your feature request related to a problem? Please describe.**
- add tests for the new pytorch releases
- drop the tests for v1.7.x?

**Comment by wyli** [comment]
the latest version of torch `pip install torch` is not compatible with cuda 10.2
https://github.com/Project-MONAI/MONAI/blob/766f21f0f68b0594845b9e28fcbde9f84c7572c9/.github/workflows/pythonapp-gpu.yml#L59

```
[2022-10-30T01:19:06.877Z] Python: /usr/bin/python
[2022-10-30T01:19:12.132Z] compile and install
[2022-10-30T01:19:12.132Z] Compiling and installing MONAI cpp extensions...
[2022-10-30T01:19:13.064Z] setup.py with torch 1.13.0+cu117
[2022-10-30T01:19:13.064Z] BUILD_MONAI_CPP=True, BUILD_MONAI_CUDA=True, TORCH_VERSION=11300.
[2022-10-30T01:19:13.064Z] running develop
[2022-10-30T01:19:13.322Z] /usr/local/lib/python3.8/dist-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
[2022-10-30T01:19:13.322Z]   warnings.warn(
[2022-10-30T01:19:13.322Z] /usr/local/lib/python3.8/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
[2022-10-30T01:19:13.322Z]   warnings.warn(
[2022-10-30T01:19:15.850Z] setup.py with torch 1.13.0+cu117
[2022-10-30T01:19:15.850Z] BUILD_MONAI_CPP=True, BUILD_MONAI_CUDA=True, TORCH_VERSION=11300.
[2022-10-30T01:19:15.850Z] running develop
[2022-10-30T01:19:15.850Z] running egg_info
[2022-10-30T01:19:15.850Z] creating monai.egg-info
[2022-10-30T01:19:15.850Z] writing monai.egg-info/PKG-INFO
[2022-10-30T01:19:15.850Z] writing dependency_links to monai.egg-info/dependency_links.txt
[2022-10-30T01:19:15.850Z] writing requirements to monai.egg-info/requires.txt
[2022-10-30T01:19:15.850Z] writing top-level names to monai.egg-info/top_level.txt
[2022-10-30T01:19:15.850Z] writing manifest file 'monai.egg-info/SOURCES.txt'
[2022-10-30T01:19:15.850Z] reading manifest file 'monai.egg-info/SOURCES.txt'
[2022-10-30T01:19:15.850Z] reading manifest template 'MANIFEST.in'
[2022-10-30T01:19:15.850Z] adding license file 'LICENSE'
[2022-10-30T01:19:15.850Z] writing manifest file 'monai.egg-info/SOURCES.txt'
[2022-10-30T01:19:15.850Z] running build_ext
[2022-10-30T01:19:15.850Z] /usr/local/lib/python3.8/dist-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
[2022-10-30T01:19:15.850Z]   warnings.warn(
[2022-10-30T01:19:15.850Z] /usr/local/lib/python3.8/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
[2022-10-30T01:19:15.850Z]   warnings.warn(
[2022-10-30T01:19:15.850Z] Traceback (most recent call last):
[2022-10-30T01:19:15.850Z]   File "setup.py", line 142, in <module>
[2022-10-30T01:19:15.850Z]     setup(
[2022-10-30T01:19:15.850Z]   File "/usr/local/lib/python3.8/dist-packages/setuptools/__init__.py", line 87, in setup
[2022-10-30T01:19:15.850Z]     return distutils.core.setup(**attrs)
[2022-10-30T01:19:15.850Z]   File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/core.py", line 185, in setup
[2022-10-30T01:19:15.850Z]     return run_commands(dist)
[2022-10-30T01:19:15.850Z]   File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
[2022-10-30T01:19:15.850Z]     dist.run_commands()
[2022-10-30T01:19:15.850Z]   File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 968, in run_commands
[2022-10-30T01:19:15.850Z]     self.run_command(cmd)
[2022-10-30T01:19:15.850Z]   File "/usr/local/lib/python3.8/dist-packages/setuptools/dist.py", line 1217, in run_command
[2022-10-30T01:19:15.850Z]     super().run_command(command)
[2022-10-30T01:19:15.850Z]   File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 987, in run_command
[2022-10-30T01:19:15.851Z]     cmd_obj.run()
[2022-10-30T01:19:15.851Z]   File "/usr/local/lib/python3.8/dist-packages/setuptools/command/develop.py", line 34, in run
[2022-10-30T01:19:15.851Z]     self.install_for_development()
[2022-10-30T01:19:15.851Z]   File "/usr/local/lib/python3.8/dist-packages/setuptools/command/develop.py", line 114, in install_for_development
[2022-10-30T01:19:15.851Z]     self.run_command('build_ext')
[2022-10-30T01:19:15.851Z]   File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/cmd.py", line 319, in run_command
[2022-10-30T01:19:15.851Z]     self.distribution.run_command(command)
[2022-10-30T01:19:15.851Z]   File "/usr/local/lib/python3.8/dist-packages/setuptools/dist.py", line 1217, in run_command
[2022-10-30T01:19:15.851Z]     super().run_command(command)
[2022-10-30T01:19:15.851Z]   File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 987, in run_command
[2022-10-30T01:19:15.851Z]     cmd_obj.run()
[2022-10-30T01:19:15.851Z]   File "/usr/local/lib/python3.8/dist-packages/setuptools/command/build_ext.py", line 84, in run
[2022-10-30T01:19:15.851Z]     _build_ext.run(self)
[2022-10-30T01:19:15.851Z]   File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
[2022-10-30T01:19:15.851Z]     self.build_extensions()
[2022-10-30T01:19:15.851Z]   File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 499, in build_extensions
[2022-10-30T01:19:15.851Z]     _check_cuda_version(compiler_name, compiler_version)
[2022-10-30T01:19:15.851Z]   File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 386, in _check_cuda_version
[2022-10-30T01:19:15.851Z]     raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
[2022-10-30T01:19:15.851Z] RuntimeError: 
[2022-10-30T01:19:15.851Z] The detected CUDA version (10.2) mismatches the version that was used to compile
[2022-10-30T01:19:15.851Z] PyTorch (11.7). Please make sure to use the same CUDA versions.
```

**Comment by wyli** [comment]
> deprecated CUDA 10.2 and 11.3 and completed migration of CUDA 11.6 and 11.7

since pytorch 1.13, CI/CD are migrated to cuda 11.6/11.7 https://pytorch.org/blog/PyTorch-1.13-release/

I think we should also do the migration, mainly to review the base image's cuda versions:
https://github.com/Project-MONAI/MONAI/blob/766f21f0f68b0594845b9e28fcbde9f84c7572c9/.github/workflows/setupapp.yml#L24

https://github.com/Project-MONAI/MONAI/blob/766f21f0f68b0594845b9e28fcbde9f84c7572c9/.github/workflows/pythonapp-gpu.yml#L34

this probably requires confirming the github and blossom runner's gpu driver versions
cc @Nic-Ma @YanxuanLiu @pxLi

**Comment by YanxuanLiu** [comment]
should we reserve 10.2 for 1.12 and early version of pt?

**Comment by wyli** [comment]
> should we reserve 10.2 for 1.12 and early version of pt?

good question, I was checking this earlier, I think cuda 10.2 is supported by all the pytorch versions before 1.13. so, maybe it's good to support 10.2, unless we have gpu driver issues for supporting both 10.x and 11.x

**Comment by YanxuanLiu** [comment]
for [MONAI/.github/workflows/pythonapp-gpu.yml](https://github.com/Project-MONAI/MONAI/blob/766f21f0f68b0594845b9e28fcbde9f84c7572c9/.github/workflows/pythonapp-gpu.yml#L34)
```
- environment: PT112+CUDA117
            # we explicitly set pytorch to -h to avoid pip install error
            # 22.08: 1.13.0a0+d321be6
            pytorch: "-h"
            base: "nvcr.io/nvidia/pytorch:22.08-py3"
```
The cuda version in this image is 11.7, you can use this image for Pytorch 1.13 and later versions.

for [MONAI/.github/workflows/setupapp.yml](https://github.com/Project-MONAI/MONAI/blob/766f21f0f68b0594845b9e28fcbde9f84c7572c9/.github/workflows/setupapp.yml#L24)
for job `coverage-py`, we can update the image when we update pytorch version to 1.13

**Comment by wyli** [comment]
sure, I also tested `nvcr.io/nvidia/cuda:11.6.1-devel-ubuntu18.04` works fine with 1.13 and this script https://github.com/Project-MONAI/MONAI/blob/766f21f0f68b0594845b9e28fcbde9f84c7572c9/.github/workflows/pythonapp-gpu.yml#L76-L112

(both ubuntu18.04 and python 3.7 are deprecating next year though)
