### ISSUE TITLE
logging file should be optional in Bundle command instead erroring out 

### ISSUE THREAD

**Issue by AHarouni** [Project-MONAI/MONAI#5453]
running any bundle command with the wrong bundle log file would error with unclear cause 

**To Reproduce**
```
python -m monai.bundle run training --meta_file metadata.json --config_file train.json --logging_file /Nologginfile_logging.conf 
```
you would get errors below 
```
2022-09-07 15:53:00,279 - INFO - --- input summary of monai.bundle.scripts.run --- 

2022-09-07 15:53:00,279 - INFO - > runner_id: 'training' 

2022-09-07 15:53:00,279 - INFO - > meta_file: '/metadata.json' 

2022-09-07 15:53:00,279 - INFO - > config_file: '/train.json' 

2022-09-07 15:53:00,279 - INFO - > logging_file: '/logging.conf' 

2022-09-07 15:53:00,279 - INFO - --- 

2022-09-07 15:53:00,279 - INFO - set logging properties based on config: /logging.conf. 

Traceback (most recent call last): 

  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main 

    return _run_code(code, main_globals, None, 

  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code 

    exec(code, run_globals) 

  File "/opt/monai/monai/bundle/__main__.py", line 19, in <module> 

    fire.Fire() 

  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 141, in Fire 

    component_trace = _Fire(component, args, parsed_flag_args, context, name) 

  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire 

    component, remaining_args = _CallAndUpdateTrace( 

  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace 

    component = fn(*varargs, **kwargs) 

  File "/opt/monai/monai/bundle/scripts.py", line 367, in run 

    fileConfig(logging_file_, disable_existing_loggers=False) 

  File "/opt/conda/lib/python3.8/logging/config.py", line 71, in fileConfig 

    formatters = _create_formatters(cp) 

  File "/opt/conda/lib/python3.8/logging/config.py", line 104, in _create_formatters 

    flist = cp["formatters"]["keys"] 

  File "/opt/conda/lib/python3.8/configparser.py", line 960, in __getitem__ 

    raise KeyError(key) 

KeyError: 'formatters
```
**Expected behavior**
- code should check on all files and give clear message if they don't exist 
- I think logging should be optional, advanced users can add it when they need to debug

**Comment by Nic-Ma** [comment]
Hi @AHarouni ,

Thanks for your feedback.
I think we have the check for the file exists: https://github.com/Project-MONAI/MONAI/blob/dev/monai/bundle/scripts.py#L533
And it's certainly optional, you can leave it to None if you don't want to see logging.

Thanks.
