### ISSUE TITLE
tests.test_sampler_dist -- windows

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#5501]
log: https://github.com/Project-MONAI/MONAI/actions/runs/3429344900/jobs/5714838305

```
test_cachedataset (tests.test_sampler_dist.DistributedSamplerTest) ... torch.testing.assert_allclose() is deprecated since 1.12 and will be removed in 1.14. Use torch.testing.assert_close() instead. For detailed upgrade instructions see https://github.com/pytorch/pytorch/issues/61844.
torch.testing.assert_allclose() is deprecated since 1.12 and will be removed in 1.14. Use torch.testing.assert_close() instead. For detailed upgrade instructions see https://github.com/pytorch/pytorch/issues/61844.
Process SpawnProcess-157:
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\a\MONAI\MONAI\tests\utils.py", line 475, in run_process
    raise e
  File "D:\a\MONAI\MONAI\tests\utils.py", line 466, in run_process
    func(*args, **kwargs)
  File "D:\a\MONAI\MONAI\tests\utils.py", line 634, in _call_original_func
    return f(*args, **kwargs)
  File "D:\a\MONAI\MONAI\tests\test_sampler_dist.py", line 61, in test_cachedataset
    for k, d in enumerate(dataloader):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\torch\utils\data\dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\torch\utils\data\dataloader.py", line 1359, in _process_data
    data.reraise()
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\torch\_utils.py", line 543, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\multiprocessing\managers.py", line 827, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\a\MONAI\MONAI\monai\data\dataset.py", line 107, in __getitem__
    return self._transform(index)
  File "D:\a\MONAI\MONAI\monai\data\dataset.py", line 908, in _transform
    data = self._cache[cache_index]
  File "<string>", line 2, in __getitem__
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\multiprocessing\managers.py", line 831, in _callmethod
    self._connect()
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\multiprocessing\managers.py", line 818, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\multiprocessing\connection.py", line 500, in Client
    c = PipeClient(address)
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\multiprocessing\connection.py", line 702, in PipeClient
    _winapi.WaitNamedPipe(address, 1000)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by wyli** [comment]
https://github.com/Project-MONAI/MONAI/pull/5494 included a patch
