### ISSUE TITLE
Failing unit test : tests/test_integration_segmentation_3d.py

### ISSUE THREAD

**Issue by myron** [Project-MONAI/MONAI#5619]
One of the integration tests always fails for me:
 
 **tests/test_integration_segmentation_3d.py**

I tried both on main and dev branches. Is it expected?  @wyli @Nic-Ma 
thanks 
 

```
2022-11-30 23:04:53,064 INFO image_writer.py:193 - writing: /tmp/tmpq5rhetob/output/img7/img7_seg.nii.gz                                                      
2022-11-30 23:04:53,274 INFO image_writer.py:193 - writing: /tmp/tmpq5rhetob/output/img8/img8_seg.nii.gz                                                      
2022-11-30 23:04:53,488 INFO image_writer.py:193 - writing: /tmp/tmpq5rhetob/output/img9/img9_seg.nii.gz                                                      
losses [0.5451198399066925, 0.47095481753349305, 0.452019140124321, 0.4443228721618652, 0.43412517607212064, 0.43511083722114563]                             
best metric 0.9301624298095703                                                                                                                                
infer metric 0.9300851821899414                                                                                                                               
[0.1430950958895707, 0.15311301883488881, 0.1524822533393576, 0.1404460392052536, 0.18908918112383785, 0.17044005481857102, 0.147810057840978, 0.1691574540634
4576, 0.15809960619944452, 0.18031834244391975, 0.1635822398289536, 0.16889806360181064, 0.1452261554513099, 0.11459416963010247, 0.16264445363099517, 0.20183
162324572904, 0.176806380817086, 0.09871156366459519, 0.19462697726547584, 0.2039081051499176, 0.19706409643211958, 0.20916774261696144, 0.16295310416089434, 
0.13284166561370975, 0.14878046924608998, 0.14348626052381575, 0.23209682552446892, 0.16174730382345734, 0.14935701688978129, 0.10347741305261388, 0.119612649
91568968, 0.130434868578445, 0.11480659702374629, 0.15295821742863722, 0.1639103215354819, 0.19465812146109684, 0.22346557217899304, 0.18167824186854253, 0.19
105603590639497, 0.07527836019812181]                                                                                                                         
E
======================================================================
ERROR: test_timing (__main__.IntegrationSegmentation3D)
----------------------------------------------------------------------
ValueError: no matched results for integration_segmentation_3d, losses. [0.5451198399066925, 0.47095481753349305, 0.452019140124321, 0.4443228721618652, 0.434
12517607212064, 0.43511083722114563].

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/amproj/Code/MONAI/tests/utils.py", line 601, in _wrapper
    raise RuntimeError(res.traceback) from res
RuntimeError: Traceback (most recent call last):
  File "/mnt/amproj/Code/MONAI/tests/utils.py", line 552, in run_process
    output = func(*args, **kwargs)
  File "/mnt/amproj/Code/MONAI/tests/utils.py", line 633, in _call_original_func
    return f(*args, **kwargs)
  File "/mnt/amproj/Code/MONAI/tests/test_integration_segmentation_3d.py", line 298, in test_timing
    self.train_and_infer(idx=3)
  File "/mnt/amproj/Code/MONAI/tests/test_integration_segmentation_3d.py", line 281, in train_and_infer
    self.assertTrue(test_integration_value(TASK, key="losses", data=results[:6], rtol=1e-3))
  File "/mnt/amproj/Code/MONAI/tests/testing_data/integration_answers.py", line 596, in test_integration_value
    raise ValueError(f"no matched results for {test_name}, {key}. {data}.")
ValueError: no matched results for integration_segmentation_3d, losses. [0.5451198399066925, 0.47095481753349305, 0.452019140124321, 0.4443228721618652, 0.434
12517607212064, 0.43511083722114563].


======================================================================
ERROR: test_training (__main__.IntegrationSegmentation3D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_integration_segmentation_3d.py", line 290, in test_training
    results = self.train_and_infer(i)
  File "tests/test_integration_segmentation_3d.py", line 281, in train_and_infer
    self.assertTrue(test_integration_value(TASK, key="losses", data=results[:6], rtol=1e-3))
  File "/mnt/amproj/Code/MONAI/tests/testing_data/integration_answers.py", line 596, in test_integration_value
    raise ValueError(f"no matched results for {test_name}, {key}. {data}.")
ValueError: no matched results for integration_segmentation_3d, losses. [0.5451198399066925, 0.47095481753349305, 0.452019140124321, 0.4443228721618652, 0.434
12517607212064, 0.43511083722114563].
----------------------------------------------------------------------
Ran 2 tests in 136.962s

FAILED (errors=2)
```

```
nvidia/pytorch:22.11 (ubuntu 2xgpu machine)

Numpy version: 1.22.2
Pytorch version: 1.13.0a0+936e930
MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
MONAI rev id: 8271a193229fe4437026185e218d5b06f7c8ce69
MONAI __file__: /mnt/amproj/Code/MONAI/monai/__init__.py

Optional dependencies:
Pytorch Ignite version: 0.4.10
Nibabel version: 4.0.2
scikit-image version: 0.19.3
Pillow version: 9.0.1
Tensorboard version: 2.9.0
gdown version: 4.5.4
TorchVision version: 0.15.0a0
tqdm version: 4.64.1
lmdb version: 1.3.0
psutil version: 5.9.4
pandas version: 1.4.4
einops version: 0.6.0
transformers version: 4.21.3
mlflow version: 2.0.1
pynrrd version: 1.0.0
```

**Comment by wyli** [comment]
that's 22.11, the ci is currently at 22.10

**Comment by myron** [comment]
hmm, so I tried to start a docker **nvidia/pytorch:22.10**, 
then installed dependencies
`python -m pip install -U -r requirements-dev.txt`

clone monai, dev branch: this test Fails with the same error

--

but when using docker **projectmonai/monai:latest**
clone monai, dev branch, this test runs ok without issues

I'll close it, if there are no other insights...
