### ISSUE TITLE
conda test oom

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#5625]
https://github.com/Project-MONAI/MONAI/actions/runs/3589162575/jobs/6047020767
```
======================================================================
ERROR: test_spacing_17 (tests.test_spacing.TestSpacingCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda\envs\monai\lib\site-packages\parameterized\parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "d:\a\monai\monai\tests\test_spacing.py", line 268, in test_spacing
    res: MetaTensor = Spacing(**init_param)(img, **data_param)
  File "d:\a\monai\monai\monai\utils\deprecate_utils.py", line 221, in _wrapper
    return func(*args, **kwargs)
  File "d:\a\monai\monai\monai\transforms\spatial\array.py", line 606, in __call__
    data_array = self.sp_resample(
  File "d:\a\monai\monai\monai\utils\deprecate_utils.py", line 221, in _wrapper
    return func(*args, **kwargs)
  File "d:\a\monai\monai\monai\transforms\spatial\array.py", line 315, in __call__
    img = affine_xform(img.unsqueeze(0), theta=xform, spatial_size=spatial_size).squeeze(0)
  File "C:\Miniconda\envs\monai\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "d:\a\monai\monai\monai\networks\layers\spatial_transforms.py", line 575, in forward
    grid = nn.functional.affine_grid(theta=theta[:, :sr], size=list(dst_size), align_corners=self.align_corners)
  File "C:\Miniconda\envs\monai\lib\site-packages\torch\nn\functional.py", line 4332, in affine_grid
    return torch.affine_grid_generator(theta, size, align_corners)
RuntimeError: [enforce fail at C:\cb\pytorch_1000000000000\work\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 879204144 bytes.
```

**Comment by wyli** [comment]
skipped for quick tests https://github.com/Project-MONAI/MONAI/pull/5606/commits/9c5593f62ec599f0a1883200ca1f251181b6ae43
