### ISSUE TITLE
upgrade base image to 22.11 or newer

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#5779]
would be great to use a more recent base image than the current 22.10:
https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch/tags

once this ticket is done, #5777 should be verified and closed as that's an issue with pytorch 22.10.

cc @Nic-Ma @YanxuanLiu

**Comment by wyli** [comment]
22.12 compatibility issue

```
[2023-01-04T09:56:18.647Z] ======================================================================
[2023-01-04T09:56:18.647Z] ERROR: test_consistency_0 (tests.test_dynunet.TestDynUNetWithInstanceNorm3dNVFuser)
[2023-01-04T09:56:18.647Z] ----------------------------------------------------------------------
[2023-01-04T09:56:18.647Z] Traceback (most recent call last):
[2023-01-04T09:56:18.647Z]   File "/usr/local/lib/python3.8/dist-packages/parameterized/parameterized.py", line 533, in standalone_func
[2023-01-04T09:56:18.647Z]     return func(*(a + p.args), **p.kwargs)
[2023-01-04T09:56:18.647Z]   File "/home/jenkins/agent/workspace/Monai-latest-image/tests/test_dynunet.py", line 144, in test_consistency
[2023-01-04T09:56:18.647Z]     result_fuser = net_fuser(input_tensor)
[2023-01-04T09:56:18.647Z]   File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1423, in _call_impl
[2023-01-04T09:56:18.647Z]     return forward_call(*input, **kwargs)
[2023-01-04T09:56:18.647Z]   File "/home/jenkins/agent/workspace/Monai-latest-image/monai/networks/nets/dynunet.py", line 267, in forward
[2023-01-04T09:56:18.647Z]     out = self.skip_layers(x)
[2023-01-04T09:56:18.647Z]   File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1423, in _call_impl
[2023-01-04T09:56:18.647Z]     return forward_call(*input, **kwargs)
[2023-01-04T09:56:18.647Z]   File "/home/jenkins/agent/workspace/Monai-latest-image/monai/networks/nets/dynunet.py", line 46, in forward
[2023-01-04T09:56:18.647Z]     nextout = self.next_layer(downout)
[2023-01-04T09:56:18.647Z]   File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1423, in _call_impl
[2023-01-04T09:56:18.647Z]     return forward_call(*input, **kwargs)
[2023-01-04T09:56:18.647Z]   File "/home/jenkins/agent/workspace/Monai-latest-image/monai/networks/nets/dynunet.py", line 45, in forward
[2023-01-04T09:56:18.647Z]     downout = self.downsample(x)
[2023-01-04T09:56:18.647Z]   File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1423, in _call_impl
[2023-01-04T09:56:18.647Z]     return forward_call(*input, **kwargs)
[2023-01-04T09:56:18.647Z]   File "/home/jenkins/agent/workspace/Monai-latest-image/monai/networks/blocks/dynunet_block.py", line 99, in forward
[2023-01-04T09:56:18.647Z]     out = self.norm1(out)
[2023-01-04T09:56:18.647Z]   File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1423, in _call_impl
[2023-01-04T09:56:18.647Z]     return forward_call(*input, **kwargs)
[2023-01-04T09:56:18.647Z]   File "/usr/local/lib/python3.8/dist-packages/apex/normalization/instance_norm.py", line 138, in forward
[2023-01-04T09:56:18.647Z]     out = InstanceNormNVFuserFunction.apply(
[2023-01-04T09:56:18.647Z]   File "/usr/local/lib/python3.8/dist-packages/apex/normalization/instance_norm.py", line 25, in forward
[2023-01-04T09:56:18.647Z]     result = instance_norm_nvfuser_cuda.forward(_input, weight, bias, running_mean, running_var,
[2023-01-04T09:56:18.647Z] RuntimeError: !mismatch INTERNAL ASSERT FAILED at "/opt/pytorch/pytorch/torch/csrc/jit/codegen/cuda/executor_utils.cpp":388, please report a bug to PyTorch. Found one or more invalid arguments: Argument is scalar type, but kernel parameter is not
[2023-01-04T09:56:18.647Z] Argument is scalar type, but kernel parameter is not
[2023-01-04T09:56:18.647Z] 
[2023-01-04T09:56:18.647Z] 
[2023-01-04T09:56:18.647Z] ----------------------------------------------------------------------
```

**Comment by Nic-Ma** [comment]
Hi @yiheng-wang-nv ,

Do you have any idea about this 22.12 issue?

Thanks in advance.

**Comment by yiheng-wang-nv** [comment]
I tried to reproduce the issue with the following code:
```
from monai.utils import look_up_option, optional_import

InstanceNorm3dNVFuser, has_nvfuser = optional_import("apex.normalization", name="InstanceNorm3dNVFuser")
layer = InstanceNorm3dNVFuser(num_features=16, affine=True).to("cuda:0")
layer(torch.randn((1, 16, 8, 8, 8)).to("cuda:0"))
```
When `affine=False` or if increasing input size to `(1, 16, 16, 8, 8)` no error happen

**Comment by yiheng-wang-nv** [comment]
This module is available in: https://github.com/NVIDIA/apex/blob/22.12-dev/apex/normalization/instance_norm.py
Let me raise the issue in the apex side.

**Comment by yiheng-wang-nv** [comment]
> This module is available in: https://github.com/NVIDIA/apex/blob/22.12-dev/apex/normalization/instance_norm.py Let me raise the issue in the apex side.

See: https://github.com/NVIDIA/apex/issues/1562
