### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy.typing'

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#5952]
**Describe the bug**
```
[2023-02-06T23:22:07.279Z] + bash runtests.sh --clean
[2023-02-06T23:22:08.211Z] PYTHONPATH: /home/jenkins/agent/workspace/Monai-pip/monai:
[2023-02-06T23:22:08.211Z] Python: /opt/conda/bin/python
[2023-02-06T23:22:11.481Z] Traceback (most recent call last):
[2023-02-06T23:22:11.482Z]   File "/home/jenkins/agent/workspace/Monai-pip/monai/monai/utils/module.py", line 209, in load_submodules
[2023-02-06T23:22:11.482Z]     mod = import_module(name)
[2023-02-06T23:22:11.482Z]   File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
[2023-02-06T23:22:11.482Z]     return _bootstrap._gcd_import(name[level:], package, level)
[2023-02-06T23:22:11.482Z]   File "/home/jenkins/agent/workspace/Monai-pip/monai/monai/apps/pathology/__init__.py", line 16, in <module>
[2023-02-06T23:22:11.482Z]     from .losses import HoVerNetLoss
[2023-02-06T23:22:11.482Z]   File "/home/jenkins/agent/workspace/Monai-pip/monai/monai/apps/pathology/losses/__init__.py", line 14, in <module>
[2023-02-06T23:22:11.482Z]     from .hovernet_loss import HoVerNetLoss
[2023-02-06T23:22:11.482Z]   File "/home/jenkins/agent/workspace/Monai-pip/monai/monai/apps/pathology/losses/hovernet_loss.py", line 19, in <module>
[2023-02-06T23:22:11.482Z]     from monai.losses import DiceLoss
[2023-02-06T23:22:11.482Z]   File "/home/jenkins/agent/workspace/Monai-pip/monai/monai/losses/__init__.py", line 37, in <module>
[2023-02-06T23:22:11.482Z]     from .ssim_loss import SSIMLoss
[2023-02-06T23:22:11.482Z]   File "/home/jenkins/agent/workspace/Monai-pip/monai/monai/losses/ssim_loss.py", line 17, in <module>
[2023-02-06T23:22:11.482Z]     from monai.metrics.regression import SSIMMetric
[2023-02-06T23:22:11.482Z]   File "/home/jenkins/agent/workspace/Monai-pip/monai/monai/metrics/__init__.py", line 27, in <module>
[2023-02-06T23:22:11.482Z]     from .rocauc import ROCAUCMetric, compute_roc_auc
[2023-02-06T23:22:11.482Z]   File "/home/jenkins/agent/workspace/Monai-pip/monai/monai/metrics/rocauc.py", line 18, in <module>
[2023-02-06T23:22:11.482Z]     import numpy.typing as npt
[2023-02-06T23:22:11.482Z] ModuleNotFoundError: No module named 'numpy.typing'
```

tests with numpy 1.19.2, base image 21.02

**Comment by wyli** [comment]
updated the requirements to include `numpy.typing` https://github.com/Project-MONAI/MONAI/pull/5949/commits/bdcb1045e34488b6bc7ad98473712920010646ab
