### ISSUE TITLE
Getting the wrong shape in training when pixelshuffle in FlexibleUNet

### ISSUE THREAD

**Issue by JohnMasoner** [Project-MONAI/MONAI#5971]
**Describe the bug**
I get an error shape in the decoder When I use A for training,.

**To Reproduce**

```python
import torch
from monai.networks.nets import BasicUNetPlusPlus, FlexibleUNet

model1 = FlexibleUNet(1, 1, backbone='efficientnet-b8',upsample = 'pixelshuffle')
x = torch.randn(2, 1, 512, 512, requires_grad=True)
torch_out = model1(x)
```

```shell
Traceback (most recent call last):
  File "torch2.py", line 8, in <module>
    torch_out = model1(x)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xxx/.local/lib/python3.7/site-packages/monai/networks/nets/flexible_unet.py", line 337, in forward
    decoder_out = self.decoder(enc_out, self.skip_connect)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xxx/.local/lib/python3.7/site-packages/monai/networks/nets/flexible_unet.py", line 166, in forward
    x = block(x, skip)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xxx/.local/lib/python3.7/site-packages/monai/networks/nets/basic_unet.py", line 168, in forward
    x = self.convs(torch.cat([x_e, x_0], dim=1))  # input channels: (cat_chns + up_chns)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 454, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [256, 1168, 3, 3], expected input[2, 824, 32, 32] to have 1168 channels, but got 824 channels instead
```

**Expected behavior**

**Environment**

Ensuring you use the relevant python executable, please paste the output of:

```shell
python -c 'import monai; monai.config.print_debug_info()'

================================
Printing MONAI config...
================================
MONAI version: 1.1.0
Numpy version: 1.21.6
Pytorch version: 1.12.1+cu116
MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
MONAI rev id: a2ec3752f54bfc3b40e7952234fbeb5452ed63e3
MONAI __file__: /home/xxx/.local/lib/python3.7/site-packages/monai/__init__.py

Optional dependencies:
Pytorch Ignite version: 0.4.9
Nibabel version: 3.2.1
scikit-image version: 0.19.3
Pillow version: 8.1.0
Tensorboard version: 2.9.1
gdown version: 4.5.1
TorchVision version: 0.8.2
tqdm version: 4.64.0
lmdb version: 1.3.0
psutil version: 5.4.7
pandas version: 0.23.4
einops version: 0.3.2
transformers version: 4.21.2
mlflow version: 1.28.0
pynrrd version: 0.4.3

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies


================================
Printing system config...
================================
System: Linux
Linux version: Ubuntu 18.04.6 LTS
Platform: Linux-4.15.0-166-generic-x86_64-with-debian-buster-sid
Processor: x86_64
Machine: x86_64
Python version: 3.7.2
Process name: python
Command: ['python', '-c', 'import monai; monai.config.print_debug_info()']
Open files: []
Num physical CPUs: 24
Num logical CPUs: 48
Num usable CPUs: 48
CPU usage (%): [6.2, 4.9, 21.3, 4.2, 5.1, 5.1, 4.9, 4.2, 3.9, 80.1, 5.4, 4.9, 7.9, 0.2, 9.1, 12.3, 4.2, 6.9, 0.5, 8.9, 0.7, 41.2, 0.0, 0.2, 3.0, 3.7, 81.1, 4.9, 5.4, 4.7, 4.9, 4.2, 23.3, 3.7, 5.4, 5.2, 0.2, 29.9, 0.2, 0.0, 0.0, 4.4, 0.2, 0.0, 70.1, 0.2, 0.0, 0.5]
CPU freq. (MHz): 1575
Load avg. in last 1, 5, 15 mins (%): UNKNOWN for given OS
Disk usage (%): 46.3
Avg. sensor temp. (Celsius): UNKNOWN for given OS
Total physical memory (GB): 125.8
Available memory (GB): 111.1
Used memory (GB): 13.6

================================
Printing GPU config...
================================
Num GPUs: 5
Has CUDA: True
CUDA version: 11.6
cuDNN enabled: True
cuDNN version: 8302
Current device: 0
Library compiled for CUDA architectures: ['sm_37', 'sm_50', 'sm_60', 'sm_70', 'sm_75', 'sm_80', 'sm_86']
GPU 0 Name: NVIDIA GeForce RTX 3090
GPU 0 Is integrated: False
GPU 0 Is multi GPU board: False
GPU 0 Multi processor count: 82
GPU 0 Total memory (GB): 23.7
GPU 0 CUDA capability (maj.min): 8.6
GPU 1 Name: NVIDIA GeForce RTX 3090
GPU 1 Is integrated: False
GPU 1 Is multi GPU board: False
GPU 1 Multi processor count: 82
GPU 1 Total memory (GB): 23.7
GPU 1 CUDA capability (maj.min): 8.6
GPU 2 Name: NVIDIA GeForce RTX 3090
GPU 2 Is integrated: False
GPU 2 Is multi GPU board: False
GPU 2 Multi processor count: 82
GPU 2 Total memory (GB): 23.7
GPU 2 CUDA capability (maj.min): 8.6
GPU 3 Name: NVIDIA GeForce RTX 3090
GPU 3 Is integrated: False
GPU 3 Is multi GPU board: False
GPU 3 Multi processor count: 82
GPU 3 Total memory (GB): 23.7
GPU 3 CUDA capability (maj.min): 8.6
GPU 4 Name: NVIDIA GeForce RTX 3090
GPU 4 Is integrated: False
GPU 4 Is multi GPU board: False
GPU 4 Multi processor count: 82
GPU 4 Total memory (GB): 23.7
GPU 4 CUDA capability (maj.min): 8.6

```

**Additional context**

**Comment by Nic-Ma** [comment]
Hi @binliunls ,

Could you please help take a look at this question?

Thanks in advance.
