### ISSUE TITLE
integration errors

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#6149]
**Describe the bug**
some version dependent integration errors
```
[2023-03-15T05:40:29.871Z] ======================================================================
[2023-03-15T05:40:29.871Z] FAIL: test_bspline (tests.test_global_mutual_information_loss.TestGlobalMutualInformationLoss)
[2023-03-15T05:40:29.871Z] ----------------------------------------------------------------------
[2023-03-15T05:40:29.871Z] Traceback (most recent call last):
[2023-03-15T05:40:29.871Z]   File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/tests/test_global_mutual_information_loss.py", line 109, in test_bspline
[2023-03-15T05:40:29.871Z]     np.testing.assert_allclose(result, expected_value, rtol=1e-3, atol=5e-3)
[2023-03-15T05:40:29.871Z]   File "/opt/conda/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 1530, in assert_allclose
[2023-03-15T05:40:29.871Z]     assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
[2023-03-15T05:40:29.871Z]   File "/opt/conda/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
[2023-03-15T05:40:29.871Z]     raise AssertionError(msg)
[2023-03-15T05:40:29.871Z] AssertionError: 
[2023-03-15T05:40:29.871Z] Not equal to tolerance rtol=0.001, atol=0.005
[2023-03-15T05:40:29.871Z] 
[2023-03-15T05:40:29.871Z] Mismatched elements: 1 / 1 (100%)
[2023-03-15T05:40:29.871Z] Max absolute difference: 0.028
[2023-03-15T05:40:29.871Z] Max relative difference: 0.045
[2023-03-15T05:40:29.871Z]  x: array(-0.596109, dtype=float32)
[2023-03-15T05:40:29.871Z]  y: array(-0.624335)
[2023-03-15T05:40:29.871Z] 
[2023-03-15T05:40:29.871Z] ----------------------------------------------------------------------
[2023-03-15T05:40:29.871Z] Ran 12322 tests in 2105.197s
[2023-03-15T05:40:29.871Z] 
[2023-03-15T05:40:29.871Z] FAILED (failures=1, skipped=116)
```

```
[2023-03-15T03:06:38.969Z] ======================================================================
[2023-03-15T03:06:38.969Z] FAIL: test_correct_results_11 (tests.test_rand_rotated.TestRandRotated2D)
[2023-03-15T03:06:38.969Z] ----------------------------------------------------------------------
[2023-03-15T03:06:38.969Z] Traceback (most recent call last):
[2023-03-15T03:06:38.969Z]   File "/usr/local/lib/python3.10/dist-packages/parameterized/parameterized.py", line 533, in standalone_func
[2023-03-15T03:06:38.969Z]     return func(*(a + p.args), **p.kwargs)
[2023-03-15T03:06:38.969Z]   File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/tests/test_rand_rotated.py", line 149, in test_correct_results
[2023-03-15T03:06:38.969Z]     self.assertLessEqual(np.abs(good - expected.size), 25, "diff at most 25 pixels")
[2023-03-15T03:06:38.969Z] AssertionError: 26 not less than or equal to 25 : diff at most 25 pixels
[2023-03-15T03:06:38.969Z] 
[2023-03-15T03:06:38.969Z] ----------------------------------------------------------------------
[2023-03-15T03:06:38.969Z] Ran 10030 tests in 1044.933s
[2023-03-15T03:06:38.969Z] 
[2023-03-15T03:06:38.969Z] FAILED (failures=1, skipped=807)
```

**Comment by wyli** [comment]
the default padding option `reflection` tends to generate significant differences when the coordinates change by a tiny value, `padding_mode=border` results are more robust, but these are not API bugs

abs diff
![Screenshot 2023-03-15 at 10 24 33](https://user-images.githubusercontent.com/831580/225281093-1945d1e8-42e6-4d43-bed5-de11afa8faff.png)

![Screenshot 2023-03-15 at 10 27 21](https://user-images.githubusercontent.com/831580/225281756-2e7dcc44-77eb-418e-9eb1-29254329bcaa.png)
