### ISSUE TITLE
Data Analyzer writes `null` for all by_cases result in datastats.yaml

### ISSUE THREAD

**Issue by mingxin-zheng** [Project-MONAI/MONAI#6205]
**Describe the bug**

**To Reproduce**
Run the following script, and it will generate `null` cases
```python
import os
from monai.data import create_test_image_3d
import nibabel as nib
from monai.bundle.config_parser import ConfigParser
import numpy as np
from monai.apps.auto3dseg import DataAnalyzer

fake_datalist: dict[str, list[dict]] = {
    "testing": [{"image": "val_001.fake.nii.gz"}, {"image": "val_002.fake.nii.gz"}],
    "training": [
        {"fold": 0, "image": "tr_image_001.fake.nii.gz", "label": "tr_label_001.fake.nii.gz"},
        {"fold": 0, "image": "tr_image_002.fake.nii.gz", "label": "tr_label_002.fake.nii.gz"},
        {"fold": 0, "image": "tr_image_003.fake.nii.gz", "label": "tr_label_003.fake.nii.gz"},
        {"fold": 0, "image": "tr_image_004.fake.nii.gz", "label": "tr_label_004.fake.nii.gz"},
        {"fold": 1, "image": "tr_image_005.fake.nii.gz", "label": "tr_label_005.fake.nii.gz"},
        {"fold": 1, "image": "tr_image_006.fake.nii.gz", "label": "tr_label_006.fake.nii.gz"},
        {"fold": 1, "image": "tr_image_007.fake.nii.gz", "label": "tr_label_007.fake.nii.gz"},
        {"fold": 1, "image": "tr_image_008.fake.nii.gz", "label": "tr_label_008.fake.nii.gz"},
        {"fold": 2, "image": "tr_image_009.fake.nii.gz", "label": "tr_label_009.fake.nii.gz"},
        {"fold": 2, "image": "tr_image_010.fake.nii.gz", "label": "tr_label_010.fake.nii.gz"},
        {"fold": 2, "image": "tr_image_011.fake.nii.gz", "label": "tr_label_011.fake.nii.gz"},
        {"fold": 2, "image": "tr_image_012.fake.nii.gz", "label": "tr_label_012.fake.nii.gz"},
    ],
}
work_dir = "./build"
dataroot = "./build/data"

da_output_yaml = os.path.join(work_dir, "datastats.yaml")
data_src_cfg = os.path.join(work_dir, "data_src_cfg.yaml")

if not os.path.isdir(dataroot):
    os.makedirs(dataroot)

if not os.path.isdir(work_dir):
    os.makedirs(work_dir)

# Generate a fake dataset
for d in fake_datalist["testing"] + fake_datalist["training"]:
    im, seg = create_test_image_3d(24, 24, 24, rad_max=10, num_seg_classes=1)
    nib_image = nib.Nifti1Image(im, affine=np.eye(4))
    image_fpath = os.path.join(dataroot, d["image"])
    nib.save(nib_image, image_fpath)

    if "label" in d:
        nib_image = nib.Nifti1Image(seg, affine=np.eye(4))
        label_fpath = os.path.join(dataroot, d["label"])
        nib.save(nib_image, label_fpath)

# write to a json file
fake_json_datalist = os.path.join(dataroot, "fake_input.json")
ConfigParser.export_config_file(fake_datalist, fake_json_datalist)

da = DataAnalyzer(fake_json_datalist, dataroot, output_path=da_output_yaml)
da.get_all_case_stats()
```

The `stats_by_cases` in the output yaml file:
```
stats_by_cases: [null, null, null, null, null, null, null, null, null, null, null,
  null]
```

**Expected behavior**
The output yaml file should include the by_case stats.

**Screenshots**
![image](https://user-images.githubusercontent.com/18563433/226514390-00978431-0868-432e-9d01-031aabcc1be0.png)

**Environment**

Ensuring you use the relevant python executable, please paste the output of:

```
python -c 'import monai; monai.config.print_debug_info()'
```

**Additional context**

**Comment by myron** [comment]
this is by design, no need to fix anything

**Comment by myron** [comment]
to reduce the size of the saved yaml, it's beeing saved as 2 different files now:
https://github.com/Project-MONAI/MONAI/pull/6131

1) datastats.yaml (summary without stats_by_cases, with nulls)
2) datastats_by_case.yaml (stats_by_cases only)

otherwise yaml.safe_load() takes too long to load large yaml files.  Do you need stats of individual case for anything?

**Comment by mingxin-zheng** [comment]
Thank you @myron for the swift response.

I think the by_cases is used in the dummy trainers. Now it is unable to read it from the data_stats:
https://github.com/mingxin-zheng/research-contributions/blob/d8bec423e3b3ece41fca6589f4cf7d4502635c57/auto3dseg/algorithm_templates/segresnet2d/scripts/dummy_runner.py#L73

**Comment by myron** [comment]
that code should be updated, it would take too long to load individual case stats , (to find the max shape)

you can use a new field to find image size in millimeters, and then multiply it by resolution to get max_shape 
` image_size_mm = data_stats["stats_summary#image_stats#sizemm#percentile_99_5"]`

**Comment by mingxin-zheng** [comment]
Sure that sounds a proper way to fix the following issue:
```
/workspace/monai/MONAI# python -m tests.test_integration_gpu_customization
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 43.30it/s]
2023-03-21 03:24:26,375 - INFO - BundleGen from https://github.com/Project-MONAI/research-contributions/releases/download/algo_templates/d0fa876d.tar.gz
algo_templates.tar.gz: 64.0kB [00:01, 49.8kB/s]                                                                                                                                                                                    
2023-03-21 03:24:27,693 - INFO - Downloaded: /tmp/tmp5nrcdfvu/algo_templates.tar.gz
2023-03-21 03:24:27,693 - INFO - Expected md5 is None, skip md5 check for file /tmp/tmp5nrcdfvu/algo_templates.tar.gz.
2023-03-21 03:24:27,693 - INFO - Writing into directory: /tmp/tmphvljc4i6/workdir.
[info] gpu device 0 with minimum memory
[I 2023-03-21 03:24:27,874] A new study created in memory with name: no-name-3c8b3f2a-8a26-4ef9-9b1b-87d89840c905
patch_size [32, 32, 3]
patch_size_valid [32, 32, 3]
label_channels 1
monai.transforms.io.dictionary LoadImaged.__init__:image_only: Current default value of argument `image_only=False` has been deprecated since version 1.1. It will be changed to `image_only=True` in version 1.3.
Traceback (most recent call last):
  File "/tmp/tmphvljc4i6/workdir/segresnet2d_0/scripts/dummy_runner.py", line 222, in <module>
    fire.Fire(DummyRunnerSegResNet2D)
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/tmp/tmphvljc4i6/workdir/segresnet2d_0/scripts/dummy_runner.py", line 74, in __init__
    image_shape = data_stat["stats_by_cases"][_k]["image_stats"]["shape"]
TypeError: 'NoneType' object is not subscriptable
[error] OOM
```

**Comment by mingxin-zheng** [comment]
Since it is a different issue, I will open up another issue ticket and close this one.
