### ISSUE TITLE
test_onnx_0 test_retinanet

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#6296]
**Describe the bug**
with pytorch 1.9 (pytorch 21.10)
```
[2023-04-05T11:14:10.671Z] ======================================================================
[2023-04-05T11:14:10.671Z] FAIL: test_onnx_0 (tests.test_retinanet.TestRetinaNet)
[2023-04-05T11:14:10.671Z] ----------------------------------------------------------------------
[2023-04-05T11:14:10.671Z] Traceback (most recent call last):
[2023-04-05T11:14:10.671Z]   File "/opt/conda/lib/python3.8/site-packages/parameterized/parameterized.py", line 620, in standalone_func
[2023-04-05T11:14:10.671Z]     return func(*(a + p.args), **p.kwargs, **kw)
[2023-04-05T11:14:10.671Z]   File "/home/jenkins/agent/workspace/MONAI-premerge/monai/tests/test_retinanet.py", line 185, in test_onnx
[2023-04-05T11:14:10.671Z]     test_onnx_save(backbone, data, rtol=1e-3, atol=0.1)
[2023-04-05T11:14:10.671Z]   File "/home/jenkins/agent/workspace/MONAI-premerge/monai/tests/utils.py", line 758, in test_onnx_save
[2023-04-05T11:14:10.671Z]     convert_to_onnx(
[2023-04-05T11:14:10.671Z]   File "/home/jenkins/agent/workspace/MONAI-premerge/monai/monai/networks/utils.py", line 623, in convert_to_onnx
[2023-04-05T11:14:10.671Z]     torch.onnx.export(
[2023-04-05T11:14:10.671Z]   File "/opt/conda/lib/python3.8/site-packages/torch/onnx/__init__.py", line 308, in export
[2023-04-05T11:14:10.671Z]     return utils.export(model, args, f, export_params, verbose, training,
[2023-04-05T11:14:10.671Z]   File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 84, in export
[2023-04-05T11:14:10.671Z]     _export(model, args, f, export_params, verbose, training, input_names, output_names,
[2023-04-05T11:14:10.671Z]   File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 682, in _export
[2023-04-05T11:14:10.671Z]     _model_to_graph(model, args, verbose, input_names,
[2023-04-05T11:14:10.671Z]   File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 474, in _model_to_graph
[2023-04-05T11:14:10.671Z]     assert example_outputs is not None, "example_outputs must be provided when exporting a ScriptModule or " \
[2023-04-05T11:14:10.671Z] AssertionError: example_outputs must be provided when exporting a ScriptModule or ScriptFunction.
[2023-04-05T11:14:10.671Z] 
[2023-04-05T11:14:10.671Z] ======================================================================
[2023-04-05T11:14:10.671Z] FAIL: test_onnx_3 (tests.test_retinanet.TestRetinaNet)
[2023-04-05T11:14:10.671Z] ----------------------------------------------------------------------
[2023-04-05T11:14:10.671Z] Traceback (most recent call last):
[2023-04-05T11:14:10.671Z]   File "/opt/conda/lib/python3.8/site-packages/parameterized/parameterized.py", line 620, in standalone_func
[2023-04-05T11:14:10.671Z]     return func(*(a + p.args), **p.kwargs, **kw)
[2023-04-05T11:14:10.672Z]   File "/home/jenkins/agent/workspace/MONAI-premerge/monai/tests/test_retinanet.py", line 185, in test_onnx
[2023-04-05T11:14:10.672Z]     test_onnx_save(backbone, data, rtol=1e-3, atol=0.1)
[2023-04-05T11:14:10.672Z]   File "/home/jenkins/agent/workspace/MONAI-premerge/monai/tests/utils.py", line 758, in test_onnx_save
[2023-04-05T11:14:10.672Z]     convert_to_onnx(
[2023-04-05T11:14:10.672Z]   File "/home/jenkins/agent/workspace/MONAI-premerge/monai/monai/networks/utils.py", line 623, in convert_to_onnx
[2023-04-05T11:14:10.672Z]     torch.onnx.export(
[2023-04-05T11:14:10.672Z]   File "/opt/conda/lib/python3.8/site-packages/torch/onnx/__init__.py", line 308, in export
[2023-04-05T11:14:10.672Z]     return utils.export(model, args, f, export_params, verbose, training,
[2023-04-05T11:14:10.672Z]   File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 84, in export
[2023-04-05T11:14:10.672Z]     _export(model, args, f, export_params, verbose, training, input_names, output_names,
[2023-04-05T11:14:10.672Z]   File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 682, in _export
[2023-04-05T11:14:10.672Z]     _model_to_graph(model, args, verbose, input_names,
[2023-04-05T11:14:10.672Z]   File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 474, in _model_to_graph
[2023-04-05T11:14:10.672Z]     assert example_outputs is not None, "example_outputs must be provided when exporting a ScriptModule or " \
[2023-04-05T11:14:10.672Z] AssertionError: example_outputs must be provided when exporting a ScriptModule or ScriptFunction.
[2023-04-05T11:14:10.672Z] 
[2023-04-05T11:14:10.672Z] ======================================================================
[2023-04-05T11:14:10.672Z] FAIL: test_onnx_6 (tests.test_retinanet.TestRetinaNet)
[2023-04-05T11:14:10.672Z] ----------------------------------------------------------------------
[2023-04-05T11:14:10.672Z] Traceback (most recent call last):
[2023-04-05T11:14:10.672Z]   File "/opt/conda/lib/python3.8/site-packages/parameterized/parameterized.py", line 620, in standalone_func
[2023-04-05T11:14:10.672Z]     return func(*(a + p.args), **p.kwargs, **kw)
[2023-04-05T11:14:10.672Z]   File "/home/jenkins/agent/workspace/MONAI-premerge/monai/tests/test_retinanet.py", line 185, in test_onnx
[2023-04-05T11:14:10.672Z]     test_onnx_save(backbone, data, rtol=1e-3, atol=0.1)
[2023-04-05T11:14:10.672Z]   File "/home/jenkins/agent/workspace/MONAI-premerge/monai/tests/utils.py", line 758, in test_onnx_save
[2023-04-05T11:14:10.672Z]     convert_to_onnx(
[2023-04-05T11:14:10.672Z]   File "/home/jenkins/agent/workspace/MONAI-premerge/monai/monai/networks/utils.py", line 623, in convert_to_onnx
[2023-04-05T11:14:10.672Z]     torch.onnx.export(
[2023-04-05T11:14:10.672Z]   File "/opt/conda/lib/python3.8/site-packages/torch/onnx/__init__.py", line 308, in export
[2023-04-05T11:14:10.672Z]     return utils.export(model, args, f, export_params, verbose, training,
[2023-04-05T11:14:10.672Z]   File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 84, in export
[2023-04-05T11:14:10.672Z]     _export(model, args, f, export_params, verbose, training, input_names, output_names,
[2023-04-05T11:14:10.672Z]   File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 682, in _export
[2023-04-05T11:14:10.672Z]     _model_to_graph(model, args, verbose, input_names,
[2023-04-05T11:14:10.672Z]   File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 474, in _model_to_graph
[2023-04-05T11:14:10.672Z]     assert example_outputs is not None, "example_outputs must be provided when exporting a ScriptModule or " \
[2023-04-05T11:14:10.672Z] AssertionError: example_outputs must be provided when exporting a ScriptModule or ScriptFunction.
[2023-04-05T11:14:10.672Z] 
[2023-04-05T11:14:10.672Z] ----------------------------------------------------------------------
```

cc @binliunls @Nic-Ma  could you please have a look? if it takes time we can also revert the commit first.

**Comment by binliunls** [comment]
> (I'm including this workaround to skip tests before v1.10 [77f5e62](https://github.com/Project-MONAI/MONAI/commit/77f5e62d25d45f407cd11e298c5718f984242b2e) if it works I'll close this.)

FYI @wyli , this parameter was deprecated in pytorch 1.11. You can refer to [this link](https://pytorch.org/docs/1.10/onnx.html) for more details.

**Comment by wyli** [comment]
thanks @binliunls I'll change it to 1.11 and test

**Comment by wyli** [comment]
skipping the tests avoided this issue
