### ISSUE TITLE
TestEnsembleBuilder fails: No such file or directory: 'OMP_NUM_THREADS=1'

### ISSUE THREAD

**Issue by myron** [Project-MONAI/MONAI#6369]
Bug started after this PR https://github.com/Project-MONAI/MONAI/pull/6272

ensemble test doesn't pass https://github.com/Project-MONAI/MONAI/actions/runs/4703341444/jobs/8341714243

looks like something has changed the way command line is formed for training, @heyufan1995 please take a look

ERROR: test_ensemble (tests.test_auto3dseg_ensemble.TestEnsembleBuilder)

Traceback (most recent call last):
  File "/__w/MONAI/MONAI/tests/test_auto3dseg_ensemble.py", line 152, in test_ensemble
    algo.train(_train_param)
  File "/tmp/tmpoe7q1vri/workdir/algorithm_templates/dints/scripts/algo.py", line 470, in train
  File "/__w/MONAI/MONAI/monai/apps/auto3dseg/bundle_gen.py", line 238, in _run_cmd
    normal_out = subprocess.run(cmd.split(), env=ps_environ, check=True)
  File "/opt/conda/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/conda/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/conda/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'OMP_NUM_THREADS=1'

**Comment by heyufan1995** [comment]
@wyli @dongyang0122 
dints algo overides BundleAlgo.train() and the cmd has this 'OMP_NUM_THREADS=1' at the beggining of cmd.
https://github.com/Project-MONAI/research-contributions/blob/80c832ee0fe18eec1fa619127fc4388e87ff9401/auto3dseg/algorithm_templates/dints/scripts/algo.py#L469

**Comment by wyli** [comment]
this is addressed by ignoring any bash style variable assignment https://github.com/Project-MONAI/MONAI/blob/b356fecdb265ee9af4ce91a0c8238731994b5095/monai/apps/auto3dseg/bundle_gen.py#L225-L229
