### ISSUE TITLE
 torch 1.12.1 test_auto3dseg_ensemble

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#6391]
**Describe the bug**
```
[2023-04-18T16:01:00.704Z] 2023-04-18 16:01:00,505 - INFO - The keys num_warmup_epochs cannot be found in the /tmp/tmpqmv9202q/workdir/dints_0/configs/hyper_parameters.yaml for training. Skipped overriding key num_warmup_epochs.
[2023-04-18T16:01:00.704Z] 2023-04-18 16:01:00,505 - INFO - The keys use_pretrain cannot be found in the /tmp/tmpqmv9202q/workdir/dints_0/configs/hyper_parameters.yaml for training. Skipped overriding key use_pretrain.
[2023-04-18T16:01:00.704Z] 2023-04-18 16:01:00,505 - INFO - The keys pretrained_path cannot be found in the /tmp/tmpqmv9202q/workdir/dints_0/configs/hyper_parameters.yaml for training. Skipped overriding key pretrained_path.
[2023-04-18T16:01:00.704Z] 2023-04-18 16:01:00,505 - INFO - The keys determ cannot be found in the /tmp/tmpqmv9202q/workdir/dints_0/configs/hyper_parameters.yaml for training. Skipped overriding key determ.
[2023-04-18T16:01:00.704Z] 2023-04-18 16:01:00,505 - INFO - Launching: OMP_NUM_THREADS=1 python /tmp/tmpqmv9202q/workdir/dints_0/scripts/train.py run --config_file='/tmp/tmpqmv9202q/workdir/dints_0/configs/hyper_parameters.yaml','/tmp/tmpqmv9202q/workdir/dints_0/configs/hyper_parameters_search.yaml','/tmp/tmpqmv9202q/workdir/dints_0/configs/network.yaml','/tmp/tmpqmv9202q/workdir/dints_0/configs/network_search.yaml','/tmp/tmpqmv9202q/workdir/dints_0/configs/transforms_infer.yaml','/tmp/tmpqmv9202q/workdir/dints_0/configs/transforms_train.yaml','/tmp/tmpqmv9202q/workdir/dints_0/configs/transforms_validate.yaml' --training#num_images_per_batch=2 --training#num_epochs=2 --training#num_epochs_per_validation=1
[2023-04-18T16:01:08.782Z] Traceback (most recent call last):
[2023-04-18T16:01:08.783Z]   File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/bundle/config_item.py", line 292, in instantiate
[2023-04-18T16:01:08.783Z]     return instantiate(modname, mode, **args)
[2023-04-18T16:01:08.783Z]   File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/utils/module.py", line 247, in instantiate
[2023-04-18T16:01:08.783Z]     raise ModuleNotFoundError(f"Cannot locate class or function path: '{__path}'.")
[2023-04-18T16:01:08.783Z] ModuleNotFoundError: Cannot locate class or function path: 'torch.optim.lr_scheduler.PolynomialLR'.
[2023-04-18T16:01:08.783Z] 
[2023-04-18T16:01:08.783Z] The above exception was the direct cause of the following exception:
[2023-04-18T16:01:08.783Z] 
[2023-04-18T16:01:08.783Z] Traceback (most recent call last):
[2023-04-18T16:01:08.783Z]   File "/tmp/tmpqmv9202q/workdir/dints_0/scripts/train.py", line 685, in <module>
[2023-04-18T16:01:08.783Z]     fire.Fire()
[2023-04-18T16:01:08.783Z]   File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
[2023-04-18T16:01:08.783Z]     component_trace = _Fire(component, args, parsed_flag_args, context, name)
[2023-04-18T16:01:08.783Z]   File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
[2023-04-18T16:01:08.783Z]     component, remaining_args = _CallAndUpdateTrace(
[2023-04-18T16:01:08.783Z]   File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
[2023-04-18T16:01:08.783Z]     component = fn(*varargs, **kwargs)
[2023-04-18T16:01:08.783Z]   File "/tmp/tmpqmv9202q/workdir/dints_0/scripts/train.py", line 326, in run
[2023-04-18T16:01:08.783Z]     lr_scheduler = lr_scheduler_part.instantiate(optimizer=optimizer)
[2023-04-18T16:01:08.783Z]   File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/bundle/config_item.py", line 294, in instantiate
[2023-04-18T16:01:08.783Z]     raise RuntimeError(f"Failed to instantiate {self}.") from e
[2023-04-18T16:01:08.783Z] RuntimeError: Failed to instantiate {'_target_': 'torch.optim.lr_scheduler.PolynomialLR', 'optimizer': {'_target_': 'torch.optim.SGD', 'lr': 0.2, 'momentum': 0.9, 'weight_decay': 4e-05}, 'power': 0.5, 'total_iters': 3}.
[2023-04-18T16:01:09.039Z] 
[2023-04-18T16:01:09.040Z] E2023-04-18 16:01:08,818 - INFO - Directory /tmp/tmpb6i4hml3/workdir is created to save ensemble predictions
```

**Comment by wyli** [comment]
[2023-04-18T15:50:21.829Z] 2023-04-18 15:50:21,812 - INFO - Launching: OMP_NUM_THREADS=1 python /tmp/tmp8tk92xiv/workdir/dints_0/scripts/train.py run --config_file='/tmp/tmp8tk92xiv/workdir/dints_0/configs/hyper_parameters.yaml','/tmp/tmp8tk92xiv/workdir/dints_0/configs/hyper_parameters_search.yaml','/tmp/tmp8tk92xiv/workdir/dints_0/configs/network.yaml','/tmp/tmp8tk92xiv/workdir/dints_0/configs/network_search.yaml','/tmp/tmp8tk92xiv/workdir/dints_0/configs/transforms_infer.yaml','/tmp/tmp8tk92xiv/workdir/dints_0/configs/transforms_train.yaml','/tmp/tmp8tk92xiv/workdir/dints_0/configs/transforms_validate.yaml' --training#num_images_per_batch=2 --training#num_epochs=2 --training#num_epochs_per_validation=1
[2023-04-18T15:50:25.989Z] Traceback (most recent call last):
[2023-04-18T15:50:25.990Z]   File "/tmp/tmp8tk92xiv/workdir/dints_0/scripts/train.py", line 60, in <module>
[2023-04-18T15:50:25.990Z]     torch.set_float32_matmul_precision("high")
[2023-04-18T15:50:25.990Z] AttributeError: module 'torch' has no attribute 'set_float32_matmul_precision'
