### ISSUE TITLE
Auto3dseg integration

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#6417]
```

predictions
[2023-04-22T04:14:14.404Z] 2023-04-22 04:14:13,627 - INFO - Directory /tmp/tmp8m_dx6rq/work_dir/ensemble_output is created to save ensemble predictions
[2023-04-22T04:14:14.404Z] Traceback (most recent call last):
[2023-04-22T04:14:14.404Z]   File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
[2023-04-22T04:14:14.404Z]     return _run_code(code, main_globals, None,
[2023-04-22T04:14:14.404Z]   File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
[2023-04-22T04:14:14.404Z]     exec(code, run_globals)
[2023-04-22T04:14:14.404Z]   File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/apps/auto3dseg/__main__.py", line 24, in <module>
[2023-04-22T04:14:14.404Z]     fire.Fire(
[2023-04-22T04:14:14.404Z]   File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
[2023-04-22T04:14:14.404Z]     component_trace = _Fire(component, args, parsed_flag_args, context, name)
[2023-04-22T04:14:14.404Z]   File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
[2023-04-22T04:14:14.404Z]     component, remaining_args = _CallAndUpdateTrace(
[2023-04-22T04:14:14.404Z]   File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
[2023-04-22T04:14:14.404Z]     component = fn(*varargs, **kwargs)
[2023-04-22T04:14:14.404Z]   File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/apps/auto3dseg/ensemble_builder.py", line 478, in ensemble
[2023-04-22T04:14:14.404Z]     self.set_image_save_transform(**self.kwargs)
[2023-04-22T04:14:14.404Z]   File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/apps/auto3dseg/ensemble_builder.py", line 438, in set_image_save_transform
[2023-04-22T04:14:14.404Z]     os.makedirs(output_dir)
[2023-04-22T04:14:14.404Z]   File "/opt/conda/lib/python3.8/os.py", line 223, in makedirs
[2023-04-22T04:14:14.404Z]     mkdir(name, mode)
[2023-04-22T04:14:14.404Z] FileExistsError: [Errno 17] File exists: '/tmp/tmp8m_dx6rq/work_dir/ensemble_output'
[2023-04-22T04:14:14.404Z] 2023-04-22 04:14:13,682 - INFO - Auto3Dseg picked the following networks to ensemble:
[2023-04-22T04:14:14.404Z] 2023-04-22 04:14:13,682 - INFO - segresnet2d_0
[2023-04-22T04:14:14.404Z] 2023-04-22 04:14:13,682 - INFO - Auto3Dseg ensemble prediction outputs will be saved in /tmp/tmp8m_dx6rq/work_dir/ensemble_output.
[2023-04-22T04:14:14.404Z] 
Ensembling (rank 0)...:   0%|          | 0/1 [00:00<?, ?it/s]monai.transforms.io.dictionary LoadImaged.__init__:image_only: Current default value of argument `image_only=False` has been deprecated since version 1.1. It will be changed to `image_only=True` in version 1.3.
[2023-04-22T04:14:14.659Z] [info] checkpoint /tmp/tmp8m_dx6rq/work_dir/segresnet2d_0/model_fold0/best_metric_model.pt loaded
[2023-04-22T04:14:15.589Z] 2023-04-22 04:14:15,372 INFO image_writer.py:197 - writing: /tmp/tmp8m_dx6rq/work_dir/segresnet2d_0/prediction_testing/val_001.fake/val_001.fake_seg.nii.gz

```

**Comment by mingxin-zheng** [comment]
Does this happen in multi-node/multi-GPU testing?

This bug looks like two processes are competing each other to do `os.makedirs()` .

**Comment by wyli** [comment]
Indeed it happened to the multigpu tests and it's random... I think that's the issue. Could you please submit a PR to fix it?
