### ISSUE TITLE
BentoML can't handle deepcopy in MONAI RetinaNet 3D model

### ISSUE THREAD

**Issue by AceMcAwesome77** [Project-MONAI/MONAI#6458]
I trained a RetinaNet 3D model from the MONAI detection framework and am trying to serve it using BentoML, but am getting the following error:

```
Traceback (most recent call last):
  File "/app/bento_service.py", line 242, in inference
    prediction = await torch_model_runner.do_prediction.async_run(data)
  File "/usr/local/lib/python3.8/dist-packages/bentoml/_internal/runner/runner.py", line 55, in async_run
    return await self.runner._runner_handle.async_run_method(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/bentoml/_internal/runner/runner_handle/local.py", line 59, in async_run_method
    return await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.8/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread(
    return await future
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.8/dist-packages/bentoml/_internal/runner/runnable.py", line 139, in method
    return self.func(obj, *args, **kwargs)
  File "/app/bento_service.py", line 128, in do_prediction
    prediction = self.detector(data, use_inferer=True)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/monai/apps/detection/networks/retinanet_detector.py", line 518, in forward
    detections = self.postprocess_detections(
  File "/usr/local/lib/python3.8/dist-packages/monai/apps/detection/networks/retinanet_detector.py", line 654, in postprocess_detections
    selected_boxes, selected_scores, selected_labels = self.box_selector.select_boxes_per_image(
  File "/usr/local/lib/python3.8/dist-packages/monai/apps/detection/utils/box_selector.py", line 204, in select_boxes_per_image
    keep_t: Tensor = batched_nms(  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/monai/data/box_utils.py", line 1131, in batched_nms
    keep = non_max_suppression(boxes_for_nms, scores_t, nms_thresh, max_proposals, box_overlap_metric)
  File "/usr/local/lib/python3.8/dist-packages/monai/data/box_utils.py", line 1060, in non_max_suppression
    boxes_sort = deepcopy(boxes_t)[sort_idxs, :]
  File "/usr/lib/python3.8/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/usr/local/lib/python3.8/dist-packages/torch/_tensor.py", line 86, in __deepcopy__
    raise RuntimeError(
RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment

```
If I don't use convert_box_mode in the post_transforms, then the only place deepcopy is actually called is this function within box_utils.py:

```
    # sort boxes in descending order according to the scores
    sort_idxs = torch.argsort(scores_t, dim=0, descending=True)
    boxes_sort = deepcopy(boxes_t)[sort_idxs, :]
```

Do we need deepcopy at that location or should it be replaced with some other logic to avoid this error?

The model runs fine on my local computer without using BentoML, which is why I assume the error is related to that.

**Comment by AceMcAwesome77** [comment]
I just figured this out actually - this is solved by including "with torch.no_grad()" inside the runner method definition like so:

```
class RetinanetRunnable(bentoml.Runnable):
    SUPPORTED_RESOURCES = ("nvidia.com/gpu")
    SUPPORTS_CPU_MULTI_THREADING = False

    def __init__(self): 
        self.detector = RetinaNetDetector(network=net,
                                          anchor_generator=anchor_generator,
                                          debug=False)
        
        patch_size = (192,192,96)
        self.detector.set_box_selector_parameters(
            score_thresh=0.02,
            topk_candidates_per_level=1000,
            nms_thresh=0.22,
            detections_per_img=1,
        )
        self.detector.set_sliding_window_inferer(
            roi_size=patch_size,
            overlap=0.25,
            sw_batch_size=1,
            mode="gaussian",
            device=device,
        )
        self.detector.eval()

    @bentoml.Runnable.method(batchable=True, batch_dim=0)
    def do_prediction(self, data):
        with torch.no_grad():
            prediction = self.detector(data, use_inferer=True)
            return prediction
```

If no_grad is outside the method definition the graph leaves error will occur.
