### ISSUE TITLE
Lazy resampling integration test failure

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#6569]
**Describe the bug**
```
======================================================================
ERROR: test_training (__main__.IntegrationLazyResampling)
----------------------------------------------------------------------
Traceback (most recent call last):
test case: {'root_dir': '/tmp/tmpsh17fpf7', 'device': 'cuda:0', 'cachedataset': 0, 'readers': (None, None), 'num_workers': 2, 'lazy': False}
----------
Epoch 1/5
1/3, train_loss:0.6714
img2.nii.gz - [65, 19, 3, 22, 35, 67]
img2.nii.gz - [66, 18, 25, 0, 86, 16]
img2.nii.gz - [0, 84, 0, 25, 68, 34]
img2.nii.gz - [84, 0, 0, 25, 34, 68]
2/3, train_loss:0.5815
img1.nii.gz - [38, 46, 86, 14, 8, 19]
img1.nii.gz - [71, 13, 78, 22, 27, 0]
img1.nii.gz - [34, 50, 67, 33, 15, 12]
img1.nii.gz - [76, 8, 88, 12, 27, 0]
3/3, train_loss:0.6870
img0.nii.gz - [53, 31, 100, 0, 15, 12]
img0.nii.gz - [53, 31, 100, 0, 24, 3]
img0.nii.gz - [0, 84, 59, 41, 8, 19]
img0.nii.gz - [0, 84, 100, 0, 0, 27]
----------
Epoch 2/5
1/3, train_loss:0.7074
img1.nii.gz - [0, 84, 100, 0, 16, 11]
img1.nii.gz - [47, 37, 19, 81, 23, 4]
  File "tests/test_integration_lazy_samples.py", line 215, in test_training
    self.train_and_infer(i)
  File "tests/test_integration_lazy_samples.py", line 192, in train_and_infer
    results_expected = run_training_test(
  File "tests/test_integration_lazy_samples.py", line 154, in run_training_test
    invertible, reasons = has_status_keys(batch_data, TraceStatusKeys.PENDING_DURING_APPLY)
TypeError: has_status_keys() missing 1 required positional argument: 'default_msg'

----------------------------------------------------------------------
Ran 1 test in 17.147s

FAILED (errors=1)
```

**Comment by Nic-Ma** [comment]
Hi @atbenmurray ,

Could you please help fix this CI test failure ASAP?

Thanks in advance.

**Comment by atbenmurray** [comment]
Doing so
