### ISSUE TITLE
Cropposneg gives error if one of the volumes doesn't have any labels (all background)

### ISSUE THREAD

**Issue by AHarouni** [Project-MONAI/MONAI#6576]
**Describe the bug**
when using cropposneg transform and one of the labels for the volumes is all zeros training stops with an error.

**To Reproduce**
for any training job that uses cropposneg, go to any of the labels and clear it all so there is not foreground.
run training and see the error below 

**workarounds **
If I use randcropbylabelclasses instead, things work and I can train. however you need to give the ratio for each class which may not be what you need for a multiclass segmentation problem

**Expected behavior**
It should simply take samples from the background and move on 
May be give a warning --> must include the file name 
currently the error is not even helpful, as it doesn't even say the files name 

**Additional context**
error I get is 
```
N foreground 0, N  background 108862277,unable to generate class balanced samples.
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/opt/monai/monai/transforms/transform.py", line 91, in apply_transform
    return _apply_transform(transform, data, unpack_items)
  File "/opt/monai/monai/transforms/transform.py", line 55, in _apply_transform
    return transform(parameters)
  File "/opt/monai/monai/transforms/croppad/dictionary.py", line 861, in __call__
    self.randomize(label, fg_indices, bg_indices, image)
  File "/opt/monai/monai/transforms/croppad/dictionary.py", line 852, in randomize
    self.cropper.randomize(label=label, fg_indices=fg_indices, bg_indices=bg_indices, image=image)
  File "/opt/monai/monai/transforms/croppad/array.py", line 1060, in randomize
    self.centers = generate_pos_neg_label_crop_centers(
  File "/opt/monai/monai/transforms/utils.py", line 516, in generate_pos_neg_label_crop_centers
    random_int = rand_state.randint(len(indices_to_use))
  File "mtrand.pyx", line 748, in numpy.random.mtrand.RandomState.randint
  File "_bounded_integers.pyx", line 1247, in numpy.random._bounded_integers._rand_int64
ValueError: high <= 0
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/monai/monai/data/thread_buffer.py", line 47, in enqueue_values
    for src_val in self.src:
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 719, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/monai/monai/data/dataset.py", line 104, in __getitem__
    return self._transform(index)
  File "/opt/monai/monai/data/dataset.py", line 877, in _transform
    data = apply_transform(_transform, data)
  File "/opt/monai/monai/transforms/transform.py", line 118, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.croppad.dictionary.RandCropByPosNegLabeld object at 0x7f3dea8a8550>
```

**Comment by KumoLiu** [comment]
Hi @AHarouni, thanks for your interest here!
It does indeed display a warning message indicating that you have an imbalanced label.
https://github.com/Project-MONAI/MONAI/blob/00376799a2ae0e6b84fb1efe1ef9ff6d8cbedc19/monai/transforms/utils.py#L561-L564
Also for the `RandCropByLabelClasses`.
https://github.com/Project-MONAI/MONAI/blob/00376799a2ae0e6b84fb1efe1ef9ff6d8cbedc19/monai/transforms/utils.py#L622

So I'm not sure what you mean it can work in `RandCropByLabelClasses` but not `RandCropByPosNegLabeld`. If you didn't have a foreground,  `RandCropByLabelClasses` will also throw a warning. We didn't provide the filename when throwing this warning because it is in a separate function, which can also be used when the user provides his own fg_indices and bg_indices. Maybe the best way when you see this warning is to check all your label. Feel free to ask me if you have any other questions.


Hope it can help you, thanks!

**Comment by KumoLiu** [comment]
Hi @AHarouni, I see your points. I think the issue has been solved by this line.
https://github.com/Project-MONAI/MONAI/blob/a2ec3752f54bfc3b40e7952234fbeb5452ed63e3/monai/transforms/utils.py#L508
You can try MONAI 1.1.0.
Thanks!

**Comment by KumoLiu** [comment]
Closed this one for now, feel free to reopen it if it's still an issue. Thanks!
