### ISSUE TITLE
Invertd not working as in spleen tutorial

### ISSUE THREAD

**Issue by KumoLiu** [Project-MONAI/MONAI#6591]
### Discussed in https://github.com/Project-MONAI/MONAI/discussions/6589

<div type='discussions-op-text'>

<sup>Originally posted by **hreso110100** June  7, 2023</sup>
I was following this tutorial https://github.com/Project-MONAI/tutorials/blob/main/3d_segmentation/spleen_segmentation_3d.ipynb, concretely **Inference on Test Set part**:

This is my postTransform Compose for prediction of model 

```
postTransform = Compose(
    [
        Invertd(keys="pred", transform=INFERENCE_PRE_TRANSFORM, orig_keys='img', meta_keys='pred_meta_dict',
                orig_meta_keys='img_meta_dict',
                meta_key_postfix='meta_dict', to_tensor=True, nearest_interp=False, device="cpu"),
        Activationsd(keys='pred', sigmoid=True),
        AsDiscreted(keys='pred', threshold=0.7),
        RemoveSmallObjectsd(keys="pred", min_size=50)
    ]
)
```

This is my  preTransform Compose:

```
INFERENCE_PRE_TRANSFORM = Compose(
    [
        LoadImaged(keys=["img"]),
        EnsureChannelFirstd(keys=["img"]),
        Spacingd(keys=["img"], pixdim=(0.97, 0.97, 2.95), mode="bilinear"),
        ScaleIntensityRanged(
            keys=["img"],
            a_min=-135,
            a_max=215,
            b_min=0.0,
            b_max=1.0,
            clip=True,
        ),
        ToTensord(keys=["img"])
    ]
)
```

This is my prediction loop

```
with torch.no_grad():
    backslash = "\\"

    for batchTestData in testLoader:
        affine = batchTestData['img_meta_dict']['original_affine'][0].cpu().numpy()
        print(f"PREDICTING CASE: {batchTestData['img_meta_dict']['filename_or_obj'][0].split(backslash)[-1]}")
        batchTestData['pred'] = sliding_window_inference(batchTestData["img"].to(myDevice), roi_size=(96, 96, 96),
                                                         sw_batch_size=1, sw_device=myDevice,
                                                         predictor=model, overlap=0.7, device="cpu")
        output = [postTransform(b) for b in decollate_batch(batchTestData)]

        pred_hrd = Nifti1Header()
        pred_hrd.set_qform(affine, code=int(batchTestData['img_meta_dict']["qform_code"]))
        pred_hrd.set_sform(affine, code=int(batchTestData['img_meta_dict']["sform_code"]))

        output = determine_converter(output)
        determine_output_name(output)

```

but I ve got this error : 

```
Traceback (most recent call last):
  File "C:\Users\David\PycharmProjects\generalizationmonai\venv\Lib\site-packages\monai\transforms\transform.py", line 103, in apply_transform
    return _apply_transform(transform, data, unpack_items)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\David\PycharmProjects\generalizationmonai\venv\Lib\site-packages\monai\transforms\transform.py", line 67, in _apply_transform
    return transform(parameters)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\David\PycharmProjects\generalizationmonai\venv\Lib\site-packages\monai\transforms\spatial\dictionary.py", line 452, in inverse
    d[key] = self.spacing_transform.inverse(cast(torch.Tensor, d[key]))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\David\PycharmProjects\generalizationmonai\venv\Lib\site-packages\monai\transforms\spatial\array.py", line 507, in inverse
    return self.sp_resample.inverse(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\David\PycharmProjects\generalizationmonai\venv\Lib\site-packages\monai\transforms\spatial\array.py", line 220, in inverse
    transform = self.pop_transform(data)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\David\PycharmProjects\generalizationmonai\venv\Lib\site-packages\monai\transforms\inverse.py", line 312, in pop_transform
    return self.get_most_recent_transform(data, key, check, pop=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\David\PycharmProjects\generalizationmonai\venv\Lib\site-packages\monai\transforms\inverse.py", line 292, in get_most_recent_transform
    raise ValueError(f"`data` should be either `MetaTensor` or dictionary, got {type(data)}.")
ValueError: `data` should be either `MetaTensor` or dictionary, got <class 'numpy.ndarray'>.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\David\PycharmProjects\generalizationmonai\venv\Lib\site-packages\monai\transforms\transform.py", line 103, in apply_transform
    return _apply_transform(transform, data, unpack_items)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\David\PycharmProjects\generalizationmonai\venv\Lib\site-packages\monai\transforms\transform.py", line 67, in _apply_transform
    return transform(parameters)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\David\PycharmProjects\generalizationmonai\venv\Lib\site-packages\monai\transforms\post\dictionary.py", line 702, in __call__
    inverted = self.transform.inverse(input_dict)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\David\PycharmProjects\generalizationmonai\venv\Lib\site-packages\monai\transforms\compose.py", line 478, in inverse
    data = apply_transform(t.inverse, data, self.map_items, self.unpack_items, self.log_stats)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\David\PycharmProjects\generalizationmonai\venv\Lib\site-packages\monai\transforms\transform.py", line 130, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <bound method Spacingd.inverse of <monai.transforms.spatial.dictionary.Spacingd object at 0x0000027C88309650>>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\David\PycharmProjects\generalizationmonai\inference\predict.py", line 109, in <module>
    output = [postTransform(b) for b in decollate_batch(batchTestData)]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\David\PycharmProjects\generalizationmonai\inference\predict.py", line 109, in <listcomp>
    output = [postTransform(b) for b in decollate_batch(batchTestData)]
              ^^^^^^^^^^^^^^^^
  File "C:\Users\David\PycharmProjects\generalizationmonai\venv\Lib\site-packages\monai\transforms\compose.py", line 451, in __call__
    return execute_compose(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\David\PycharmProjects\generalizationmonai\venv\Lib\site-packages\monai\transforms\compose.py", line 199, in execute_compose
    data = apply_transform(_transform, data, map_items, unpack_items, log_stats)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\David\PycharmProjects\generalizationmonai\venv\Lib\site-packages\monai\transforms\transform.py", line 130, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.post.dictionary.Invertd object at 0x0000027C875DD050>
```</div>

**Comment by KumoLiu** [comment]
Maybe a bug caused by lazy-resampling, is investigating.
