### ISSUE TITLE
Installing the dev environment fails with AttributeError: install_layout

### ISSUE THREAD

**Issue by matt3o** [Project-MONAI/MONAI#6655]
**Describe the bug**
I wanted to do a short Pull request, however ran into error when trying to run the dev environment. I'll paste the output below. I forked the code from Github, pulled the repo, created my own branch (from dev) and then tried to run tests. When that failed I went back to the MONAI installation site and tried the official building steps, but they return the same error:

```bash
(monai_dev) matteo@matteo-ubuntu-server:~/code/MONAI_matteo$ python setup.py develop
setup.py with torch 2.0.0+cu117
Please set environment variable `BUILD_MONAI=1` to enable Cpp/CUDA extension build.
BUILD_MONAI_CPP=False, BUILD_MONAI_CUDA=False, TORCH_VERSION=20000.
running develop
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
Traceback (most recent call last):
  File "/home/matteo/code/MONAI_matteo/setup.py", line 144, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 985, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/usr/lib/python3/dist-packages/setuptools/command/develop.py", line 52, in finalize_options
    easy_install.finalize_options(self)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 299, in finalize_options
    self.set_undefined_options(
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 287, in set_undefined_options
    src_cmd_obj.ensure_finalized()
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 17, in finalize_options
    self.set_undefined_options('install',('install_layout','install_layout'))
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 290, in set_undefined_options
    setattr(self, dst_option, getattr(src_cmd_obj, src_option))
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 103, in __getattr__
    raise AttributeError(attr)
AttributeError: install_layout. Did you mean: 'install_platlib'?
```

Also trying to uninstall in this state yields another error which may be unimportant.

```bash
(monai_dev) matteo@matteo-ubuntu-server:~/code/MONAI_matteo$ ./runtests.sh --clean
PYTHONPATH: /home/matteo/code/MONAI_matteo:
Python: /home/matteo/anaconda3/envs/monai_dev/bin/python
--------------------------------------------------------------------------------
clean
Uninstalling MONAI development files...
setup.py with torch 2.0.0+cu117
Please set environment variable `BUILD_MONAI=1` to enable Cpp/CUDA extension build.
BUILD_MONAI_CPP=False, BUILD_MONAI_CUDA=False, TORCH_VERSION=20000.
running develop
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
Traceback (most recent call last):
  File "/home/matteo/code/MONAI_matteo/setup.py", line 144, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 985, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/usr/lib/python3/dist-packages/setuptools/command/develop.py", line 52, in finalize_options
    easy_install.finalize_options(self)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 270, in finalize_options
    self._fix_install_dir_for_user_site()
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 400, in _fix_install_dir_for_user_site
    self.select_scheme(scheme_name)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 741, in select_scheme
    scheme = INSTALL_SCHEMES[name]
KeyError: 'unix_user'

```

**Environment**

Ensuring you use the relevant python executable, please paste the output of:

```
================================
Printing MONAI config...
================================
MONAI version: 0+untagged.2722.gf4d2f32.dirty
Numpy version: 1.24.3
Pytorch version: 2.0.0+cu117
MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
MONAI rev id: f4d2f3291665bb5e4ffcb114ff2e3ab06b5744c2
MONAI __file__: /home/matteo/code/MONAI_matteo/monai/__init__.py

Optional dependencies:
Pytorch Ignite version: NOT INSTALLED or UNKNOWN VERSION.
ITK version: 5.3.0
Nibabel version: 5.1.0
scikit-image version: 0.21.0
Pillow version: 9.0.1
Tensorboard version: NOT INSTALLED or UNKNOWN VERSION.
gdown version: NOT INSTALLED or UNKNOWN VERSION.
TorchVision version: NOT INSTALLED or UNKNOWN VERSION.
tqdm version: 4.65.0
lmdb version: 1.4.1
psutil version: 5.9.5
pandas version: 2.0.1
einops version: 0.6.1
transformers version: NOT INSTALLED or UNKNOWN VERSION.
mlflow version: NOT INSTALLED or UNKNOWN VERSION.
pynrrd version: 1.0.0

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies


================================
Printing system config...
================================
System: Linux
Linux version: Ubuntu 22.04.2 LTS
Platform: Linux-5.19.0-45-generic-x86_64-with-glibc2.35
Processor: x86_64
Machine: x86_64
Python version: 3.10.11
Process name: python
Command: ['python', '-c', 'import monai; monai.config.print_debug_info()']
Open files: []
Num physical CPUs: 12
Num logical CPUs: 24
Num usable CPUs: 24
CPU usage (%): [6.4, 7.2, 7.1, 6.3, 6.3, 6.4, 6.4, 6.4, 6.4, 7.1, 6.3, 100.0, 6.3, 7.2, 7.1, 6.4, 7.2, 8.0, 6.4, 6.4, 6.4, 6.3, 6.4, 6.3]
CPU freq. (MHz): 2421
Load avg. in last 1, 5, 15 mins (%): [2.6, 2.9, 2.5]
Disk usage (%): 25.5
Avg. sensor temp. (Celsius): UNKNOWN for given OS
Total physical memory (GB): 31.2
Available memory (GB): 25.5
Used memory (GB): 5.2

================================
Printing GPU config...
================================
Num GPUs: 1
Has CUDA: True
CUDA version: 11.7
cuDNN enabled: True
cuDNN version: 8500
Current device: 0
Library compiled for CUDA architectures: ['sm_37', 'sm_50', 'sm_60', 'sm_70', 'sm_75', 'sm_80', 'sm_86']
GPU 0 Name: NVIDIA GeForce RTX 3090 Ti
GPU 0 Is integrated: False
GPU 0 Is multi GPU board: False
GPU 0 Multi processor count: 84
GPU 0 Total memory (GB): 22.2
GPU 0 CUDA capability (maj.min): 8.6

```

**Comment by wyli** [comment]
looks like a setuptools version issue, please note the requirement https://github.com/Project-MONAI/MONAI/blob/0ffe55a0d2d9165dc3841e5cc4a9d177b08c6b57/requirements-min.txt#L3

could try `pip install -U -r requirements-min.txt`

**Comment by matt3o** [comment]
It's a bit weird, it appears I cannot overwrite my systems setuptools
```bash
(monai_dev) matteo@matteo-ubuntu-server:~/code/MONAI_matteo$ pip install setuptools==65
Collecting setuptools==65
  Downloading setuptools-65.0.0-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 9.8 MB/s eta 0:00:00
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 59.6.0
    Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /home/matteo/anaconda3/envs/monai_dev
    Can't uninstall 'setuptools'. No files were found to uninstall.
Successfully installed setuptools-67.8.0
```
And the some output comes again if I repeat the command / pip freeze | grep setuptools is empy.

However it is version 59.6.0, so it should still fit the requirements..

```bash
(monai_dev) matteo@matteo-ubuntu-server:~/code/MONAI_matteo$ pip install -U -r requirements-min.txt
Requirement already satisfied: torch>=1.9 in /home/matteo/anaconda3/envs/monai_dev/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (2.0.1)
Requirement already satisfied: numpy>=1.20 in /home/matteo/anaconda3/envs/monai_dev/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (1.25.0)
Requirement already satisfied: setuptools!=60.6.0,<66.0.0,>=50.3.0 in /usr/lib/python3/dist-packages (from -r requirements-min.txt (line 3)) (59.6.0)
Collecting setuptools!=60.6.0,<66.0.0,>=50.3.0
  Using cached setuptools-65.7.0-py3-none-any.whl (1.2 MB)
Requirement already satisfied: coverage>=5.5 in /home/matteo/anaconda3/envs/monai_dev/lib/python3.10/site-packages (from -r requirements-min.txt (line 4)) (7.2.7)
Requirement already satisfied: parameterized in /home/matteo/anaconda3/envs/monai_dev/lib/python3.10/site-packages (from -r requirements-min.txt (line 5)) (0.9.0)
Requirement already satisfied: jinja2 in /home/matteo/anaconda3/envs/monai_dev/lib/python3.10/site-packages (from torch>=1.9->-r requirements.txt (line 1)) (3.1.2)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in /home/matteo/anaconda3/envs/monai_dev/lib/python3.10/site-packages (from torch>=1.9->-r requirements.txt (line 1)) (11.7.99)
Requirement already satisfied: nvidia-nccl-cu11==2.14.3 in /home/matteo/anaconda3/envs/monai_dev/lib/python3.10/site-packages (from torch>=1.9->-r requirements.txt (line 1)) (2.14.3)
Requirement already satisfied: nvidia-cusolver-cu11==11.4.0.1 in /home/matteo/anaconda3/envs/monai_dev/lib/python3.10/site-packages (from torch>=1.9->-r requirements.txt (line 1)) (11.4.0.1)
Requirement already satisfied: nvidia-cusparse-cu11==11.7.4.91 in /home/matteo/anaconda3/envs/monai_dev/lib/python3.10/site-packages (from torch>=1.9->-r requirements.txt (line 1)) (11.7.4.91)
Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in /home/matteo/anaconda3/envs/monai_dev/lib/python3.10/site-packages (from torch>=1.9->-r requirements.txt (line 1)) (8.5.0.96)
Requirement already satisfied: typing-extensions in /home/matteo/anaconda3/envs/monai_dev/lib/python3.10/site-packages (from torch>=1.9->-r requirements.txt (line 1)) (4.6.3)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /home/matteo/anaconda3/envs/monai_dev/lib/python3.10/site-packages (from torch>=1.9->-r requirements.txt (line 1)) (11.7.99)
Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in /home/matteo/anaconda3/envs/monai_dev/lib/python3.10/site-packages (from torch>=1.9->-r requirements.txt (line 1)) (11.10.3.66)
Requirement already satisfied: filelock in /home/matteo/anaconda3/envs/monai_dev/lib/python3.10/site-packages (from torch>=1.9->-r requirements.txt (line 1)) (3.11.0)
Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in /home/matteo/anaconda3/envs/monai_dev/lib/python3.10/site-packages (from torch>=1.9->-r requirements.txt (line 1)) (10.9.0.58)
Requirement already satisfied: triton==2.0.0 in /home/matteo/anaconda3/envs/monai_dev/lib/python3.10/site-packages (from torch>=1.9->-r requirements.txt (line 1)) (2.0.0)
Requirement already satisfied: sympy in /home/matteo/anaconda3/envs/monai_dev/lib/python3.10/site-packages (from torch>=1.9->-r requirements.txt (line 1)) (1.12)
Requirement already satisfied: nvidia-nvtx-cu11==11.7.91 in /home/matteo/anaconda3/envs/monai_dev/lib/python3.10/site-packages (from torch>=1.9->-r requirements.txt (line 1)) (11.7.91)
Requirement already satisfied: networkx in /home/matteo/anaconda3/envs/monai_dev/lib/python3.10/site-packages (from torch>=1.9->-r requirements.txt (line 1)) (3.1)
Requirement already satisfied: nvidia-cuda-cupti-cu11==11.7.101 in /home/matteo/anaconda3/envs/monai_dev/lib/python3.10/site-packages (from torch>=1.9->-r requirements.txt (line 1)) (11.7.101)
Requirement already satisfied: nvidia-curand-cu11==10.2.10.91 in /home/matteo/anaconda3/envs/monai_dev/lib/python3.10/site-packages (from torch>=1.9->-r requirements.txt (line 1)) (10.2.10.91)
Requirement already satisfied: wheel in /usr/lib/python3/dist-packages (from nvidia-cublas-cu11==11.10.3.66->torch>=1.9->-r requirements.txt (line 1)) (0.37.1)
Requirement already satisfied: lit in /home/matteo/anaconda3/envs/monai_dev/lib/python3.10/site-packages (from triton==2.0.0->torch>=1.9->-r requirements.txt (line 1)) (16.0.6)
Requirement already satisfied: cmake in /home/matteo/anaconda3/envs/monai_dev/lib/python3.10/site-packages (from triton==2.0.0->torch>=1.9->-r requirements.txt (line 1)) (3.26.4)
Requirement already satisfied: MarkupSafe>=2.0 in /home/matteo/anaconda3/envs/monai_dev/lib/python3.10/site-packages (from jinja2->torch>=1.9->-r requirements.txt (line 1)) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in /home/matteo/anaconda3/envs/monai_dev/lib/python3.10/site-packages (from sympy->torch>=1.9->-r requirements.txt (line 1)) (1.3.0)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 59.6.0
    Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /home/matteo/anaconda3/envs/monai_dev
    Can't uninstall 'setuptools'. No files were found to uninstall.
Successfully installed setuptools-67.8.0
```

**Comment by matt3o** [comment]
Update: I figured out pip freeze does not show the actual package (needs the --all flag). Removing the Ubuntu system package python3-setuptools appears to fix the problem - now the setup.py runs as expected.
So it either has to be related to the version setuptools 59.6.0 or to the Ubuntu package of that..
@wyli  Thanks for your help, I think we can close the issue then
