### ISSUE TITLE
PerceptualLoss rate limit exceeded

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#6824]
**Describe the bug**
```
[2023-08-05T01:07:49.325Z] ======================================================================
[2023-08-05T01:07:49.325Z] ERROR: test_identical_input_2 (tests.test_perceptual_loss.TestPerceptualLoss)
[2023-08-05T01:07:49.325Z] ----------------------------------------------------------------------
[2023-08-05T01:07:49.325Z] Traceback (most recent call last):
[2023-08-05T01:07:49.325Z]   File "/usr/local/lib/python3.8/dist-packages/parameterized/parameterized.py", line 620, in standalone_func
[2023-08-05T01:07:49.325Z]     return func(*(a + p.args), **p.kwargs, **kw)
[2023-08-05T01:07:49.325Z]   File "/home/jenkins/agent/workspace/Monai-pytorch-versions/tests/test_perceptual_loss.py", line 62, in test_identical_input
[2023-08-05T01:07:49.325Z]     loss = PerceptualLoss(**input_param)
[2023-08-05T01:07:49.325Z]   File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/losses/perceptual.py", line 107, in __init__
[2023-08-05T01:07:49.326Z]     self.perceptual_function = RadImageNetPerceptualSimilarity(net=network_type, verbose=False)
[2023-08-05T01:07:49.326Z]   File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/losses/perceptual.py", line 257, in __init__
[2023-08-05T01:07:49.326Z]     self.model = torch.hub.load("Warvito/radimagenet-models", model=net, verbose=verbose)
[2023-08-05T01:07:49.326Z]   File "/usr/local/lib/python3.8/dist-packages/torch/hub.py", line 539, in load
[2023-08-05T01:07:49.326Z]     repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, trust_repo, "load",
[2023-08-05T01:07:49.326Z]   File "/usr/local/lib/python3.8/dist-packages/torch/hub.py", line 203, in _get_cache_or_reload
[2023-08-05T01:07:49.326Z]     _validate_not_a_forked_repo(repo_owner, repo_name, ref)
[2023-08-05T01:07:49.326Z]   File "/usr/local/lib/python3.8/dist-packages/torch/hub.py", line 162, in _validate_not_a_forked_repo
[2023-08-05T01:07:49.326Z]     response = json.loads(_read_url(Request(url, headers=headers)))
[2023-08-05T01:07:49.326Z]   File "/usr/local/lib/python3.8/dist-packages/torch/hub.py", line 145, in _read_url
[2023-08-05T01:07:49.326Z]     with urlopen(url) as r:
[2023-08-05T01:07:49.326Z]   File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
[2023-08-05T01:07:49.326Z]     return opener.open(url, data, timeout)
[2023-08-05T01:07:49.326Z]   File "/usr/lib/python3.8/urllib/request.py", line 531, in open
[2023-08-05T01:07:49.326Z]     response = meth(req, response)
[2023-08-05T01:07:49.326Z]   File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
[2023-08-05T01:07:49.326Z]     response = self.parent.error(
[2023-08-05T01:07:49.326Z]   File "/usr/lib/python3.8/urllib/request.py", line 569, in error
[2023-08-05T01:07:49.326Z]     return self._call_chain(*args)
[2023-08-05T01:07:49.326Z]   File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
[2023-08-05T01:07:49.326Z]     result = func(*args)
[2023-08-05T01:07:49.326Z]   File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
[2023-08-05T01:07:49.326Z]     raise HTTPError(req.full_url, code, msg, hdrs, fp)
[2023-08-05T01:07:49.326Z] urllib.error.HTTPError: HTTP Error 403: rate limit exceeded
[2023-08-05T01:07:49.326Z] 
```

**Comment by wyli** [comment]
included workaround https://github.com/Project-MONAI/MONAI/pull/6827/commits/52f04932f2ca9b5590f062315505f8c93ec866d1
