### ISSUE TITLE
update base image to 23.08

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#6920]
**Is your feature request related to a problem? Please describe.**
would be great to use the latest base image
https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch/tags

cc @Nic-Ma

**Comment by wyli** [comment]
```
[2023-08-31T22:02:43.905Z] ======================================================================
[2023-08-31T22:02:43.905Z] ERROR: test_correct_results_1 (tests.test_deepgrow_transforms.TestRestoreLabeld)
[2023-08-31T22:02:43.905Z] ----------------------------------------------------------------------
[2023-08-31T22:02:43.905Z] Traceback (most recent call last):
[2023-08-31T22:02:43.905Z]   File "/usr/local/lib/python3.10/dist-packages/parameterized/parameterized.py", line 620, in standalone_func
[2023-08-31T22:02:43.905Z]     return func(*(a + p.args), **p.kwargs, **kw)
[2023-08-31T22:02:43.905Z]   File "/home/jenkins/agent/workspace/Monai-latest-image/tests/test_deepgrow_transforms.py", line 440, in test_correct_results
[2023-08-31T22:02:43.905Z]     result = RestoreLabeld(**arguments)(input_data)
[2023-08-31T22:02:43.905Z]   File "/home/jenkins/agent/workspace/Monai-latest-image/monai/apps/deepgrow/transforms.py", line 874, in __call__
[2023-08-31T22:02:43.905Z]     result = resizer(result, mode=mode, align_corners=align_corners)  # type: ignore
[2023-08-31T22:02:43.905Z]   File "/home/jenkins/agent/workspace/Monai-latest-image/monai/transforms/spatial/array.py", line 838, in __call__
[2023-08-31T22:02:43.905Z]     return resize(  # type: ignore
[2023-08-31T22:02:43.905Z]   File "/home/jenkins/agent/workspace/Monai-latest-image/monai/transforms/spatial/functional.py", line 335, in resize
[2023-08-31T22:02:43.905Z]     resized = torch.nn.functional.interpolate(
[2023-08-31T22:02:43.905Z]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py", line 3934, in interpolate
[2023-08-31T22:02:43.905Z]     raise TypeError(
[2023-08-31T22:02:43.905Z] TypeError: expected size to be one of int or Tuple[int] or Tuple[int, int] or Tuple[int, int, int], but got size with types [<class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>]
[2023-08-31T22:02:43.905Z] 
[2023-08-31T22:02:43.905Z] ----------------------------------------------------------------------
```

**Comment by Nic-Ma** [comment]
23.08 would be necessary for other projects.

Thanks.
