### ISSUE TITLE
Bundle download failed

### ISSUE THREAD

**Issue by KumoLiu** [Project-MONAI/MONAI#6962]
```
wholeBody_ct_segmentation_v0.2.0.zip: 0.00B [00:00, ?B/s]2023-09-08 09:26:43,546 - ERROR - Download failed from https://api.ngc.nvidia.com/v2/models/nvidia/monaihosting/wholeBody_ct_segmentation/versions/0.2.0/files/wholeBody_ct_segmentation_v0.2.0.zip to /tmp/tmprgid_gmj/wholeBody_ct_segmentation_v0.2.0.zip.
17:26:50  
17:26:50  Traceback (most recent call last):
17:26:50    File "ci/verify_tensorrt.py", line 109, in <module>
17:26:50      verify_all_tensorrt_bundles()
17:26:50    File "ci/verify_tensorrt.py", line 72, in verify_all_tensorrt_bundles
17:26:50      export_context = get_export_required_files(bundle, download_path)
17:26:50    File "ci/verify_tensorrt.py", line 44, in get_export_required_files
17:26:50      download_latest_bundle(bundle_name=bundle, models_path="models", download_path=download_path)
17:26:50    File "/home/jenkins/agent/workspace/model-zoo-weekly/ci/download_latest_bundle.py", line 24, in download_latest_bundle
17:26:50      download(name=bundle_name, source="monaihosting", version=version, bundle_dir=download_path)
17:26:50    File "/usr/local/lib/python3.8/dist-packages/monai/bundle/scripts.py", line 362, in download
17:26:50      _download_from_monaihosting(download_path=bundle_dir_, filename=name_, version=version_, progress=progress_)
17:26:50    File "/usr/local/lib/python3.8/dist-packages/monai/bundle/scripts.py", line 178, in _download_from_monaihosting
17:26:50      download_url(url=url, filepath=filepath, hash_val=None, progress=progress)
17:26:50    File "/usr/local/lib/python3.8/dist-packages/monai/apps/utils.py", line 219, in download_url
17:26:50      _download_with_progress(url, tmp_name, progress=progress)
17:26:50    File "/usr/local/lib/python3.8/dist-packages/monai/apps/utils.py", line 119, in _download_with_progress
17:26:50      raise e
17:26:50    File "/usr/local/lib/python3.8/dist-packages/monai/apps/utils.py", line 112, in _download_with_progress
17:26:50      urlretrieve(url, filepath, reporthook=t.update_to)
17:26:50    File "/usr/lib/python3.8/urllib/request.py", line 247, in urlretrieve
17:26:50      with contextlib.closing(urlopen(url, data)) as fp:
17:26:50    File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
17:26:50      return opener.open(url, data, timeout)
17:26:50    File "/usr/lib/python3.8/urllib/request.py", line 531, in open
17:26:50      response = meth(req, response)
17:26:50    File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
17:26:50      response = self.parent.error(
17:26:50    File "/usr/lib/python3.8/urllib/request.py", line 569, in error
17:26:50      return self._call_chain(*args)
17:26:50    File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
17:26:50      result = func(*args)
17:26:50    File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
17:26:50      raise HTTPError(req.full_url, code, msg, hdrs, fp)
17:26:50  urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by yiheng-wang-nv** [comment]
Reopen this issue.
The actual issue is that ngc hosting requires to use lowercase on models to be created.
For a model, all files it include do not have the lowercase restriction.
For example, we prepared:
```
https://api.ngc.nvidia.com/v2/models/nvidia/monaihosting/wholebody_ct_segmentation/versions/0.2.0/files/wholeBody_ct_segmentation_v0.2.0.zip
```
You can also refer to the source code of uploading bundles in model zoo:
https://github.com/Project-MONAI/model-zoo/blob/de0a2f94ccb65ee5601b6c272decb059a40daee9/ci/utils.py#L188

I will create a new PR to address the issue.
