### ISSUE TITLE
`test_bundle_download` error

### ISSUE THREAD

**Issue by KumoLiu** [Project-MONAI/MONAI#7005]
```
08:28:55  ======================================================================
08:28:55  ERROR: test_github_download_bundle_0_test_bundle (tests.test_bundle_download.TestDownload)
08:28:55  ----------------------------------------------------------------------
08:28:55  Traceback (most recent call last):
08:28:55    File "/home/jenkins/agent/workspace/Monai-pytorch-versions/tests/utils.py", line 818, in command_line_tests
08:28:55      normal_out = subprocess.run(cmd, env=test_env, check=True, capture_output=True)
08:28:55    File "/usr/lib/python3.8/subprocess.py", line 516, in run
08:28:55      raise CalledProcessError(retcode, process.args,
08:28:55  subprocess.CalledProcessError: Command '['coverage', 'run', '-m', 'monai.bundle', 'download', '--name', 'test_bundle', '--source', 'github', '--bundle_dir', '/tmp/tmpkb8hqx9m', '--repo', 'Project-MONAI/MONAI-extra-test-data/0.8.1']' returned non-zero exit status 1.
08:28:55  
08:28:55  The above exception was the direct cause of the following exception:
08:28:55  
08:28:55  Traceback (most recent call last):
08:28:55    File "/usr/local/lib/python3.8/dist-packages/parameterized/parameterized.py", line 620, in standalone_func
08:28:55      return func(*(a + p.args), **p.kwargs, **kw)
08:28:55    File "/home/jenkins/agent/workspace/Monai-pytorch-versions/tests/test_bundle_download.py", line 98, in test_github_download_bundle
08:28:55      command_line_tests(cmd)
08:28:55    File "/home/jenkins/agent/workspace/Monai-pytorch-versions/tests/utils.py", line 823, in command_line_tests
08:28:55      raise RuntimeError(f"subprocess call error {e.returncode}: {errors}, {output}") from e
08:28:55  RuntimeError: subprocess call error 1: b'Traceback (most recent call last):
08:28:55    File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/bundle/__main__.py", line 31, in <module>
08:28:55      fire.Fire()
08:28:55    File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 141, in Fire
08:28:55      component_trace = _Fire(component, args, parsed_flag_args, context, name)
08:28:55    File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 475, in _Fire
08:28:55      component, remaining_args = _CallAndUpdateTrace(
08:28:55    File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 691, in _CallAndUpdateTrace
08:28:55      component = fn(*varargs, **kwargs)
08:28:55    File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/bundle/scripts.py", line 357, in download
08:28:55      version_ = _get_latest_bundle_version(source=source_, name=name_, repo=repo_)
08:28:55    File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/bundle/scripts.py", line 234, in _get_latest_bundle_version
08:28:55      return get_bundle_versions(name, repo=f"{repo_owner}/{repo_name}", tag=tag_name)["latest_version"]
08:28:55    File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/bundle/scripts.py", line 653, in get_bundle_versions
08:28:55      bundles_info = _get_all_bundles_info(repo=repo, tag=tag, auth_token=auth_token)
08:28:55    File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/utils/deprecate_utils.py", line 323, in _wrapper
08:28:55      return func(*args, **kwargs)
08:28:55    File "/home/jenkins/agent/workspace/Monai-pytorch-versions/monai/bundle/scripts.py", line 559, in _get_all_bundles_info
08:28:55      resp.raise_for_status()
08:28:55    File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 1021, in raise_for_status
08:28:55      raise HTTPError(http_error_msg, response=self)
08:28:55  requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/Project-MONAI/MONAI-extra-test-data/0.8.1/models/model_info.json
08:28:55  ', b"name test_bundle
```

**Comment by KumoLiu** [comment]
Fixed by https://github.com/Project-MONAI/MONAI-extra-test-data/pull/16.
