### ISSUE TITLE
decollate_batch case the error when the transforms' chain try to update its applied_opreations list

### ISSUE THREAD

**Issue by LuZWCHA** [Project-MONAI/MONAI#7007]
The Error `AttributeError: 'dict' object has no attribute 'append'`  were throwed when I ran my postprocess codes:
```python
post_pred=Compose(
        [EnsureType(),   Resize(spatial_size=512, size_mode="longest", mode="nearest")]
  )
...
preds = modle(inputs)
val_seg_logits = [post_pred(i) for i in decollate_batch(preds)]
...
```

The key lines in the "Exception" is following:
```bash
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.10/site-packages/monai/transforms/transform.py", line 141, in apply_transform
    return _apply_transform(transform, data, unpack_items, lazy, overrides, log_stats)
  File "/root/anaconda3/lib/python3.10/site-packages/monai/transforms/transform.py", line 98, in _apply_transform
    return transform(data, lazy=lazy) if isinstance(transform, LazyTrait) else transform(data)
  File "/root/anaconda3/lib/python3.10/site-packages/monai/transforms/spatial/array.py", line 837, in __call__
    return resize(  # type: ignore
  File "/root/anaconda3/lib/python3.10/site-packages/monai/transforms/spatial/functional.py", line 303, in resize
    meta_info = TraceableTransform.track_transform_meta(
  File "/root/anaconda3/lib/python3.10/site-packages/monai/transforms/inverse.py", line 248, in track_transform_meta
    out_obj.push_applied_operation(info)
  File "/root/anaconda3/lib/python3.10/site-packages/monai/data/meta_obj.py", line 205, in push_applied_operation
    self._applied_operations.append(t)
AttributeError: 'dict' object has no attribute 'append'

The above exception was the direct cause of the following exception:
...
RuntimeError: applying transform <monai.transforms.spatial.array.Resize object at 0x7fc16c1844c0>
...
```
The following codes are from monai.data.utils.decollate_batch:
```python
for t, m in zip(out_list, batch.applied_operations):
      if isinstance(t, MetaObj):
            t.applied_operations = m
            t.is_batch = False
```
The batch's applied_operations is a list of operations. When the out_list rebuilding the applied_operations, it cast to a "`dict`" operations(t.applied_operations is a `list`, but m is a `dict`), these codes break the logic of downstream.

**Comment by wyli** [comment]
I couldn't replicate it with this script, could you help create an example based on this script to demonstrate the issue?

```py
import monai.transforms as mt
from monai.data import DataLoader, Dataset, create_test_image_3d, decollate_batch
from monai.utils import set_determinism
from tests.utils import make_nifti_image

set_determinism(seed=0)
im_fname = make_nifti_image(create_test_image_3d(101, 100, 107, noise_max=100)[1])  # label image, discrete
data = [im_fname for _ in range(12)]
transform = mt.Compose(
    [
        mt.LoadImage(image_only=True, ensure_channel_first=True),
        mt.Orientation("RPS"),
        mt.Spacing(pixdim=(1.2, 1.01, 0.9), mode=1, dtype=float),
        mt.RandFlip(prob=0.5, spatial_axis=[1, 2]),
        mt.RandAxisFlip(prob=0.5),
        mt.RandRotate90(prob=0, spatial_axes=(1, 2)),
        mt.RandZoom(prob=0.5, min_zoom=0.5, max_zoom=1.1, keep_size=True),
        mt.ResizeWithPadOrCrop(100),
        mt.RandSpatialCropSamples(roi_size=96, num_samples=4, random_size=False),
    ]
)
post_pred = mt.Compose([mt.EnsureType(), mt.Resize(spatial_size=200, size_mode="longest", mode="nearest")])

dataset = Dataset(data, transform=transform)
loader = DataLoader(dataset, batch_size=2)

for d in loader:
    d = decollate_batch(d)
    for item in d:
        output = post_pred(item)
        print(output.shape)
```

**Comment by LuZWCHA** [comment]
Thank you. I found that this bug was simply caused by some oversight when using the `torch`'s `DataLoader`. When I replaced the DataLoader with the `monai`'s `DataLoader`, the issue disappeared. But, is it nessary that I must use the `Dataloader` when using the `transforms` of the `monai`(only simple resize, flip and so on).

**Comment by wyli** [comment]
sure, you can also deal with the regular tensor after data loading, but in this case all the metadata and information about the previously applied operations are dropped:
```py
for d in loader:
    if isinstance(d, monai.data.MetaTensor):
        d = d.as_subclass(torch.Tensor)
    d = decollate_batch(d)
```
