### ISSUE TITLE
test_dataset_tracking

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#7036]
```
[2023-09-22T18:59:24.123Z] ======================================================================
[2023-09-22T18:59:24.123Z] ERROR: test_dataset_tracking (tests.test_handler_mlflow.TestHandlerMLFlow)
[2023-09-22T18:59:24.123Z] ----------------------------------------------------------------------
[2023-09-22T18:59:24.123Z] Traceback (most recent call last):
[2023-09-22T18:59:24.123Z]   File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/bundle/config_item.py", line 293, in instantiate
[2023-09-22T18:59:24.123Z]     return instantiate(modname, mode, **args)
[2023-09-22T18:59:24.123Z]   File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/utils/module.py", line 248, in instantiate
[2023-09-22T18:59:24.123Z]     raise ModuleNotFoundError(f"Cannot locate class or function path: '{__path}'.")
[2023-09-22T18:59:24.123Z] ModuleNotFoundError: Cannot locate class or function path: 'AsChannelFirstd'.
[2023-09-22T18:59:24.123Z] 
[2023-09-22T18:59:24.123Z] The above exception was the direct cause of the following exception:
[2023-09-22T18:59:24.123Z] 
[2023-09-22T18:59:24.123Z] Traceback (most recent call last):
[2023-09-22T18:59:24.123Z]   File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/tests/test_handler_mlflow.py", line 271, in test_dataset_tracking
[2023-09-22T18:59:24.123Z]     infer_dataset = workflow.dataset
[2023-09-22T18:59:24.123Z]   File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/bundle/workflows.py", line 129, in __getattr__
[2023-09-22T18:59:24.123Z]     return self._get_property(name=name, property=self.properties[name])
[2023-09-22T18:59:24.123Z]   File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/bundle/workflows.py", line 365, in _get_property
[2023-09-22T18:59:24.123Z]     return self.parser.get_parsed_content(id=prop_id) if prop_id is not None else None
[2023-09-22T18:59:24.124Z]   File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/bundle/config_parser.py", line 290, in get_parsed_content
[2023-09-22T18:59:24.124Z]     return self.ref_resolver.get_resolved_content(id=id, **kwargs)
[2023-09-22T18:59:24.124Z]   File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/bundle/reference_resolver.py", line 193, in get_resolved_content
[2023-09-22T18:59:24.124Z]     return self._resolve_one_item(id=id, **kwargs)
[2023-09-22T18:59:24.124Z]   File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/bundle/reference_resolver.py", line 163, in _resolve_one_item
[2023-09-22T18:59:24.124Z]     self._resolve_one_item(id=d, waiting_list=waiting_list, **kwargs)
[2023-09-22T18:59:24.124Z]   File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/bundle/reference_resolver.py", line 163, in _resolve_one_item
[2023-09-22T18:59:24.124Z]     self._resolve_one_item(id=d, waiting_list=waiting_list, **kwargs)
[2023-09-22T18:59:24.124Z]   File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/bundle/reference_resolver.py", line 171, in _resolve_one_item
[2023-09-22T18:59:24.124Z]     self.resolved_content[id] = item.instantiate() if kwargs.get("instantiate", True) else item
[2023-09-22T18:59:24.124Z]   File "/home/jenkins/agent/workspace/MONAI-postmerge/monai_github/monai/bundle/config_item.py", line 295, in instantiate
[2023-09-22T18:59:24.124Z]     raise RuntimeError(f"Failed to instantiate {self}") from e
[2023-09-22T18:59:24.124Z] RuntimeError: Failed to instantiate ConfigComponent: 
[2023-09-22T18:59:24.124Z] {'_target_': 'AsChannelFirstd', 'keys': ['image']}
[2023-09-22T18:59:24.124Z] 
[2023-09-22T18:59:24.124Z] ----------------------------------------------------------------------
```

**Comment by wyli** [comment]
this test case might need an update @KumoLiu before closing this ticket @KumoLiu? https://github.com/Project-MONAI/MONAI/blob/e4dbfdeb6778e399909226843e89f62deb546460/tests/test_handler_mlflow.py#L243-L245
