### ISSUE TITLE
Bug in SwinUNETR

### ISSUE THREAD

**Issue by dmus** [Project-MONAI/MONAI#7149]
**Describe the bug**
I can not run the following code  without an error

**To Reproduce**
```
import torch
import numpy as np
from monai.networks.nets import SwinUNETR

net = SwinUNETR(img_size=(96,96,96), in_channels=1, out_channels=4, feature_size=48)
my_input = np.random.rand(2, 1, 96, 96, 96)

prediction = net.forward(my_input)
```
```
The error is 
Traceback (most recent call last):
  File "/home/derk/rndeep/rndeep/Models/Keras/swinunetr.py", line 30, in <module>
    prediction = net.forward(my_input)
  File "/home/derk/rndeep/venv/lib/python3.10/site-packages/monai/networks/nets/swin_unetr.py", line 325, in forward
    hidden_states_out = self.swinViT(x_in, self.normalize)
  File "/home/derk/rndeep/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/derk/rndeep/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/derk/rndeep/venv/lib/python3.10/site-packages/monai/networks/nets/swin_unetr.py", line 1062, in forward
    x0 = self.patch_embed(x)
  File "/home/derk/rndeep/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/derk/rndeep/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/derk/rndeep/venv/lib/python3.10/site-packages/monai/networks/blocks/patchembedding.py", line 199, in forward
    x_shape = x.size()
TypeError: 'int' object is not callable
```

**Expected behavior**
No error

**Environment**

Ensuring you use the relevant python executable, please paste the output of:

```
python -c 'import monai; monai.config.print_debug_info()'
```

2023-10-20 11:50:50.207615: I tensorflow/core/util/port.cc:111] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-10-20 11:50:50.250986: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-10-20 11:50:50.251035: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-10-20 11:50:50.251069: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-10-20 11:50:50.260116: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-20 11:50:50.949429: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
================================
Printing MONAI config...
================================
MONAI version: 1.3.0
Numpy version: 1.26.1
Pytorch version: 2.1.0+cu118
MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
MONAI rev id: 865972f7a791bf7b42efbcd87c8402bd865b329e
MONAI __file__: /home/<username>/rndeep/venv/lib/python3.10/site-packages/monai/__init__.py

Optional dependencies:
Pytorch Ignite version: NOT INSTALLED or UNKNOWN VERSION.
ITK version: NOT INSTALLED or UNKNOWN VERSION.
Nibabel version: 5.1.0
scikit-image version: 0.22.0
scipy version: 1.11.3
Pillow version: 10.1.0
Tensorboard version: 2.14.1
gdown version: NOT INSTALLED or UNKNOWN VERSION.
TorchVision version: 0.16.0+cu118
tqdm version: 4.66.1
lmdb version: NOT INSTALLED or UNKNOWN VERSION.
psutil version: 5.9.6
pandas version: 2.1.1
einops version: 0.7.0
transformers version: NOT INSTALLED or UNKNOWN VERSION.
mlflow version: NOT INSTALLED or UNKNOWN VERSION.
pynrrd version: 1.0.0
clearml version: 1.13.1

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

================================
Printing system config...
================================
System: Linux
Linux version: Ubuntu 22.04.3 LTS
Platform: Linux-5.15.0-84-generic-x86_64-with-glibc2.35
Processor: x86_64
Machine: x86_64
Python version: 3.10.12
Process name: python
Command: ['python', '-c', 'import monai; monai.config.print_debug_info()']
Open files: [popenfile(path='/home/derk/.vscode-server/data/logs/20231020T103336/ptyhost.log', fd=19, position=1912, mode='a', flags=33793), popenfile(path='/home/derk/.vscode-server/data/logs/20231020T103336/remoteagent.log', fd=20, position=659, mode='a', flags=33793), popenfile(path='/home/derk/.vscode-server/data/logs/20231020T103336/network.log', fd=24, position=0, mode='a', flags=33793), popenfile(path='/home/derk/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/vscode-remote-lock.derk.f1b07bd25dfad64b0167beb15359ae573aecd2cc', fd=99, position=0, mode='w', flags=32769)]
Num physical CPUs: 32
Num logical CPUs: 64
Num usable CPUs: 64
CPU usage (%): [4.1, 3.5, 3.8, 5.0, 3.5, 3.8, 4.7, 3.5, 4.4, 4.7, 3.8, 4.1, 4.1, 4.1, 3.8, 3.8, 3.8, 3.5, 4.1, 4.7, 3.5, 3.5, 3.5, 3.8, 3.8, 3.5, 3.5, 3.8, 3.8, 3.8, 3.5, 3.8, 3.5, 98.4, 3.8, 5.7, 3.8, 5.7, 3.8, 3.8, 3.8, 3.8, 4.1, 4.1, 4.4, 3.8, 3.5, 3.8, 3.8, 3.5, 3.5, 3.8, 3.5, 3.5, 3.8, 4.1, 3.8, 3.8, 3.5, 3.5, 3.5, 3.8, 4.1, 10.1]
CPU freq. (MHz): 2280
Load avg. in last 1, 5, 15 mins (%): [0.7, 0.6, 0.5]
Disk usage (%): 82.8
Avg. sensor temp. (Celsius): UNKNOWN for given OS
Total physical memory (GB): 755.3
Available memory (GB): 738.4
Used memory (GB): 12.3

================================
Printing GPU config...
================================
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/derk/rndeep/venv/lib/python3.10/site-packages/monai/config/deviceconfig.py", line 261, in print_debug_info
    print_gpu_info(file)
  File "/home/derk/rndeep/venv/lib/python3.10/site-packages/monai/config/deviceconfig.py", line 239, in print_gpu_info
    for k, v in get_gpu_info().items():
  File "/home/derk/rndeep/venv/lib/python3.10/site-packages/monai/config/deviceconfig.py", line 208, in get_gpu_info
    cudnn_ver = torch.backends.cudnn.version()
  File "/home/derk/rndeep/venv/lib/python3.10/site-packages/torch/backends/cudnn/__init__.py", line 82, in version
    if not _init():
  File "/home/derk/rndeep/venv/lib/python3.10/site-packages/torch/backends/cudnn/__init__.py", line 58, in _init
    raise RuntimeError(
RuntimeError: cuDNN version incompatibility: PyTorch was compiled  against (8, 7, 0) but found runtime version (8, 6, 0). PyTorch already comes bundled with cuDNN. One option to resolving this error is to ensure PyTorch can find the bundled cuDNN.Looks like your LD_LIBRARY_PATH contains incompatible version of cudnnPlease either remove it from the path or install cudnn (8, 7, 0)

**Comment by wyli** [comment]
Hi @dmus  I think the network module expects a tensor input, but in this case it's a numpy array.
