### ISSUE TITLE
runtime error trying to resize storage that is not resizable

### ISSUE THREAD

**Issue by SnoopyXI** [Project-MONAI/MONAI#7171]
I don't know this a bug or an problem:
runtime error trying to resize storage that is not resizable

**Comment by KumoLiu** [comment]
Hi @SnoopyXI, could you please share more details such as a small piece code that can reproduce the error, MONAI version?

**Comment by wyli** [comment]
I'm curious about this, I saw similar logs here https://github.com/Project-MONAI/MONAI/issues/6901 but didn't have the data to replicate the issue.

**Comment by SnoopyXI** [comment]
> Hi @SnoopyXI, could you please share more details such as a small piece code that can reproduce the error, MONAI version?

E: stack expects each tensor to be equal size, but got [3, 224, 224] at entry 0 and [3, 224, 223] at entry 6, shape [torch.Size([3, 224, 224]), torch.Size([3, 224, 224]), torch.Size([3, 224, 224]), torch.Size([3, 224, 224]), torch.Size([3, 224, 224]), torch.Size([3, 224, 224]), torch.Size([3, 224, 223]), torch.Size([3, 224, 224]), torch.Size([3, 224, 224]), torch.Size([3, 224, 224]), torch.Size([3, 224, 224]), torch.Size([3, 224, 224])] in collate([metatensor([[[0.5941, 0.6067, 0.6276,  ..., 0.6611, 0.7113, 0.7364],
         [0.6820, 0.6778, 0.6736,  ..., 0.6862, 0.7280, 0.7490],
         [0.7657, 0.7490, 0.7197,  ..., 0.7113, 0.7406, 0.7448],
         ...,
         [0.4812, 0.4059, 0.3054,  ..., 0.7197, 0.7280, 0.7322],
         [0.5105, 0.4477, 0.3640,  ..., 0.7782, 0.7615, 0.7615],
         [0.5230, 0.4812, 0.4184,  ..., 0.7657, 0.7531, 0.7573]],

        [[0.5230, 0.4979, 0.4770,  ..., 0.3473, 0.3724, 0.3891],
         [0.5900, 0.5565, 0.5146,  ..., 0.3640, 0.3891, 0.4017],
         [0.6444, 0.6025, 0.5523,  ..., 0.3766, 0.4017, 0.4059],
         ...,
         [0.1967, 0.1715, 0.1381,  ..., 0.4728, 0.4686, 0.4561],
         [0.2134, 0.1925, 0.1590,  ..., 0.5397, 0.5146, 0.4812],
         [0.2552, 0.2385, 0.2134,  ..., 0.5356, 0.5105, 0.4854]],

        [[0.7113, 0.6946, 0.6778,  ..., 0.6360, 0.6527, 0.6736],
         [0.7531, 0.7406, 0.7280,  ..., 0.6569, 0.6695, 0.6862],
         [0.7741, 0.7699, 0.7615,  ..., 0.6736, 0.6820, 0.6820],
         ...,
         [0.5021, 0.4770, 0.4435,  ..., 0.6736, 0.6653, 0.6569],
         [0.5314, 0.5146, 0.4979,  ..., 0.7197, 0.7071, 0.6946],
         [0.5649, 0.5607, 0.5523,  ..., 0.7113, 0.7113, 0.7113]]]), metatensor([[[0.3808, 0.3933, 0.4059,  ..., 0.4561, 0.4268, 0.4184],
         [0.4017, 0.3933, 0.3975,  ..., 0.3556, 0.3264, 0.3054],
         [0.4184, 0.4100, 0.4059,  ..., 0.2552, 0.2259, 0.2176],
         ...,
         [0.3766, 0.3975, 0.4477,  ..., 0.2008, 0.1841, 0.1841],
         [0.4142, 0.4310, 0.4561,  ..., 0.1674, 0.1548, 0.1841],
         [0.4728, 0.4644, 0.4644,  ..., 0.1464, 0.1506, 0.2008]],

        [[0.2008, 0.2008, 0.2134,  ..., 0.3556, 0.3473, 0.3431],
         [0.2134, 0.2134, 0.2301,  ..., 0.2427, 0.2469, 0.2552],
         [0.2301, 0.2301, 0.2427,  ..., 0.1590, 0.1674, 0.1841],
         ...,
         [0.2092, 0.2259, 0.2594,  ..., 0.1130, 0.1088, 0.1172],
         [0.2343, 0.2427, 0.2678,  ..., 0.1004, 0.0837, 0.0879],
         [0.2678, 0.2678, 0.2762,  ..., 0.0879, 0.0795, 0.1046]],

        [[0.4979, 0.5021, 0.5146,  ..., 0.6820, 0.6862, 0.6946],
         [0.5021, 0.5105, 0.5230,  ..., 0.5732, 0.5858, 0.5983],
         [0.5105, 0.5188, 0.5230,  ..., 0.4854, 0.4895, 0.5063],
         ...,
         [0.5063, 0.5188, 0.5481,  ..., 0.3849, 0.3682, 0.3808],
         [0.5230, 0.5314, 0.5481,  ..., 0.3640, 0.3682, 0.4142],
         [0.5439, 0.5523, 0.5565,  ..., 0.3473, 0.3766, 0.4393]]]), metatensor([[[0.1590, 0.1674, 0.1674,  ..., 0.6653, 0.6192, 0.5523],
         [0.1967, 0.1841, 0.1674,  ..., 0.6025, 0.5900, 0.5607],
         [0.2218, 0.2050, 0.1757,  ..., 0.6360, 0.6192, 0.5900],
         ...,
         [0.1172, 0.1464, 0.1799,  ..., 0.5649, 0.5774, 0.5732],
         [0.1339, 0.1674, 0.1883,  ..., 0.5356, 0.5565, 0.5607],
         [0.2427, 0.2427, 0.2469,  ..., 0.5439, 0.5649, 0.5690]],

        [[0.0669, 0.0628, 0.0544,  ..., 0.3347, 0.3180, 0.2762],
         [0.0837, 0.0753, 0.0460,  ..., 0.3096, 0.2971, 0.2678],
         [0.0962, 0.0837, 0.0544,  ..., 0.3096, 0.2971, 0.2678],
         ...,
         [0.1046, 0.1297, 0.1632,  ..., 0.2720, 0.2845, 0.2803],
         [0.1757, 0.1967, 0.2134,  ..., 0.2552, 0.2720, 0.2636],
         [0.2427, 0.2427, 0.2343,  ..., 0.2636, 0.2803, 0.2720]],

        [[0.3264, 0.3389, 0.3431,  ..., 0.6109, 0.5858, 0.5439],
         [0.3640, 0.3473, 0.3138,  ..., 0.6109, 0.5983, 0.5607],
         [0.3891, 0.3598, 0.3222,  ..., 0.6234, 0.5983, 0.5690],
         ...,
         [0.3933, 0.3766, 0.3724,  ..., 0.5774, 0.5900, 0.5858],
         [0.5397, 0.5314, 0.5230,  ..., 0.5774, 0.5858, 0.5816],
         [0.6025, 0.6025, 0.5983,  ..., 0.5858, 0.5941, 0.5900]]]), metatensor([[[0.3891, 0.4059, 0.4059,  ..., 0.5439, 0.6109, 0.5983],
         [0.3891, 0.3556, 0.3347,  ..., 0.4686, 0.5523, 0.5607],
         [0.4017, 0.3556, 0.3054,  ..., 0.3933, 0.4895, 0.5063],
         ...,
         [0.6904, 0.7238, 0.7573,  ..., 0.5983, 0.5732, 0.5607],
         [0.6778, 0.6987, 0.7490,  ..., 0.5900, 0.5397, 0.5314],
         [0.6820, 0.6946, 0.7406,  ..., 0.6025, 0.5565, 0.5439]],

        [[0.2594, 0.3013, 0.3013,  ..., 0.2762, 0.2678, 0.2594],
         [0.2594, 0.2678, 0.2469,  ..., 0.2678, 0.2762, 0.2720],
         [0.2803, 0.2678, 0.2218,  ..., 0.2594, 0.2803, 0.2803],
         ...,
         [0.4435, 0.4770, 0.5314,  ..., 0.3347, 0.3222, 0.3222],
         [0.4351, 0.4770, 0.5314,  ..., 0.3347, 0.3222, 0.3222],
         [0.4477, 0.4854, 0.5314,  ..., 0.3264, 0.3180, 0.3096]],

        [[0.5439, 0.5439, 0.5397,  ..., 0.5858, 0.5774, 0.5397],
         [0.5523, 0.5063, 0.4854,  ..., 0.5774, 0.5774, 0.5439],
         [0.5565, 0.5063, 0.4686,  ..., 0.5649, 0.5774, 0.5397],
         ...,
         [0.6778, 0.7197, 0.7490,  ..., 0.6276, 0.6234, 0.6067],
         [0.6820, 0.7029, 0.7364,  ..., 0.6234, 0.6234, 0.6192],
         [0.7029, 0.7071, 0.7448,  ..., 0.6234, 0.6151, 0.6067]]]), metatensor([[[0.4894, 0.4936, 0.5021,  ..., 0.6426, 0.6638, 0.6766],
         [0.4511, 0.4426, 0.4723,  ..., 0.6085, 0.6255, 0.6383],
         [0.3957, 0.3830, 0.4255,  ..., 0.5617, 0.5702, 0.5787],
         ...,
         [0.5447, 0.5745, 0.5957,  ..., 0.5234, 0.5191, 0.5191],
         [0.5362, 0.5660, 0.5872,  ..., 0.5319, 0.5319, 0.5319],
         [0.5362, 0.5660, 0.5872,  ..., 0.5362, 0.5404, 0.5404]],

        [[0.2298, 0.2340, 0.2426,  ..., 0.3957, 0.4170, 0.4298],
         [0.2043, 0.1957, 0.2213,  ..., 0.3660, 0.3872, 0.4000],
         [0.1745, 0.1660, 0.2000,  ..., 0.3191, 0.3362, 0.3447],
         ...,
         [0.3277, 0.3617, 0.3915,  ..., 0.2979, 0.2936, 0.2936],
         [0.3234, 0.3532, 0.3787,  ..., 0.2851, 0.2851, 0.2851],
         [0.3234, 0.3532, 0.3660,  ..., 0.2681, 0.2723, 0.2723]],

        [[0.4809, 0.4851, 0.4851,  ..., 0.5660, 0.5787, 0.5915],
         [0.4638, 0.4468, 0.4681,  ..., 0.5404, 0.5532, 0.5660],
         [0.4468, 0.4170, 0.4383,  ..., 0.5106, 0.5149, 0.5234],
         ...,
         [0.5660, 0.5702, 0.5702,  ..., 0.4851, 0.4723, 0.4723],
         [0.5489, 0.5702, 0.5787,  ..., 0.4979, 0.4894, 0.4894],
         [0.5489, 0.5702, 0.5745,  ..., 0.5021, 0.4979, 0.4979]]]), metatensor([[[0.6426, 0.6383, 0.6681,  ..., 0.6340, 0.6553, 0.6681],
         [0.6340, 0.6255, 0.6383,  ..., 0.6723, 0.6894, 0.7021],
         [0.6255, 0.6170, 0.6043,  ..., 0.7064, 0.7277, 0.7362],
         ...,
         [0.3106, 0.2979, 0.2894,  ..., 0.6638, 0.6979, 0.7404],
         [0.2936, 0.2723, 0.2681,  ..., 0.6128, 0.6426, 0.6766],
         [0.2894, 0.2681, 0.2723,  ..., 0.5957, 0.6213, 0.6468]],

        [[0.3957, 0.4170, 0.4383,  ..., 0.3872, 0.4085, 0.4340],
         [0.3915, 0.3957, 0.4085,  ..., 0.4213, 0.4468, 0.4681],
         [0.3787, 0.3745, 0.3745,  ..., 0.4553, 0.4851, 0.5149],
         ...,
         [0.1234, 0.1319, 0.1191,  ..., 0.3915, 0.4340, 0.4809],
         [0.1234, 0.1149, 0.1064,  ..., 0.3574, 0.3915, 0.4340],
         [0.1191, 0.1234, 0.1234,  ..., 0.3574, 0.3830, 0.4213]],

        [[0.6426, 0.6213, 0.6511,  ..., 0.6383, 0.6553, 0.6766],
         [0.6255, 0.6085, 0.6213,  ..., 0.6681, 0.6809, 0.7021],
         [0.5957, 0.6000, 0.5957,  ..., 0.6851, 0.7021, 0.7234],
         ...,
         [0.3830, 0.3745, 0.3745,  ..., 0.6128, 0.6426, 0.6681],
         [0.3489, 0.3447, 0.3489,  ..., 0.5745, 0.5957, 0.6255],
         [0.3404, 0.3404, 0.3532,  ..., 0.5574, 0.5745, 0.6000]]]), metatensor([[[0.3106, 0.3277, 0.3489,  ..., 0.6894, 0.7489, 0.7745],
         [0.3064, 0.3191, 0.3277,  ..., 0.7404, 0.7957, 0.8170],
         [0.2979, 0.3021, 0.3149,  ..., 0.7915, 0.8298, 0.8511],
         ...,
         [0.4000, 0.4043, 0.4170,  ..., 0.7234, 0.7489, 0.7702],
         [0.4553, 0.4638, 0.4681,  ..., 0.7064, 0.7319, 0.7489],
         [0.4809, 0.4809, 0.4851,  ..., 0.7021, 0.7191, 0.7404]],

        [[0.1574, 0.1574, 0.1574,  ..., 0.5021, 0.5447, 0.5617],
         [0.1362, 0.1277, 0.1277,  ..., 0.5617, 0.6043, 0.6213],
         [0.1106, 0.1064, 0.1021,  ..., 0.6298, 0.6638, 0.6681],
         ...,
         [0.2170, 0.2298, 0.2426,  ..., 0.5447, 0.5574, 0.5702],
         [0.2468, 0.2596, 0.2638,  ..., 0.5106, 0.5319, 0.5404],
         [0.2553, 0.2553, 0.2638,  ..., 0.4894, 0.5064, 0.5191]],

        [[0.4170, 0.4255, 0.4511,  ..., 0.7191, 0.7574, 0.7702],
         [0.4000, 0.4043, 0.4170,  ..., 0.7574, 0.7872, 0.7872],
         [0.3787, 0.3830, 0.3957,  ..., 0.7872, 0.7957, 0.7872],
         ...,
         [0.4553, 0.4681, 0.4809,  ..., 0.7149, 0.7319, 0.7489],
         [0.4809, 0.4809, 0.4851,  ..., 0.7064, 0.7277, 0.7404],
         [0.4851, 0.4766, 0.4723,  ..., 0.6979, 0.7149, 0.7277]]]), metatensor([[[0.3489, 0.3830, 0.3872,  ..., 0.7234, 0.6936, 0.6638],
         [0.3404, 0.3660, 0.3830,  ..., 0.7447, 0.7149, 0.6936],
         [0.3319, 0.3574, 0.3745,  ..., 0.7617, 0.7319, 0.7149],
         ...,
         [0.7319, 0.7149, 0.7064,  ..., 0.5660, 0.5447, 0.5404],
         [0.7149, 0.6851, 0.6936,  ..., 0.5915, 0.5617, 0.5489],
         [0.6851, 0.6553, 0.6638,  ..., 0.6170, 0.5745, 0.5404]],

        [[0.1830, 0.1830, 0.1872,  ..., 0.4851, 0.4596, 0.4426],
         [0.1745, 0.1745, 0.1830,  ..., 0.5021, 0.4809, 0.4553],
         [0.1702, 0.1702, 0.1830,  ..., 0.5149, 0.4936, 0.4766],
         ...,
         [0.4596, 0.4340, 0.4213,  ..., 0.2681, 0.2723, 0.2979],
         [0.4511, 0.4213, 0.4128,  ..., 0.2894, 0.2894, 0.3064],
         [0.4255, 0.3957, 0.3787,  ..., 0.3064, 0.3064, 0.3106]],

        [[0.4085, 0.4128, 0.4085,  ..., 0.6426, 0.6255, 0.6085],
         [0.4085, 0.4170, 0.4170,  ..., 0.6383, 0.6170, 0.6043],
         [0.4128, 0.4213, 0.4255,  ..., 0.6170, 0.6000, 0.5915],
         ...,
         [0.6170, 0.5872, 0.6043,  ..., 0.5787, 0.5319, 0.5319],
         [0.6255, 0.5957, 0.6170,  ..., 0.5872, 0.5447, 0.5404],
         [0.6128, 0.5830, 0.5957,  ..., 0.6000, 0.5489, 0.5319]]]), metatensor([[[0.8341, 0.8122, 0.8035,  ..., 0.8079, 0.8035, 0.7904],
         [0.8428, 0.8253, 0.8210,  ..., 0.8166, 0.8122, 0.8079],
         [0.8384, 0.8253, 0.8210,  ..., 0.8341, 0.8341, 0.8253],
         ...,
         [0.6594, 0.6376, 0.6332,  ..., 0.8996, 0.8559, 0.8253],
         [0.6812, 0.6550, 0.6638,  ..., 0.8079, 0.8166, 0.8253],
         [0.6725, 0.6419, 0.6332,  ..., 0.7991, 0.8079, 0.8210]],

        [[0.5546, 0.5502, 0.5459,  ..., 0.3712, 0.3668, 0.3668],
         [0.5633, 0.5633, 0.5633,  ..., 0.3843, 0.3799, 0.3712],
         [0.5546, 0.5633, 0.5633,  ..., 0.3974, 0.3974, 0.3843],
         ...,
         [0.3319, 0.3319, 0.3493,  ..., 0.5371, 0.5197, 0.5240],
         [0.3581, 0.3406, 0.3319,  ..., 0.4934, 0.5197, 0.5502],
         [0.3493, 0.3319, 0.3275,  ..., 0.4847, 0.5066, 0.5240]],

        [[0.7817, 0.7773, 0.7817,  ..., 0.6856, 0.6812, 0.6769],
         [0.7904, 0.7904, 0.7991,  ..., 0.6769, 0.6725, 0.6769],
         [0.7904, 0.7991, 0.7991,  ..., 0.6681, 0.6769, 0.6725],
         ...,
         [0.6245, 0.6376, 0.6376,  ..., 0.7817, 0.7642, 0.7642],
         [0.6245, 0.6288, 0.6463,  ..., 0.7729, 0.7424, 0.7380],
         [0.6245, 0.6288, 0.6419,  ..., 0.7642, 0.7424, 0.7380]]]), metatensor([[[0.8253, 0.8035, 0.7773,  ..., 0.7598, 0.7249, 0.7031],
         [0.8384, 0.8210, 0.7860,  ..., 0.7511, 0.7162, 0.7118],
         [0.8428, 0.8341, 0.7948,  ..., 0.7336, 0.7074, 0.7074],
         ...,
         [0.8603, 0.8384, 0.8079,  ..., 0.8384, 0.8079, 0.7991],
         [0.8472, 0.8515, 0.7991,  ..., 0.8210, 0.8122, 0.8122],
         [0.8253, 0.8297, 0.7860,  ..., 0.8253, 0.8210, 0.8341]],

        [[0.5459, 0.5240, 0.5153,  ..., 0.4279, 0.4454, 0.4803],
         [0.5415, 0.5197, 0.5109,  ..., 0.4279, 0.4498, 0.4760],
         [0.5328, 0.5109, 0.4978,  ..., 0.4236, 0.4410, 0.4672],
         ...,
         [0.5677, 0.5240, 0.4847,  ..., 0.3712, 0.3581, 0.3624],
         [0.5371, 0.5066, 0.4541,  ..., 0.3537, 0.3537, 0.3712],
         [0.5022, 0.4760, 0.4323,  ..., 0.3668, 0.3624, 0.3886]],

        [[0.8079, 0.7904, 0.7424,  ..., 0.6987, 0.7074, 0.7293],
         [0.7991, 0.7948, 0.7424,  ..., 0.6856, 0.7074, 0.7293],
         [0.7948, 0.7860, 0.7467,  ..., 0.6769, 0.6987, 0.7205],
         ...,
         [0.8035, 0.7991, 0.7598,  ..., 0.6769, 0.6769, 0.6812],
         [0.7904, 0.7948, 0.7380,  ..., 0.6507, 0.6550, 0.6769],
         [0.7686, 0.7773, 0.7205,  ..., 0.6594, 0.6550, 0.6769]]])] ... )
> collate dict key "seg" out of 2 keys
>> collate/stack a list of tensors
Traceback (most recent call last):
  File "nucls_on_unet.py", line 195, in <module>
    main(img_file, mask_file, epoch_num=10)
  File "nucls_on_unet.py", line 138, in main
    for batch_data in train_loader:
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/monai/data/utils.py", line 495, in list_data_collate
    ret = collate_meta_tensor(data)
  File "/root/miniconda3/lib/python3.8/site-packages/monai/data/utils.py", line 464, in collate_meta_tensor
    return {k: collate_meta_tensor([d[k] for d in batch]) for k in elem_0}
  File "/root/miniconda3/lib/python3.8/site-packages/monai/data/utils.py", line 464, in <dictcomp>
    return {k: collate_meta_tensor([d[k] for d in batch]) for k in elem_0}
  File "/root/miniconda3/lib/python3.8/site-packages/monai/data/utils.py", line 454, in collate_meta_tensor
    collated = default_collate(batch)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 265, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 123, in collate
    return collate_fn_map[collate_type](batch, collate_fn_map=collate_fn_map)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 161, in collate_tensor_fn
    out = elem.new(storage).resize_(len(batch), *list(elem.size()))
  File "/root/miniconda3/lib/python3.8/site-packages/monai/data/meta_tensor.py", line 282, in __torch_function__
    ret = super().__torch_function__(func, types, args, kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_tensor.py", line 1386, in __torch_function__
    ret = func(*args, **kwargs)
RuntimeError: Trying to resize storage that is not resizable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/root/miniconda3/lib/python3.8/site-packages/monai/data/utils.py", line 508, in list_data_collate
    raise RuntimeError(re_str) from re
RuntimeError: Trying to resize storage that is not resizable

This is the whole problem! And my monai version is 1.3.0.
Thank you very much!

**Comment by SnoopyXI** [comment]
> I'm curious about this, I saw similar logs here #6901 but didn't have the data to replicate the issue.
I also used the same function -- RandCropByPosNegLabeld! haha
  train_transforms = Compose(
        [
            LoadImaged(keys=["img", "seg"]),
            EnsureChannelFirstd(keys=["img", "seg"]),
            ScaleIntensityd(keys=["img", "seg"]),
            RandCropByPosNegLabeld(
                keys=["img", "seg"], label_key="seg", spatial_size=[96, 96], 
                pos=1, neg=1, num_samples=2
            ),
            RandRotate90d(keys=["img", "seg"], prob=0.5, spatial_axes=[0, 1]),
        ]
    )
    val_transforms = Compose(
        [
            LoadImaged(keys=["img", "seg"]),
            EnsureChannelFirstd(keys=["img", "seg"]),
            ScaleIntensityd(keys=["img", "seg"]),
        ]
    )

**Comment by KumoLiu** [comment]
Hi @SnoopyXI, could you please share a data that can help us reproduce the error so that we can find out the reason? Thanks!

**Comment by SnoopyXI** [comment]
> Hi @SnoopyXI, could you please share a data that can help us reproduce the error so that we can find out the reason? Thanks!
Sure! The argument values were different from the above traceback, but I had met the same problem!

import logging
import os
import logging
import os
import sys
import math
import tempfile
from glob import glob
import matplotlib.pyplot as plt
import torch
from PIL import Image

import monai
from monai.data import list_data_collate, decollate_batch, DataLoader
from monai.inferers import sliding_window_inference
from monai.metrics import DiceMetric
from monai.transforms import (
    Activations,
    EnsureChannelFirstd,
    AsDiscrete,
    Compose,
    LoadImaged,
    RandCropByPosNegLabeld,
    RandRotate90d,
    ScaleIntensityd,
)

def plot_loss_and_metric(epoch_num, epoch_loss_values, metric_values):
    fig = plt.figure("train",(12, 6))
    # 绘制子图
    plt.subplot(1, 2, 1)
    plt.title("Epoch Average Loss")
    x = list(range(1, epoch_num+1))
    y1 = epoch_loss_values
    plot_data_1 = [x, y1]
    plt.xlabel("Epoch")
    plt.plot(plot_data_1[0],plot_data_1[1])
    plt.subplot(1, 2, 2)
    plt.title("Val Mean Dice")
    y2 = metric_values
    plot_data_2 = [x, y2]
    plt.xlabel("Epoch")
    plt.plot(plot_data_2[0],plot_data_2[1], color='red')
    # 保存
    fig.savefig('loss_and_metric.png')
    

def main(img_file, mask_file, epoch_num=10):
    '''
    img_file:所有图片文件的根目录
    mask_file:所有掩膜文件的根目录
    '''
    # 打印配置和日志信息
    # monai.config.print_config()
    # logging.basicConfig(stream=sys.stdout, level=logging.INFO)

    # 图片和掩膜文件路径
    images = sorted(glob(os.path.join(img_file, "*.png")))
    segs = sorted(glob(os.path.join(mask_file, "*.png")))
    train_files = [{"img": img, "seg": seg} for img, seg in zip(images[:-100], segs[:-100])]
    val_files = [{"img": img, "seg": seg} for img, seg in zip(images[-100:], segs[-100:])]
    
    # 数据增强
    # define transforms for image and segmentation
    train_transforms = Compose(
        [
            LoadImaged(keys=["img", "seg"]),
            EnsureChannelFirstd(keys=["img", "seg"]),
            ScaleIntensityd(keys=["img", "seg"]),
            # keys: 这是一个列表，指定了要应用此数据转换的数据字段，通常包括图像和对应的分割掩模。
            # label_key: 指定了用于识别正样本和负样本的标签的字段。
            # spatial_size: 指定了随机裁剪出的区域的空间尺寸（高度和宽度）。
            # pos: 指定了每次裁剪后的图片中要保留的正样本的数量。
            # neg: 指定了每次裁剪后的图片中要保留的负样本的数量。
            # num_samples: 指定了每个输入图像应生成的样本数量。
            RandCropByPosNegLabeld(
                keys=["img", "seg"], label_key="seg", spatial_size=[96, 96], 
                pos=1, neg=1, num_samples=2
            ),
            RandRotate90d(keys=["img", "seg"], prob=0.5, spatial_axes=[0, 1]),
        ]
    )
    val_transforms = Compose(
        [
            LoadImaged(keys=["img", "seg"]),
            EnsureChannelFirstd(keys=["img", "seg"]),
            ScaleIntensityd(keys=["img", "seg"]),
        ]
    )

    # 定义dataset和dataloader
    train_ds = monai.data.Dataset(data=train_files, transform=train_transforms)
    train_loader = DataLoader(
        train_ds,
        batch_size=4,
        shuffle=True,
        num_workers=8,
        collate_fn=list_data_collate,
        pin_memory=torch.cuda.is_available(),
    )

    val_ds = monai.data.Dataset(data=val_files, transform=val_transforms)
    # val_loader的batch_size参数只能为1，因为这里传入的是原始图片，尺寸不一样，不能stack
    val_loader = DataLoader(val_ds, batch_size=1, num_workers=14, collate_fn=list_data_collate)
    dice_metric = DiceMetric(include_background=True, reduction="mean", get_not_nans=False)
    post_trans = Compose([Activations(softmax=True), AsDiscrete(threshold=0.5)])

    # create UNet, DiceLoss and Adam optimizer
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    # spatial_dims=2: 指定了 UNet 模型的空间维度，这里是 2D 图像。
    # channels=(16, 32, 64, 128, 256): UNet 模型的通道数配置。这个参数定义了每个层级的通道数，通常从低分辨率到高分辨率逐渐增加。
    # strides=(2, 2, 2, 2): 每个层级的步幅配置。这个参数定义了每个池化和上采样操作的步幅，决定了特征图的尺寸变化。
    # num_res_units=2: UNet 模型中每个层级的残差单元的数量。残差单元用于学习特征表示，并有助于提高模型性能。
    model = monai.networks.nets.UNet(
        spatial_dims=2,
        in_channels=3,
        out_channels=14,
        channels=(16, 32, 64, 128, 256),
        strides=(2, 2, 2, 2),
        num_res_units=2,
    ).to(device)
    loss_function = monai.losses.DiceLoss(to_onehot_y=True)
    optimizer = torch.optim.Adam(model.parameters(), 1e-3)

    ###################正式开始训练###################
    val_interval = 2
    best_metric = -1
    best_metric_epoch = -1
    epoch_loss_values = list()
    metric_values = list()
    for epoch in range(epoch_num):
        print("-" * epoch_num)
        print(f"epoch {epoch + 1}/{epoch_num}")
        model.train()
        epoch_loss = 0
        step = 0
        ######### 训练 ##########
        for batch_data in train_loader:
            step += 1
            inputs, labels = batch_data["img"].to(device), batch_data["seg"].to(device)
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = loss_function(outputs, labels)
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item()
            epoch_len = math.ceil(len(train_ds) / train_loader.batch_size)  # 每个epoch中有多少个batch
            print(f"{step}/{epoch_len}, train_loss: {loss.item():.4f}")
        epoch_loss /= step  # 每个epoch的平均损失
        epoch_loss_values.append(epoch_loss)
        print(f"epoch {epoch + 1} average loss: {epoch_loss:.4f}")
        
        ######### 验证 ##########
        model.eval()
        with torch.no_grad():
            val_images = None
            val_labels = None
            val_outputs = None
            for val_data in val_loader:
                val_images, val_labels = val_data["img"].to(device), val_data["seg"].to(device)
                roi_size = (96, 96)  # 滑动窗口推断时输入图像的区域大小。
                sw_batch_size = 4  # sliding_window_batch_size，一次性输入到模型的小块数量
                val_outputs = sliding_window_inference(val_images, roi_size, sw_batch_size, model)
                val_outputs = [post_trans(i) for i in decollate_batch(val_outputs)]  # decollate_batch将模型输出中的这些小块分开，以便后续分析或可视化。
                # compute metric for current iteration
                dice_metric(y_pred=val_outputs, y=val_labels)
            # aggregate the final mean dice result
            metric = dice_metric.aggregate().item()
            # reset the status for next validation round
            dice_metric.reset()
            metric_values.append(metric)
            
            if metric > best_metric:
                best_metric = metric
                best_metric_epoch = epoch + 1
                # 获取当前py文件的文件名
                current_file_path = __file__          
                file_name = os.path.basename(current_file_path)
                torch.save(model.state_dict(), f"best_model_of_{file_name}.pth")
                print("saved new best metric model")
            print(
                "current epoch: {} current mean dice: {:.4f} best mean dice: {:.4f} at epoch {}".format(
                    epoch + 1, metric, best_metric, best_metric_epoch
                )
            )
    plot_loss_and_metric(epoch_num, epoch_loss_values, metric_values)
    print(f"train completed, best_metric: {best_metric:.4f} at epoch: {best_metric_epoch}")
    

if __name__ == "__main__":
    img_file = '/root/autodl-tmp/Dataset/QC/rgb'
    mask_file = '/root/autodl-tmp/Dataset/QC/mask_first_channel'
    torch.multiprocessing.set_start_method('spawn')
    main(img_file, mask_file, epoch_num=10)

**Comment by SnoopyXI** [comment]
Oh, I have solved the problem through #6903!!!! 
The problem was caused because image's size was different from mask's size!!!!
