### ISSUE TITLE
AttributeError: 'DintsAlgo' object has no attribute 'mlflow_tracking_uri'

### ISSUE THREAD

**Issue by KumoLiu** [Project-MONAI/MONAI#7184]
```
[2023-11-01T22:22:20.159Z] ======================================================================
[2023-11-01T22:22:20.159Z] ERROR: test_ensemble (__main__.TestEnsembleBuilder)
[2023-11-01T22:22:20.159Z] ----------------------------------------------------------------------
[2023-11-01T22:22:20.159Z] Traceback (most recent call last):
[2023-11-01T22:22:20.159Z]   File "/home/jenkins/agent/workspace/Monai-notebooks/MONAI/tests/test_auto3dseg_ensemble.py", line 162, in test_ensemble
[2023-11-01T22:22:20.159Z]     bundle_generator.generate(self.work_dir, num_fold=1)
[2023-11-01T22:22:20.159Z]   File "/home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/apps/auto3dseg/bundle_gen.py", line 598, in generate
[2023-11-01T22:22:20.159Z]     gen_algo.export_to_disk(output_folder, name, fold=f_id)
[2023-11-01T22:22:20.159Z]   File "/home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/apps/auto3dseg/bundle_gen.py", line 171, in export_to_disk
[2023-11-01T22:22:20.159Z]     self.fill_records = self.fill_template_config(self.data_stats_files, self.output_path, **kwargs)
[2023-11-01T22:22:20.159Z]   File "/tmp/tmpvqe9bmvp/workdir/algorithm_templates/dints/scripts/algo.py", line 124, in fill_template_config
[2023-11-01T22:22:20.159Z] AttributeError: 'DintsAlgo' object has no attribute 'mlflow_tracking_uri'
[2023-11-01T22:22:20.159Z] 
[2023-11-01T22:22:20.159Z] ----------------------------------------------------------------------
[2023-11-01T22:22:20.159Z] Ran 2 tests in 1.316s
[2023-11-01T22:22:20.159Z] 
[2023-11-01T22:22:20.159Z] FAILED (errors=1)
```

**Comment by wyli** [comment]
Probably addressed by https://github.com/Project-MONAI/research-contributions/pull/333 cc @dongyang0122
