### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by Zhongrocky** [Project-MONAI/MONAI#7256]
**Describe the bug**

**To Reproduce**
1. Go to Linux terminal
2. Install monai==1.1.0,ptorch==2.0.1,numpy==1.23.0
3. Run my_train.py

**Expected behavior**

**Screenshots**

Traceback (most recent call last):
  File "/CCTA2D/lib/python3.10/site-packages/monai/transforms/transform.py", line 102, in apply_transform
    return _apply_transform(transform, data, unpack_items)
  File "/CCTA2D/lib/python3.10/site-packages/monai/transforms/transform.py", line 66, in _apply_transform
    return transform(parameters)
  File "/CCTA2D/lib/python3.10/site-packages/monai/transforms/io/dictionary.py", line 154, in __call__
    data = self._loader(d[key], reader)
  File "/CCTA2D/lib/python3.10/site-packages/monai/transforms/io/array.py", line 266, in __call__
    raise RuntimeError(
RuntimeError: LoadImage cannot find a suitable reader for file: /Final_Data_real/train/FU WEI SU/raw_data.nii.gz.
    Please install the reader libraries, see also the installation instructions:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies.
   The current registered: [<monai.data.image_reader.NumpyReader object at 0x7f99d17edab0>, <monai.data.image_reader.PILReader object at 0x7f99d17edea0>].

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/CCTA2D/lib/python3.10/site-packages/monai/data/dataset.py", line 870, in _fill_cache
    return list(tqdm(p.imap(self._load_cache_item, indices), total=len(indices), desc="Loading dataset"))
  File "/CCTA2D/lib/python3.10/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/CCTA2D/lib/python3.10/multiprocessing/pool.py", line 870, in next
    raise value
  File "/CCTA2D/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/CCTA2D/lib/python3.10/site-packages/monai/data/dataset.py", line 884, in _load_cache_item
    item = apply_transform(_xform, item)
  File "/CCTA2D/lib/python3.10/site-packages/monai/transforms/transform.py", line 129, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.io.dictionary.LoadImaged object at 0x7f9ae34e73d0>

Process finished with exit code 1

**Environment**

Ensuring you use the relevant python executable, please paste the output of: python==3.10.0

```
python -c "import monai; monai.config.print_debug_info()"
```

**Additional context**

**Comment by KumoLiu** [comment]
Hi @Zhongrocky, could you please try `pip install nibabel`?
Thanks!

**Comment by Zhongrocky** [comment]
@KumoLiu Thank you for your help, it's ok.
