### ISSUE TITLE
FileNotFoundError in test_perceptual_loss

### ISSUE THREAD

**Issue by KumoLiu** [Project-MONAI/MONAI#7382]
```
[2024-01-10T02:16:36.089Z] ======================================================================
[2024-01-10T02:16:36.089Z] ERROR: test_identical_input_2 (tests.test_perceptual_loss.TestPerceptualLoss)
[2024-01-10T02:16:36.089Z] ----------------------------------------------------------------------
[2024-01-10T02:16:36.089Z] Traceback (most recent call last):
[2024-01-10T02:16:36.089Z]   File "/usr/local/lib/python3.10/dist-packages/parameterized/parameterized.py", line 620, in standalone_func
[2024-01-10T02:16:36.089Z]     return func(*(a + p.args), **p.kwargs, **kw)
[2024-01-10T02:16:36.089Z]   File "/opt/monai/tests/test_perceptual_loss.py", line 65, in test_identical_input
[2024-01-10T02:16:36.089Z]     loss = PerceptualLoss(**input_param)
[2024-01-10T02:16:36.089Z]   File "/opt/monai/monai/losses/perceptual.py", line 107, in __init__
[2024-01-10T02:16:36.089Z]     self.perceptual_function = RadImageNetPerceptualSimilarity(net=network_type, verbose=False)
[2024-01-10T02:16:36.090Z]   File "/opt/monai/monai/losses/perceptual.py", line 257, in __init__
[2024-01-10T02:16:36.090Z]     self.model = torch.hub.load("Warvito/radimagenet-models", model=net, verbose=verbose)
[2024-01-10T02:16:36.090Z]   File "/usr/local/lib/python3.10/dist-packages/torch/hub.py", line 565, in load
[2024-01-10T02:16:36.090Z]     model = _load_local(repo_or_dir, model, *args, **kwargs)
[2024-01-10T02:16:36.090Z]   File "/usr/local/lib/python3.10/dist-packages/torch/hub.py", line 594, in _load_local
[2024-01-10T02:16:36.090Z]     model = entry(*args, **kwargs)
[2024-01-10T02:16:36.090Z]   File "/root/.cache/torch/hub/Warvito_radimagenet-models_main/radimagenet_models/models/resnet.py", line 153, in radimagenet_resnet50
[2024-01-10T02:16:36.090Z]     model.load_state_dict(torch.load(cached_file))
[2024-01-10T02:16:36.090Z]   File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 988, in load
[2024-01-10T02:16:36.090Z]     with _open_file_like(f, 'rb') as opened_file:
[2024-01-10T02:16:36.090Z]   File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 437, in _open_file_like
[2024-01-10T02:16:36.090Z]     return _open_file(name_or_buffer, mode)
[2024-01-10T02:16:36.090Z]   File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 418, in __init__
[2024-01-10T02:16:36.090Z]     super().__init__(open(name, mode))
[2024-01-10T02:16:36.090Z] FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/torch/hub/checkpoints/RadImageNet-ResNet50_notop.pth'
[2024-01-10T02:16:36.090Z] 
[2024-01-10T02:16:36.090Z] ----------------------------------------------------------------------
[2024-01-10T02:16:36.090Z] Ran 13397 tests in 4093.907s
[2024-01-10T02:16:36.090Z] 
[2024-01-10T02:16:36.090Z] FAILED (errors=1, skipped=158)
```

**Comment by KumoLiu** [comment]
```
Access denied with the following error:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses. 
```
The cause of the error appears to be that the permission of the link has changed.
https://github.com/Project-MONAI/MONAI/blob/e1ffa7ebd38963bdced326d86979f5a9e2851517/monai/losses/perceptual.py#L257

Hi @marksgraham and @Warvito, would you mind taking a look at this one? Is there any reason you have done this or has it been done accidentally? Thanks!

**Comment by KumoLiu** [comment]
May not be due to permission but the issue described [here](https://github.com/wkentaro/gdown/issues/43#issuecomment-1382813663).

**Comment by marksgraham** [comment]
I can now download so I think the problem must be hitting a daily download limit. I think we need to move to a non g-drive solution for hosting these files. What is does in the rest of MONAI? 
@ericspod

**Comment by KumoLiu** [comment]
It may be about a daily download limit.
It has failed for three days and happened in other gdown-related tests.
https://github.com/Project-MONAI/MONAI/issues/7383
https://github.com/Project-MONAI/tutorials/issues/1608#issuecomment-1885373947

**Comment by ericspod** [comment]
This issue is either sorted with the gdown fix or it's a matter of moving temp files to the extra test data repo so I'd close this for now.
