### ISSUE TITLE
Broken download link in test_bundle_download

### ISSUE THREAD

**Issue by KumoLiu** [Project-MONAI/MONAI#7383]
```
[2024-01-10T00:38:35.456Z] ERROR: test_url_download_large_files_0 (tests.test_bundle_download.TestDownloadLargefiles)
[2024-01-10T00:38:35.456Z] ----------------------------------------------------------------------
[2024-01-10T00:38:35.456Z] Traceback (most recent call last):
[2024-01-10T00:38:35.456Z]   File "/home/jenkins/agent/workspace/Monai-latest-image/tests/utils.py", line 807, in command_line_tests
[2024-01-10T00:38:35.456Z]     normal_out = subprocess.run(cmd, env=test_env, check=True, capture_output=True)
[2024-01-10T00:38:35.456Z]   File "/opt/conda/lib/python3.8/subprocess.py", line 516, in run
[2024-01-10T00:38:35.456Z]     raise CalledProcessError(retcode, process.args,
[2024-01-10T00:38:35.456Z] subprocess.CalledProcessError: Command '['coverage', 'run', '-m', 'monai.bundle', 'download_large_files', '--bundle_path', '/tmp/tmp0oa200eb/test_bundle']' returned non-zero exit status 1.
[2024-01-10T00:38:35.456Z] 
[2024-01-10T00:38:35.456Z] The above exception was the direct cause of the following exception:
[2024-01-10T00:38:35.456Z] 
[2024-01-10T00:38:35.456Z] Traceback (most recent call last):
[2024-01-10T00:38:35.456Z]   File "/opt/conda/lib/python3.8/site-packages/parameterized/parameterized.py", line 620, in standalone_func
[2024-01-10T00:38:35.456Z]     return func(*(a + p.args), **p.kwargs, **kw)
[2024-01-10T00:38:35.456Z]   File "/home/jenkins/agent/workspace/Monai-latest-image/tests/test_bundle_download.py", line 360, in test_url_download_large_files
[2024-01-10T00:38:35.456Z]     command_line_tests(cmd)
[2024-01-10T00:38:35.456Z]   File "/home/jenkins/agent/workspace/Monai-latest-image/tests/utils.py", line 813, in command_line_tests
[2024-01-10T00:38:35.456Z]     raise RuntimeError(f"subprocess call error {e.returncode}: {errors}, {output}") from e
[2024-01-10T00:38:35.456Z] RuntimeError: subprocess call error 1: b'Traceback (most recent call last):
[2024-01-10T00:38:35.456Z]   File "/home/jenkins/agent/workspace/Monai-latest-image/monai/bundle/__main__.py", line 31, in <module>
[2024-01-10T00:38:35.456Z]     fire.Fire()
[2024-01-10T00:38:35.456Z]   File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
[2024-01-10T00:38:35.456Z]     component_trace = _Fire(component, args, parsed_flag_args, context, name)
[2024-01-10T00:38:35.456Z]   File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
[2024-01-10T00:38:35.456Z]     component, remaining_args = _CallAndUpdateTrace(
[2024-01-10T00:38:35.456Z]   File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
[2024-01-10T00:38:35.457Z]     component = fn(*varargs, **kwargs)
[2024-01-10T00:38:35.457Z]   File "/home/jenkins/agent/workspace/Monai-latest-image/monai/bundle/scripts.py", line 1797, in download_large_files
[2024-01-10T00:38:35.457Z]     download_url(**lf_data)
[2024-01-10T00:38:35.457Z]   File "/home/jenkins/agent/workspace/Monai-latest-image/monai/apps/utils.py", line 208, in download_url
[2024-01-10T00:38:35.457Z]     gdown.download(url, f"{tmp_name}", quiet=not progress, **gdown_kwargs)
[2024-01-10T00:38:35.457Z]   File "/opt/conda/lib/python3.8/site-packages/gdown/download.py", line 259, in download
[2024-01-10T00:38:35.457Z]     filename_from_url = m.groups()[0]
[2024-01-10T00:38:35.457Z] AttributeError: \'NoneType\' object has no attribute \'groups\'
[2024-01-10T00:38:35.457Z] ', b''
```

**Comment by KumoLiu** [comment]
Looks like the bug described here.
https://github.com/wkentaro/gdown/issues/43

The permissions on the file have been set to ``Anyone with the link''.
The problems, according to https://github.com/wkentaro/gdown/issues/43#issuecomment-1382813663, there are some limitations for access without OAuth to Google Drive and gdown cannot resolve it.

Do you have alternatives here? cc @ericspod @Nic-Ma
