### ISSUE TITLE
test_integration_nnunetv2_runner error

### ISSUE THREAD

**Issue by KumoLiu** [Project-MONAI/MONAI#7478]
test nnunetv2runner is broken after the recent update https://github.com/MIC-DKFZ/nnUNet/issues/1967#issuecomment-1956353741
```
[2024-02-19T23:30:47.247Z] ERROR: test_nnunetv2runner (__main__.TestnnUNetV2Runner)
[2024-02-19T23:30:47.247Z] ----------------------------------------------------------------------
[2024-02-19T23:30:47.247Z] Traceback (most recent call last):
[2024-02-19T23:30:47.247Z]   File "/home/jenkins/agent/workspace/Monai-notebooks/MONAI/tests/test_integration_nnunetv2_runner.py", line 87, in test_nnunetv2runner
[2024-02-19T23:30:47.247Z]     runner.run(run_train=False, run_find_best_configuration=False, run_predict_ensemble_postprocessing=False)
[2024-02-19T23:30:47.247Z]   File "/home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/apps/nnunet/nnunetv2_runner.py", line 954, in run
[2024-02-19T23:30:47.247Z]     self.plan_and_process()
[2024-02-19T23:30:47.247Z]   File "/home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/apps/nnunet/nnunetv2_runner.py", line 481, in plan_and_process
[2024-02-19T23:30:47.247Z]     self.extract_fingerprints(fpe, npfp, verify_dataset_integrity, clean, verbose)
[2024-02-19T23:30:47.247Z]   File "/home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/apps/nnunet/nnunetv2_runner.py", line 320, in extract_fingerprints
[2024-02-19T23:30:47.247Z]     from nnunetv2.experiment_planning.plan_and_preprocess_api import extract_fingerprints
[2024-02-19T23:30:47.247Z]   File "/usr/local/lib/python3.10/dist-packages/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 8, in <module>
[2024-02-19T23:30:47.247Z]     from nnunetv2.experiment_planning.experiment_planners.default_experiment_planner import ExperimentPlanner
[2024-02-19T23:30:47.247Z]   File "/usr/local/lib/python3.10/dist-packages/nnunetv2/experiment_planning/experiment_planners/default_experiment_planner.py", line 8, in <module>
[2024-02-19T23:30:47.247Z]     from dynamic_network_architectures.architectures.unet import PlainConvUNet, ResidualEncoderUNet
[2024-02-19T23:30:47.247Z] ImportError: cannot import name 'ResidualEncoderUNet' from 'dynamic_network_architectures.architectures.unet' (/usr/local/lib/python3.10/dist-packages/dynamic_network_architectures/architectures/unet.py)
```

**Comment by KumoLiu** [comment]
Fixed by new update https://github.com/MIC-DKFZ/dynamic-network-architectures.
