### ISSUE TITLE
Issue during transforms

### ISSUE THREAD

**Issue by DarthPenguinz** [Project-MONAI/MONAI#7537]
Hi, when executing the following transforms, I get this error 
train_transform = Compose(
    [   
        AddChanneld(keys=["image", "label"]),
        Spacingd(keys=['image', 'label'], pixdim=(1, 1, 1), mode=("bilinear", "nearest")),
        RandFlipd(keys=['image', 'label'], prob=0.5, spatial_axis=0),
        RandFlipd(keys=['image', 'label'], prob=0.5, spatial_axis=1),
        RandFlipd(keys=['image', 'label'], prob=0.5, spatial_axis=2),
        NormalizeIntensityd(keys='image', nonzero=True, channel_wise=True),
        RandScaleIntensityd(keys='image', factors=0.1, prob=1.0),
        RandShiftIntensityd(keys='image', offsets=0.1, prob=1.0),
        DivisiblePadd(k=16, keys=["image", "label"]),
        ToTensord(keys=['image', 'label'])
    ]
)

input data information of the runtime error transform:
name statistics:
Type: <class 'str'>
Value: BRATS_457.nii.gz
image statistics:
Type: <class 'numpy.ndarray'>
Shape: (1, 4, 240, 240, 155)
Value range: (0.0, 1260.0)
label statistics:
Type: <class 'numpy.ndarray'>
Shape: (1, 155, 240, 240)
Value range: (0.0, 3.0)
Traceback (most recent call last):
  File "/Users/ryanng/.pyenv/versions/deeplearning/lib/python3.9/site-packages/monai/transforms/transform.py", line 48, in apply_transform
    return transform(data)
  File "/Users/ryanng/.pyenv/versions/deeplearning/lib/python3.9/site-packages/monai/transforms/spatial/dictionary.py", line 201, in __call__
    meta_data = d[meta_data_key]
KeyError: 'image_meta_dict'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ryanng/Desktop/3D-UNet/train.py", line 42, in <module>
    for data in train_dataloader:
  File "/Users/ryanng/.pyenv/versions/deeplearning/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/Users/ryanng/.pyenv/versions/deeplearning/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/Users/ryanng/.pyenv/versions/deeplearning/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/ryanng/.pyenv/versions/deeplearning/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/ryanng/Desktop/3D-UNet/dataset.py", line 118, in __getitem__
    proccessed_out = self.transform[0](proccessed_out)
  File "/Users/ryanng/.pyenv/versions/deeplearning/lib/python3.9/site-packages/monai/transforms/compose.py", line 144, in __call__
    input_ = apply_transform(_transform, input_)
  File "/Users/ryanng/.pyenv/versions/deeplearning/lib/python3.9/site-packages/monai/transforms/transform.py", line 71, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.spatial.dictionary.Spacingd object at 0x31c885040>

**Comment by KumoLiu** [comment]
Hi @DarthPenguinz, which MONAI version did you use?

**Comment by DarthPenguinz** [comment]
Hi! I have tried 0.5.0 and 1.2.0

**Comment by KumoLiu** [comment]
Hi @DarthPenguinz, I don't think we have such a logic in 1.2.0 since we introduced `MetaTensor` from 0.9.1. So in 1.2.0, what error did you get?
https://github.com/Project- MONAI/MONAI/blob/c33f1ba588ee00229a309000e888f9817b4f1934/monai/transforms/spatial/dictionary.py#L358

**Comment by DarthPenguinz** [comment]
Hi this is the error from 1.2.0 Traceback (most recent call last):
  File "/Users/ryanng/.pyenv/versions/deeplearning/lib/python3.9/site-packages/monai/transforms/transform.py", line 141, in apply_transform
    return _apply_transform(transform, data, unpack_items, lazy, overrides, log_stats)
  File "/Users/ryanng/.pyenv/versions/deeplearning/lib/python3.9/site-packages/monai/transforms/transform.py", line 98, in _apply_transform
    return transform(data, lazy=lazy) if isinstance(transform, LazyTrait) else transform(data)
  File "/Users/ryanng/.pyenv/versions/deeplearning/lib/python3.9/site-packages/monai/transforms/spatial/dictionary.py", line 503, in __call__
    should_match = np.allclose(_init_shape, d[key].peek_pending_shape()) and np.allclose(
  File "/Users/ryanng/.pyenv/versions/deeplearning/lib/python3.9/site-packages/numpy/core/numeric.py", line 2241, in allclose
    res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
  File "/Users/ryanng/.pyenv/versions/deeplearning/lib/python3.9/site-packages/numpy/core/numeric.py", line 2351, in isclose
    return within_tol(x, y, atol, rtol)
  File "/Users/ryanng/.pyenv/versions/deeplearning/lib/python3.9/site-packages/numpy/core/numeric.py", line 2332, in within_tol
    return less_equal(abs(x-y), atol + rtol * abs(y))
ValueError: operands could not be broadcast together with shapes (4,) (3,) 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ryanng/Desktop/3D-UNet/train.py", line 44, in <module>
    for data in train_dataloader:
  File "/Users/ryanng/.pyenv/versions/deeplearning/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/Users/ryanng/.pyenv/versions/deeplearning/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/Users/ryanng/.pyenv/versions/deeplearning/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/ryanng/.pyenv/versions/deeplearning/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/ryanng/Desktop/3D-UNet/dataset.py", line 118, in __getitem__
    proccessed_out = self.transform[0](proccessed_out)
  File "/Users/ryanng/.pyenv/versions/deeplearning/lib/python3.9/site-packages/monai/transforms/compose.py", line 322, in __call__
    result = execute_compose(
  File "/Users/ryanng/.pyenv/versions/deeplearning/lib/python3.9/site-packages/monai/transforms/compose.py", line 111, in execute_compose
    data = apply_transform(
  File "/Users/ryanng/.pyenv/versions/deeplearning/lib/python3.9/site-packages/monai/transforms/transform.py", line 171, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.spatial.dictionary.Spacingd object at 0x32057c190>

**Comment by KumoLiu** [comment]
Hi @DarthPenguinz, could you please try with the latest version since there has been some [update](https://github.com/Project-MONAI/MONAI/commit/9fd6d4ced3efb344cf3b24c51d899d8fafc882d5) in `Spacingd` and replace `AddChanneld` with `EnsureChannelFirstd(channel_dim="no_channel")`?  Thanks.
