### ISSUE TITLE
Test error in test_clip_intensity_percentilesd.py

### ISSUE THREAD

**Issue by KumoLiu** [Project-MONAI/MONAI#7666]
```
[2024-04-18T08:39:45.332Z] ======================================================================
[2024-04-18T08:39:45.332Z] FAIL: test_hard_clipping_two_sided_0 (tests.test_clip_intensity_percentilesd.TestClipIntensityPercentilesd2D)
[2024-04-18T08:39:45.332Z] ----------------------------------------------------------------------
[2024-04-18T08:39:45.332Z] Traceback (most recent call last):
[2024-04-18T08:39:45.332Z]   File "/usr/local/lib/python3.8/dist-packages/parameterized/parameterized.py", line 620, in standalone_func
[2024-04-18T08:39:45.332Z]     return func(*(a + p.args), **p.kwargs, **kw)
[2024-04-18T08:39:45.332Z]   File "/home/jenkins/agent/workspace/MONAI-premerge/monai/tests/test_clip_intensity_percentilesd.py", line 35, in test_hard_clipping_two_sided
[2024-04-18T08:39:45.332Z]     assert_allclose(result[key], p(expected), type_test="tensor", rtol=1e-7, atol=0)
[2024-04-18T08:39:45.333Z]   File "/home/jenkins/agent/workspace/MONAI-premerge/monai/tests/utils.py", line 135, in assert_allclose
[2024-04-18T08:39:45.333Z]     np.testing.assert_allclose(actual, desired, *args, **kwargs)
[2024-04-18T08:39:45.333Z]   File "/usr/local/lib/python3.8/dist-packages/numpy/testing/_private/utils.py", line 1530, in assert_allclose
[2024-04-18T08:39:45.333Z]     assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
[2024-04-18T08:39:45.333Z]   File "/usr/local/lib/python3.8/dist-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
[2024-04-18T08:39:45.333Z]     raise AssertionError(msg)
[2024-04-18T08:39:45.333Z] AssertionError: 
[2024-04-18T08:39:45.333Z] Not equal to tolerance rtol=1e-07, atol=0
[2024-04-18T08:39:45.333Z] 
[2024-04-18T08:39:45.333Z] Mismatched elements: 410 / 8192 (5%)
[2024-04-18T08:39:45.333Z] Max absolute difference: 9.763241e-05
[2024-04-18T08:39:45.333Z] Max relative difference: 0.00011955
[2024-04-18T08:39:45.333Z]  x: array([[[[0., 0., 0., ..., 0., 0., 0.],
[2024-04-18T08:39:45.333Z]          [0., 0., 0., ..., 0., 0., 0.],
[2024-04-18T08:39:45.333Z]          [0., 0., 0., ..., 0., 0., 0.],...
[2024-04-18T08:39:45.333Z]  y: array([[[[0., 0., 0., ..., 0., 0., 0.],
[2024-04-18T08:39:45.333Z]          [0., 0., 0., ..., 0., 0., 0.],
[2024-04-18T08:39:45.333Z]          [0., 0., 0., ..., 0., 0., 0.],...
[2024-04-18T08:39:45.333Z] 
```

**Comment by KumoLiu** [comment]
Fixed by https://github.com/Project-MONAI/MONAI/pull/7659
