### ISSUE TITLE
RuntimeError: Can't redefine method: forward on class in test_unetr

### ISSUE THREAD

**Issue by KumoLiu** [Project-MONAI/MONAI#7939]
```
18:59:33  ======================================================================
18:59:33  ERROR: test_script_0 (tests.test_unetr.TestUNETR)
18:59:33  ----------------------------------------------------------------------
18:59:33  Traceback (most recent call last):
18:59:33    File "/usr/local/lib/python3.10/dist-packages/parameterized/parameterized.py", line 620, in standalone_func
18:59:33      return func(*(a + p.args), **p.kwargs, **kw)
18:59:33    File "/home/jenkins/agent/workspace/YunLiu-Monai-latest-image-2/tests/test_unetr.py", line 131, in test_script
18:59:33      torch.jit.script(net)
18:59:33    File "/usr/local/lib/python3.10/dist-packages/torch/jit/_script.py", line 1284, in script
18:59:33      return torch.jit._recursive.create_script_module(
18:59:33    File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 489, in create_script_module
18:59:33      return create_script_module_impl(nn_module, concrete_type, stubs_fn)
18:59:33    File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 551, in create_script_module_impl
18:59:33      script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
18:59:33    File "/usr/local/lib/python3.10/dist-packages/torch/jit/_script.py", line 614, in _construct
18:59:33      init_fn(script_module)
18:59:33    File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 529, in init_fn
18:59:33      scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
18:59:33    File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 551, in create_script_module_impl
18:59:33      script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
18:59:33    File "/usr/local/lib/python3.10/dist-packages/torch/jit/_script.py", line 614, in _construct
18:59:33      init_fn(script_module)
18:59:33    File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 529, in init_fn
18:59:33      scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
18:59:33    File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 551, in create_script_module_impl
18:59:33      script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
18:59:33    File "/usr/local/lib/python3.10/dist-packages/torch/jit/_script.py", line 614, in _construct
18:59:33      init_fn(script_module)
18:59:33    File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 529, in init_fn
18:59:33      scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
18:59:33    File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 551, in create_script_module_impl
18:59:33      script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
18:59:33    File "/usr/local/lib/python3.10/dist-packages/torch/jit/_script.py", line 614, in _construct
18:59:33      init_fn(script_module)
18:59:33    File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 529, in init_fn
18:59:33      scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
18:59:33    File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 555, in create_script_module_impl
18:59:33      create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
18:59:33    File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 406, in create_methods_and_properties_from_stubs
18:59:33      concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
18:59:33  RuntimeError: 
18:59:33  Expression of type | cannot be used in a type expression:
18:59:33    File "/home/jenkins/agent/workspace/YunLiu-Monai-latest-image-2/monai/networks/blocks/crossattention.py", line 123
18:59:33      def forward(self, x: torch.Tensor, context: torch.Tensor | None = None):
18:59:33                                                  ~~~~~~~~~~~~~~~~~~~ <--- HERE
18:59:33          """
18:59:33          Args:
18:59:33  
18:59:33  
18:59:33  ======================================================================
18:59:33  ERROR: test_script_1 (tests.test_unetr.TestUNETR)
18:59:33  ----------------------------------------------------------------------
18:59:33  Traceback (most recent call last):
18:59:33    File "/usr/local/lib/python3.10/dist-packages/parameterized/parameterized.py", line 620, in standalone_func
18:59:33      return func(*(a + p.args), **p.kwargs, **kw)
18:59:33    File "/home/jenkins/agent/workspace/YunLiu-Monai-latest-image-2/tests/test_unetr.py", line 131, in test_script
18:59:33      torch.jit.script(net)
18:59:33    File "/usr/local/lib/python3.10/dist-packages/torch/jit/_script.py", line 1284, in script
18:59:33      return torch.jit._recursive.create_script_module(
18:59:33    File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 489, in create_script_module
18:59:33      return create_script_module_impl(nn_module, concrete_type, stubs_fn)
18:59:33    File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 551, in create_script_module_impl
18:59:33      script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
18:59:33    File "/usr/local/lib/python3.10/dist-packages/torch/jit/_script.py", line 614, in _construct
18:59:33      init_fn(script_module)
18:59:33    File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 529, in init_fn
18:59:33      scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
18:59:33    File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 551, in create_script_module_impl
18:59:33      script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
18:59:33    File "/usr/local/lib/python3.10/dist-packages/torch/jit/_script.py", line 614, in _construct
18:59:33      init_fn(script_module)
18:59:33    File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 529, in init_fn
18:59:33      scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
18:59:33    File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 551, in create_script_module_impl
18:59:33      script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
18:59:33    File "/usr/local/lib/python3.10/dist-packages/torch/jit/_script.py", line 614, in _construct
18:59:33      init_fn(script_module)
18:59:33    File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 529, in init_fn
18:59:33      scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
18:59:33    File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 551, in create_script_module_impl
18:59:33      script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
18:59:33    File "/usr/local/lib/python3.10/dist-packages/torch/jit/_script.py", line 614, in _construct
18:59:33      init_fn(script_module)
18:59:33    File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 529, in init_fn
18:59:33      scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
18:59:33    File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 555, in create_script_module_impl
18:59:33      create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
18:59:33    File "/usr/local/lib/python3.10/dist-packages/torch/jit/_recursive.py", line 406, in create_methods_and_properties_from_stubs
18:59:33      concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
18:59:33  RuntimeError: Can't redefine method: forward on class: __torch__.monai.networks.blocks.crossattention.___torch_mangle_880.CrossAttentionBlock (of Python compilation unit at: 0x55a6bf890db0)
```

**Comment by AlexanderSanin** [comment]
I've submitted a PR implementing this fix: https://github.com/Project-MONAI/MONAI/pull/8879. Please review
