### ISSUE TITLE
About the error that occurs when transforms_compose

### ISSUE THREAD

**Issue by shenao1994** [Project-MONAI/MONAI#794]
Hi,I am a novice to MONAI, and I am building a program for classification. I want to input multi-modal images. So I use ConcatItemsd to input ADC and T2 images, but the program reports an error.
This is my code.

`  adc_train_data = '/Users/twelveshen/Desktop/Experiment2/train_data/Data_Extend/SPC+NPCvsNonCancer/originTrain/ADC'
    t2_train_data = '/Users/twelveshen/Desktop/Experiment2/train_data/Data_Extend/SPC+NPCvsNonCancer/originTrain/T2'
    t2_image_file_list = []
    adc_image_file_list = []
    image_label_list = []
    for t2ImgFile, adcImgFile in zip(os.listdir(t2_train_data), os.listdir(adc_train_data)):
        if t2ImgFile.endswith('.nii'):
            t2_image_file_list.append(os.path.join(t2_train_data, t2ImgFile))
            if 'NonCancer' in t2ImgFile:
                image_label_list.append(0)
            else:
                image_label_list.append(1)
        if adcImgFile.endswith('.nii'):
            adc_image_file_list.append(os.path.join(adc_train_data, adcImgFile))
    # 2 binary labels for gender classification: nonPCa and PCa
    train_files = [{"t2Img": t2Img, "adcImg": adcImg, "label": label} for t2Img, adcImg, label in zip(
        t2_image_file_list[:10], adc_image_file_list[:10], image_label_list[:10])]
    val_files = [{"t2Img": t2Img, "adcImg": adcImg, "label": label} for t2Img, adcImg, label in zip(
        t2_image_file_list[-10:], adc_image_file_list[-10:], image_label_list[-10:])]

    # Define transforms for image
    train_transforms = Compose(
        [
            LoadNiftid(keys=["t2Img", "adcImg"]),
            AddChanneld(keys=["t2Img", "adcImg"]),
            ConcatItemsd(keys=["t2Img", "adcImg"], name="inputs"),
            ScaleIntensityd(keys=["inputs"]),
            Resized(keys=["inputs"], spatial_size=(32, 32, 32)),
            RandRotate90d(keys=["inputs"], prob=0.8, spatial_axes=[0, 1]),
            ToTensord(keys=["inputs"]),
        ]
    )
    val_transforms = Compose(
        [
            LoadNiftid(keys=["t2Img", "adcImg"]),
            AddChanneld(keys=["t2Img", "adcImg"]),
            ScaleIntensityd(keys=["t2Img", "adcImg"]),
            Resized(keys=["t2Img", "adcImg"], spatial_size=(32, 32, 32)),
            ToTensord(keys=["t2Img", "adcImg"]),
        ]
    )

    # Define dataset, data loader
    check_ds = monai.data.Dataset(data=train_files, transform=train_transforms)
    check_loader = DataLoader(check_ds, batch_size=2, num_workers=4, pin_memory=torch.device)
    check_data = monai.utils.misc.first(check_loader)
    print(check_data["t2Img"].shape, check_data["adcImg"].shape, check_data["label"])

    # create a training data loader
    device = torch.device("cpu")
    train_ds = monai.data.Dataset(data=train_files, transform=train_transforms)
    train_loader = DataLoader(train_ds, batch_size=2, shuffle=True, num_workers=4, pin_memory=torch.device)

    # create a validation data loader
    val_ds = monai.data.Dataset(data=val_files, transform=val_transforms)
    val_loader = DataLoader(val_ds, batch_size=2, num_workers=4, pin_memory=torch.device)

    # Create DenseNet121, CrossEntropyLoss and Adam optimizer

    model = monai.networks.nets.densenet.densenet121(spatial_dims=3, in_channels=2, out_channels=2).to(device)
    loss_function = torch.nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters(), 1e-5)`

This is an error message.

Traceback (most recent call last):
  **File "/Users/twelveshen/Desktop/PythonWorkplace/MonAI/prostate_classification.py", line 140, in <module>
    main()
  File "/Users/twelveshen/Desktop/PythonWorkplace/MonAI/prostate_classification.py", line 63, in main
    check_data = monai.utils.misc.first(check_loader)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/monai/utils/misc.py", line 41, in first
    for i in iterable:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/monai/transforms/utils.py", line 276, in apply_transform
    return transform(data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/monai/transforms/utility/dictionary.py", line 420, in __call__
    d[self.name] = np.concatenate(output, axis=self.dim)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 31 and the array at index 1 has size 88

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/monai/transforms/utils.py", line 276, in apply_transform
    return transform(data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/monai/transforms/compose.py", line 229, in __call__
    input_ = apply_transform(_transform, input_)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/monai/transforms/utils.py", line 278, in apply_transform
    raise type(e)(f"applying transform {transform}.").with_traceback(e.__traceback__)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/monai/transforms/utils.py", line 276, in apply_transform
    return transform(data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/monai/transforms/utility/dictionary.py", line 420, in __call__
    d[self.name] = np.concatenate(output, axis=self.dim)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: applying transform <monai.transforms.utility.dictionary.ConcatItemsd object at 0x7fb80495f7b8>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/monai/data/dataset.py", line 56, in __getitem__
    data = apply_transform(self.transform, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/monai/transforms/utils.py", line 278, in apply_transform
    raise type(e)(f"applying transform {transform}.").with_traceback(e.__traceback__)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/monai/transforms/utils.py", line 276, in apply_transform
    return transform(data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/monai/transforms/compose.py", line 229, in __call__
    input_ = apply_transform(_transform, input_)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/monai/transforms/utils.py", line 278, in apply_transform
    raise type(e)(f"applying transform {transform}.").with_traceback(e.__traceback__)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/monai/transforms/utils.py", line 276, in apply_transform
    return transform(data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/monai/transforms/utility/dictionary.py", line 420, in __call__
    d[self.name] = np.concatenate(output, axis=self.dim)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: applying transform <monai.transforms.compose.Compose object at 0x7fb804ddec50>.**

I don't know how to solve it. Please help me.
Thanks！

**Comment by Nic-Ma** [comment]
Hi @shenao1994 ,

Here is the error message in your code:
```
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 31 and the array at index 1 has size 88
```
Seems your original image pairs are not the same shape, so you can't `ConcatItemsd` them directly.
And I saw you didn't concate items for validation transforms.
Maybe you can try with:
```py
train_transforms = Compose(
    [
        LoadNiftid(keys=["t2Img", "adcImg"]),
        AddChanneld(keys=["t2Img", "adcImg"]),
        Resized(keys=["t2Img", "adcImg"], spatial_size=(32, 32, 32)),
        ConcatItemsd(keys=["t2Img", "adcImg"], name="inputs"),
        ScaleIntensityd(keys=["inputs"]),
        RandRotate90d(keys=["inputs"], prob=0.8, spatial_axes=[0, 1]),
        ToTensord(keys=["inputs"]),
    ]
)
val_transforms = Compose(
    [
        LoadNiftid(keys=["t2Img", "adcImg"]),
        AddChanneld(keys=["t2Img", "adcImg"]),
        Resized(keys=["t2Img", "adcImg"], spatial_size=(32, 32, 32)),
        ConcatItemsd(keys=["t2Img", "adcImg"], name="inputs"),
        ScaleIntensityd(keys=["inputs"]),
        ToTensord(keys=["inputs"]),
    ]
)
```

Thanks.

**Comment by shenao1994** [comment]
@Nic-Ma 
Thank you very much! It worked!
