### ISSUE TITLE
ValueError: Expected int64 array-like in TestSlidingPatchWSIDatasetCuCIM

### ISSUE THREAD

**Issue by KumoLiu** [Project-MONAI/MONAI#8006]
```
ERROR: test_read_patches_large_1 (tests.test_sliding_patch_wsi_dataset.TestSlidingPatchWSIDatasetCuCIM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/parameterized/parameterized.py", line 620, in standalone_func
    return func(*(a + p.args), **p.kwargs, **kw)
  File "/home/runner/work/MONAI/MONAI/tests/test_sliding_patch_wsi_dataset.py", line 246, in test_read_patches_large
    for i, sample in enumerate(dataset):
  File "/home/runner/work/MONAI/MONAI/monai/data/dataset.py", line 108, in __getitem__
    return self._transform(index)
  File "/home/runner/work/MONAI/MONAI/monai/data/wsi_datasets.py", line 155, in _transform
    image, metadata = self._get_data(sample)
  File "/home/runner/work/MONAI/MONAI/monai/data/wsi_datasets.py", line 148, in _get_data
    return self.wsi_reader.get_data(wsi=wsi_obj, location=location, size=size, level=level)
  File "/home/runner/work/MONAI/MONAI/monai/data/wsi_reader.py", line 385, in get_data
    patch = self._get_patch(each_wsi, location=location, size=size, level=level, dtype=dtype_np, mode=mode)
  File "/home/runner/work/MONAI/MONAI/monai/data/wsi_reader.py", line 633, in _get_patch
    return self.reader._get_patch(wsi=wsi, location=location, size=size, level=level, dtype=dtype, mode=mode)
  File "/home/runner/work/MONAI/MONAI/monai/data/wsi_reader.py", line 810, in _get_patch
    patch: np.ndarray = wsi.read_region(
ValueError: Expected int64 array-like
```

**Comment by KumoLiu** [comment]
https://pypi.org/project/cucim-cu12/#history
