### ISSUE TITLE
update base docker image to nvcr.io/nvidia/pytorch:20.07-py3

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#943]
**Is your feature request related to a problem? Please describe.**
update from nvcr.io/nvidia/`pytorch:20.03-py3` to `pytorch:20.07-py3` -- this image has a prebuilt pytorch 1.6.

need to double-check the monai full tests and address any issues

**Comment by Nic-Ma** [comment]
I will update docker and rerun our AMP tutorial.

Thanks.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I executed all the MONAI tests in 20.08 docker, and faced below error:
```
... ...
test_correct_results_0 (tests.test_zoomd.TestZoomd) ... ok
test_correct_results_1 (tests.test_zoomd.TestZoomd) ... ok
test_correct_results_2 (tests.test_zoomd.TestZoomd) ... ok
test_invalid_inputs_0_no_zoom (tests.test_zoomd.TestZoomd) ... ok
test_invalid_inputs_1_invalid_order (tests.test_zoomd.TestZoomd) ... ok
test_keep_size (tests.test_zoomd.TestZoomd) ... ok

======================================================================
FAIL: test_training (tests.test_integration_segmentation_3d.IntegrationSegmentation3D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/data/medical/MONAI/tests/test_integration_segmentation_3d.py", line 326, in test_training
    np.testing.assert_allclose(ave, s, rtol=5e-3)
  File "/opt/conda/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 1528, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/opt/conda/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 840, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=0.005, atol=0

Mismatched elements: 1 / 1 (100%)
Max absolute difference: 0.0005179
Max relative difference: 0.00525773
 x: array(0.099021)
 y: array(0.098503)

----------------------------------------------------------------------
Ran 1190 tests in 1020.127s

FAILED (failures=1)

```
Seems something is slightly different in CUDA 11, I will update our CI env and tests.

Thanks.

**Comment by Nic-Ma** [comment]
Then I tried to execute in 20.07 docker(PyTorch 1.6), and faced below error:
```
test_correct_results_0 (tests.test_zoomd.TestZoomd) ... ok
test_correct_results_1 (tests.test_zoomd.TestZoomd) ... ok
test_correct_results_2 (tests.test_zoomd.TestZoomd) ... ok
test_invalid_inputs_0_no_zoom (tests.test_zoomd.TestZoomd) ... ok
test_invalid_inputs_1_invalid_order (tests.test_zoomd.TestZoomd) ... ok
test_keep_size (tests.test_zoomd.TestZoomd) ... ok

======================================================================
ERROR: test_value_0 (tests.test_lltm.TestLLTM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/parameterized/parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/workspace/data/medical/MONAI/tests/test_lltm.py", line 33, in test_value
    new_h, new_c = LLTM(**input_param)(x, (h, c))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 577, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/data/medical/MONAI/monai/networks/layers/simplelayers.py", line 175, in forward
    return LLTMFunction.apply(input, self.weights, self.bias, *state)
  File "/workspace/data/medical/MONAI/monai/networks/layers/simplelayers.py", line 127, in forward
    outputs = ext.lltm_forward(input, weights, bias, old_h, old_cell)
  File "/workspace/data/medical/MONAI/monai/utils/module.py", line 186, in __getattr__
    raise self._exception
  File "/workspace/data/medical/MONAI/monai/utils/module.py", line 146, in optional_import
    pkg = __import__(module)  # top level module
AttributeError: Optional import: import monai._C (/workspace/data/medical/MONAI/monai/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor2gtEN3c106ScalarE).

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

======================================================================
ERROR: test_value_cuda_0 (tests.test_lltm.TestLLTM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/parameterized/parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/workspace/data/medical/MONAI/tests/test_lltm.py", line 47, in test_value_cuda
    new_h, new_c = lltm(x, (h, c))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 577, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/data/medical/MONAI/monai/networks/layers/simplelayers.py", line 175, in forward
    return LLTMFunction.apply(input, self.weights, self.bias, *state)
  File "/workspace/data/medical/MONAI/monai/networks/layers/simplelayers.py", line 127, in forward
    outputs = ext.lltm_forward(input, weights, bias, old_h, old_cell)
  File "/workspace/data/medical/MONAI/monai/utils/module.py", line 186, in __getattr__
    raise self._exception
  File "/workspace/data/medical/MONAI/monai/utils/module.py", line 146, in optional_import
    pkg = __import__(module)  # top level module
AttributeError: Optional import: import monai._C_CUDA (/workspace/data/medical/MONAI/monai/_C_CUDA.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at5addmmERKNS_6TensorES2_S2_N3c106ScalarES4_).

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

======================================================================
FAIL: test_training (tests.test_integration_segmentation_3d.IntegrationSegmentation3D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/data/medical/MONAI/tests/test_integration_segmentation_3d.py", line 326, in test_training
    np.testing.assert_allclose(ave, s, rtol=5e-3)
  File "/opt/conda/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 1533, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/opt/conda/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 846, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.005, atol=0

Mismatched elements: 1 / 1 (100%)
Max absolute difference: 0.00049571
Max relative difference: 0.00503249
 x: array(0.098999)
 y: array(0.098503)

----------------------------------------------------------------------
Ran 1190 tests in 918.263s

FAILED (failures=1, errors=2)

```

Thanks.

**Comment by Nic-Ma** [comment]
I tried to install PyTorch 1.4 in 20.08, got error when run test:
```
root@apt-sh-ai:/workspace/data/medical/MONAI# python tests/test_integration_segmentation_3d.py 
terminate called after throwing an instance of 'H5::DataSpaceIException'
Aborted (core dumped)âââââââââââââââââ
```

Seems it can't support PyTorch 1.4 anymore.

Thanks.
