### ISSUE TITLE
PersistentDataset breaks if given existing folder

### ISSUE THREAD

**Issue by danieltudosiu** [Project-MONAI/MONAI#948]
**Describe the bug**
If we pass a string to the cache_dir argument of the PersistentDataset that points towards an already existing directory the dataset creation will error out. 

**To Reproduce**
Create a folder (I used pathlib.Path.mkdir) and pass the absolute path string to cache_dir argument.

**Expected behavior**
The existing folder is used and caching happens.

**Actual behavior**
The following error happens:
```
Traceback (most recent call last):
  File "/home/danieltudosiu/projects/nmpevqvae/code_fine_tuning/experiment.py", line 123, in <module>
    conditional_in_channels = iter(data_loader).__next__()[
  File "/home/danieltudosiu/projects/nmpevqvae/evenv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/danieltudosiu/projects/nmpevqvae/evenv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 403, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/danieltudosiu/projects/nmpevqvae/evenv/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/danieltudosiu/projects/nmpevqvae/evenv/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/danieltudosiu/projects/nmpevqvae/evenv/lib/python3.6/site-packages/monai/data/dataset.py", line 197, in __getitem__
    pre_random_item = self._pre_first_random_cachecheck(self.data[index])
  File "/home/danieltudosiu/projects/nmpevqvae/evenv/lib/python3.6/site-packages/monai/data/dataset.py", line 176, in _pre_first_random_cachecheck
    json.dumps(item_transformed, sort_keys=True).encode("utf-8")
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ndarray' is not JSON serializable
```

**Environment (please complete the following information):**
 - OS - Ubuntu 18.04
 - Python version - 3.6
 - MONAI version [e.g. git commit hash] - 0.2 release
 - CUDA/cuDNN version - 11/8.0.2
 - GPU models and configuration - 2 x Titan V

**Comment by ericspod** [comment]
To add a little more, from what I see in the code the way in which we're calculating an MD5 hash isn't compatible with ndarray types so we should fix that or use some other way to deterministically choose cache filenames. No directory is being created in this class so if a non-existent directory is given (or the default None) nothing gets cached.

Also the key [here](https://github.com/Project-MONAI/MONAI/blob/40b85f85beb9e1c36d7053b2a4d33b459adc600e/monai/data/dataset.py#L192) should be "cached".

**Comment by Nic-Ma** [comment]
Hi @ericspod ,

I submitted PR #951 to add support to create dir if not existing.
And I think we discussed how to hash numpy array before, it's not easy to hash float numbers, so I think maybe we can just fix the `not existing dir` issue in this ticket first?

Thanks.
