### ISSUE TITLE
Failed to build from the latest source cloned from git 

### ISSUE THREAD

**Issue by jslalu** [Project-MONAI/MONAI#979]
I cloned the latest source code from git and tried to build with python setup.py develop as suggested in the doc, but the following errors occured. Could anyone point out what is the problem?

setup.py with torch 1.5.1
running develop
running egg_info
writing monai.egg-info\PKG-INFO
writing dependency_links to monai.egg-info\dependency_links.txt
writing requirements to monai.egg-info\requires.txt
writing top-level names to monai.egg-info\top_level.txt
reading manifest file 'monai.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'monai.egg-info\SOURCES.txt'
running build_ext
C:\Users\Admin\anaconda3\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py:238: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'monai._C' extension
Emitting ninja build file D:\Projects\MONAI\build\temp.win-amd64-3.6\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -IC:\Users\Admin\anaconda3\envs\pytorch\lib\site-packages\torch\include -IC:\Users\Admin\anaconda3\envs\pytorch\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\Admin\anaconda3\envs\pytorch\lib\site-packages\torch\include\TH -IC:\Users\Admin\anaconda3\envs\pytorch\lib\site-packages\torch\include\THC -IC:\Users\Admin\anaconda3\envs\pytorch\include -IC:\Users\Admin\anaconda3\envs\pytorch\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt" -c D:\Projects\MONAI\monai\networks\extensions\lltm\lltm.cpp /FoD:\Projects\MONAI\build\temp.win-amd64-3.6\Release\monai/networks/extensions/lltm/lltm.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
FAILED: D:/Projects/MONAI/build/temp.win-amd64-3.6/Release/monai/networks/extensions/lltm/lltm.obj
cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -IC:\Users\Admin\anaconda3\envs\pytorch\lib\site-packages\torch\include -IC:\Users\Admin\anaconda3\envs\pytorch\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\Admin\anaconda3\envs\pytorch\lib\site-packages\torch\include\TH -IC:\Users\Admin\anaconda3\envs\pytorch\lib\site-packages\torch\include\THC -IC:\Users\Admin\anaconda3\envs\pytorch\include -IC:\Users\Admin\anaconda3\envs\pytorch\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt" -c D:\Projects\MONAI\monai\networks\extensions\lltm\lltm.cpp /FoD:\Projects\MONAI\build\temp.win-amd64-3.6\Release\monai/networks/extensions/lltm/lltm.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
CreateProcess failed: The system cannot find the file specified.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1423, in _run_ninja_build
    check=True)
  File "C:\Users\Admin\anaconda3\envs\pytorch\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 58, in <module>
    ext_modules=get_extensions(),
  File "C:\Users\Admin\anaconda3\envs\pytorch\lib\site-packages\setuptools\__init__.py", line 161, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\Admin\anaconda3\envs\pytorch\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\Admin\anaconda3\envs\pytorch\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\Admin\anaconda3\envs\pytorch\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\Admin\anaconda3\envs\pytorch\lib\site-packages\setuptools\command\develop.py", line 38, in run
    self.install_for_development()
  File "C:\Users\Admin\anaconda3\envs\pytorch\lib\site-packages\setuptools\command\develop.py", line 140, in install_for_development
    self.run_command('build_ext')
  File "C:\Users\Admin\anaconda3\envs\pytorch\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Admin\anaconda3\envs\pytorch\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\Admin\anaconda3\envs\pytorch\lib\site-packages\setuptools\command\build_ext.py", line 87, in run
    _build_ext.run(self)
  File "C:\Users\Admin\anaconda3\envs\pytorch\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "C:\Users\Admin\anaconda3\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 603, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\Admin\anaconda3\envs\pytorch\lib\distutils\command\build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\Admin\anaconda3\envs\pytorch\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\Admin\anaconda3\envs\pytorch\lib\site-packages\setuptools\command\build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\Admin\anaconda3\envs\pytorch\lib\distutils\command\build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "C:\Users\Admin\anaconda3\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 585, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "C:\Users\Admin\anaconda3\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1163, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "C:\Users\Admin\anaconda3\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1436, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

**Comment by wyli** [comment]
`C:\Users\Admin\anaconda3\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py:238: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified` this looks like a pytorch issue, perhaps could try reinstall/upgrade pytorch?

**Comment by wyli** [comment]
couldn't identify the root cause (probably it's a local environment issue), added an option to skip the build `SKIP_MONAI_BUILD=1 python setup.py develop`
